import { BINDINGS_VERSION } from "@seldon/factory/bindings/version"

import type {
  BindingsFramework,
  BindingsMode,
  DeclarationSite,
  ExpressionInput,
  PropBinding,
  RefConsumer,
  SlotConsumer,
} from "@seldon/factory/bindings/types"

/**
 * Reads a `bindings.json` written by the scripts in a user's project.
 *
 * The file is untrusted. It is produced outside the editor by a script the user
 * can edit, it can be stale, hand-written, or generated by a different version,
 * and every string in it is rendered in the interface. So nothing is taken on
 * trust: each field is checked, text is clamped, collections are capped, and an
 * entry that fails a check is dropped and counted rather than believed.
 *
 * Refs and slots come back as maps. A crafted key such as `__proto__` assigned
 * into a plain object would reach a prototype, and a map has no such path.
 */

const MAX_REFS = 2000
const MAX_SLOT_COMPONENTS = 2000
const MAX_CONSUMERS_PER_KEY = 200
const MAX_PROPS_PER_CONSUMER = 100
const MAX_INPUTS_PER_EXPRESSION = 50
const MAX_TEXT_LENGTH = 500

const DECLARATION_KINDS = new Set(["const", "let", "function", "import", "parameter"])

export interface ValidatedBindings {
  mode: BindingsMode
  framework: BindingsFramework
  scannedFiles: number
  refs: Map<string, RefConsumer[]>
  slots: Map<string, Map<string, SlotConsumer[]>>
  /** Entries that failed a check. A count above zero means the file is suspect. */
  droppedEntries: number
}

export type BindingsResult =
  | { ok: true; bindings: ValidatedBindings }
  | { ok: false; reason: string }

export function readBindingsManifest(text: string): BindingsResult {
  let parsed: unknown

  try {
    parsed = JSON.parse(text)
  } catch {
    return { ok: false, reason: "The binding manifest is not valid JSON." }
  }

  if (!isRecord(parsed)) {
    return { ok: false, reason: "The binding manifest is not an object." }
  }

  if (parsed.version !== BINDINGS_VERSION) {
    return {
      ok: false,
      reason: `The binding manifest was written for format ${String(parsed.version)}, and this editor reads format ${BINDINGS_VERSION}. Re-run the bindings script.`,
    }
  }

  const mode = parsed.mode === "full" || parsed.mode === "shallow" ? parsed.mode : null

  if (!mode) {
    return { ok: false, reason: "The binding manifest does not say how it was scanned." }
  }

  const framework =
    parsed.framework === "react" || parsed.framework === "vue" ? parsed.framework : null

  if (!framework) {
    return { ok: false, reason: "The binding manifest does not name a known framework." }
  }

  const dropped = { count: 0 }

  return {
    ok: true,
    bindings: {
      mode,
      framework,
      scannedFiles: readCount(parsed.scannedFiles),
      refs: readRefs(parsed.refs, dropped),
      slots: readSlots(parsed.slots, dropped),
      droppedEntries: dropped.count,
    },
  }
}

interface DroppedCounter {
  count: number
}

function readRefs(value: unknown, dropped: DroppedCounter): Map<string, RefConsumer[]> {
  const refs = new Map<string, RefConsumer[]>()

  if (!isRecord(value)) return refs

  for (const [ref, consumers] of Object.entries(value)) {
    if (refs.size >= MAX_REFS) break

    if (!isUsableKey(ref) || !Array.isArray(consumers)) {
      dropped.count += 1
      continue
    }

    const read = readList(consumers, readRefConsumer, dropped)

    if (read.length > 0) refs.set(ref, read)
  }

  return refs
}

function readSlots(
  value: unknown,
  dropped: DroppedCounter,
): Map<string, Map<string, SlotConsumer[]>> {
  const slots = new Map<string, Map<string, SlotConsumer[]>>()

  if (!isRecord(value)) return slots

  for (const [component, bySlot] of Object.entries(value)) {
    if (slots.size >= MAX_SLOT_COMPONENTS) break

    if (!isUsableKey(component) || !isRecord(bySlot)) {
      dropped.count += 1
      continue
    }

    const slotMap = new Map<string, SlotConsumer[]>()

    for (const [slot, consumers] of Object.entries(bySlot)) {
      if (!isUsableKey(slot) || !Array.isArray(consumers)) {
        dropped.count += 1
        continue
      }

      const read = readList(consumers, readSlotConsumer, dropped)

      if (read.length > 0) slotMap.set(slot, read)
    }

    if (slotMap.size > 0) slots.set(component, slotMap)
  }

  return slots
}

function readRefConsumer(value: unknown): RefConsumer | null {
  if (!isRecord(value)) return null

  const file = readText(value.file)
  const line = readCount(value.line)

  if (!file) return null

  return {
    file,
    component: readText(value.component) ?? "",
    line,
    conditional: value.conditional === true,
    expression: readText(value.expression) ?? "",
    inputs: readInputs(value.inputs),
    props: readProps(value.props),
  }
}

function readSlotConsumer(value: unknown): SlotConsumer | null {
  if (!isRecord(value)) return null

  const file = readText(value.file)

  if (!file) return null

  return {
    file,
    component: readText(value.component) ?? "",
    line: readCount(value.line),
    expression: readText(value.expression) ?? "",
    inputs: readInputs(value.inputs),
    spread: value.spread === true,
  }
}

function readProps(value: unknown): PropBinding[] {
  if (!Array.isArray(value)) return []

  const props: PropBinding[] = []

  for (const entry of value) {
    if (props.length >= MAX_PROPS_PER_CONSUMER) break
    if (!isRecord(entry)) continue

    const key = readText(entry.key)

    if (!key) continue

    props.push({
      key,
      expression: readText(entry.expression) ?? "",
      inputs: readInputs(entry.inputs),
    })
  }

  return props
}

function readInputs(value: unknown): ExpressionInput[] {
  if (!Array.isArray(value)) return []

  const inputs: ExpressionInput[] = []

  for (const entry of value) {
    if (inputs.length >= MAX_INPUTS_PER_EXPRESSION) break
    if (!isRecord(entry)) continue

    const name = readText(entry.name)

    if (!name) continue

    inputs.push({ name, declaredAt: readDeclarationSite(entry.declaredAt) })
  }

  return inputs
}

function readDeclarationSite(value: unknown): DeclarationSite | null {
  if (!isRecord(value)) return null
  if (typeof value.kind !== "string" || !DECLARATION_KINDS.has(value.kind)) return null

  const site: DeclarationSite = {
    line: readCount(value.line),
    kind: value.kind as DeclarationSite["kind"],
  }

  const via = readText(value.via)
  const module = readText(value.module)

  if (via) site.via = via
  if (module) site.module = module

  return site
}

/** Reads a capped list, counting every entry that failed its check. */
function readList<T>(
  values: unknown[],
  read: (value: unknown) => T | null,
  dropped: DroppedCounter,
): T[] {
  const items: T[] = []

  for (const value of values) {
    if (items.length >= MAX_CONSUMERS_PER_KEY) break

    const item = read(value)

    if (item) {
      items.push(item)
    } else {
      dropped.count += 1
    }
  }

  return items
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value)
}

/** A key must be a non-empty string that is not absurdly long. */
function isUsableKey(key: string): boolean {
  return key.length > 0 && key.length <= MAX_TEXT_LENGTH
}

/** Trims and clamps display text, so one entry cannot flood the interface. */
function readText(value: unknown): string | undefined {
  if (typeof value !== "string") return undefined

  const trimmed = value.trim()

  if (trimmed.length === 0) return undefined

  return trimmed.length > MAX_TEXT_LENGTH ? `${trimmed.slice(0, MAX_TEXT_LENGTH)}\u2026` : trimmed
}

/** A non-negative whole number, or zero when the value is unusable. */
function readCount(value: unknown): number {
  if (typeof value !== "number" || !Number.isFinite(value) || value < 0) return 0

  return Math.floor(value)
}
