/*****
 *
 * This code was generated using Seldon (https://github.com/SeldonDigital/seldon)
 *
 * License: https://github.com/SeldonDigital/seldon/blob/main/LICENSE.md
 * Do not redistribute or sublicense without permission.
 *
 * You may not use this software, or any derivative works of it, in whole or in part,
 * for the purposes of training, fine-tuning, or otherwise improving (directly or indirectly)
 * any machine learning or artificial intelligence system without written permission.
 *
 *****/
import { SVGAttributes } from "react"
import * as Icons from "../icons/index"
import { combineClassNames } from "../utils/class-name"

export interface IconProps extends SVGAttributes<SVGElement> {
  className?: string
  icon?:
    | "__default__"
    | "material-chevronDown"
    | "material-keyboardArrowRight"
    | "material-keyboardArrowDown"
    | "seldon-more"
    | "material-add"
    | "material-moreHoriz"
    | "material-unfoldMore"
    | "seldon-iconSocialFacebook"
    | "seldon-iconSocialQuora"
    | "seldon-iconSocialReddit"
    | "seldon-iconSocialPinterest"
    | "seldon-iconSocialTiktok"
    | "seldon-iconSocialWhatsapp"
    | "seldon-iconSocialLinkedin"
    | "seldon-iconSocialSpotify"
    | "seldon-iconSocialTwitch"
    | "seldon-iconSocialYoutube"
    | "seldon-iconSocialDiscord"
    | "seldon-iconSocialTwitter"
    | "seldon-iconSocialMedium"
    | "seldon-iconSocialTelegram"
    | "seldon-iconSocialInstagram"
    | "seldon-iconSocialGithub"
    | "seldon-deviceCustom"
    | "seldon-deviceDesktop"
    | "seldon-deviceLaptop"
    | "seldon-deviceMobile"
    | "seldon-deviceTv"
    | "seldon-deviceTablet"
    | "seldon-deviceWatch"
    | "seldon-alignTop"
    | "seldon-alignBottom"
    | "seldon-codeCube"
    | "seldon-alignRight"
    | "seldon-alignLeft"
    | "seldon-background"
    | "seldon-angle"
    | "seldon-border"
    | "seldon-color"
    | "seldon-computed"
    | "seldon-corner"
    | "seldon-custom"
    | "seldon-display"
    | "seldon-empty"
    | "seldon-frameColumns"
    | "seldon-frameRows"
    | "seldon-gap"
    | "seldon-gradient"
    | "seldon-hexagon"
    | "seldon-hidden"
    | "seldon-none"
    | "seldon-positionBottom"
    | "seldon-positionCenter"
    | "seldon-positionTop"
    | "seldon-positionBottomLeft"
    | "seldon-positionBottomRight"
    | "seldon-positionLeft"
    | "seldon-positionRight"
    | "seldon-positionTopLeft"
    | "seldon-positionTopRight"
    | "seldon-frameBackground"
    | "seldon-screen"
    | "seldon-shadow"
    | "seldon-spread"
    | "seldon-step"
    | "seldon-stub"
    | "seldon-theme"
    | "seldon-valuePx"
    | "seldon-valueRem"
    | "seldon-fitHorizontal"
    | "seldon-fitVertical"
    | "seldon-orientationHorizontal"
    | "seldon-orientationVertical"
    | "seldon-swatch"
    | "seldon-padding"
    | "seldon-margin"
    | "seldon-width"
    | "seldon-height"
    | "seldon-opacity"
    | "seldon-brightness"
    | "seldon-case"
    | "seldon-style"
    | "seldon-borderStyle"
    | "seldon-borderColor"
    | "seldon-backgroundColor"
    | "seldon-align"
    | "seldon-rotation"
    | "seldon-toolComponent"
    | "seldon-toolSketch"
    | "seldon-ai"
    | "seldon-cursor"
    | "seldon-default"
    | "seldon-edited"
    | "seldon-frame"
    | "seldon-missing"
    | "seldon-reset"
    | "seldon-size"
    | "seldon-sketchCircle"
    | "seldon-sketchPencil"
    | "seldon-sketchRectangle"
    | "seldon-sketchText"
    | "seldon-toolArrow"
    | "seldon-toolImageAi"
    | "seldon-clip"
    | "seldon-addChart"
    | "seldon-assistantNavigation"
    | "seldon-checkboxOff"
    | "seldon-checkboxOn"
    | "seldon-iconInput"
    | "seldon-inputType"
    | "seldon-minus"
    | "seldon-plus"
    | "seldon-retry"
    | "seldon-x"
    | "seldon-token"
    | "seldon-upload"
    | "seldon-duplicate"
    | "seldon-preview"
    | "seldon-fullScreen"
    | "seldon-spark"
    | "seldon-component"
    | "seldon-componentDefault"
    | "seldon-componentVariant"
    | "seldon-icon"
    | "seldon-input"
    | "seldon-image"
    | "seldon-imageFit"
    | "seldon-content"
    | "seldon-iconFrame"
    | "seldon-iconImage"
    | "seldon-vector"
    | "seldon-parts"
    | "seldon-primitives"
    | "seldon-modules"
    | "seldon-elements"
    | "seldon-panels"
    | "seldon-catalog"
    | "seldon-photograph"
    | "seldon-chevronDoubleDown"
    | "seldon-chevronDoubleLeft"
    | "seldon-chevronDoubleP"
    | "seldon-chevronDoubleRight"
    | "seldon-chevronDown"
    | "seldon-chevronP"
    | "seldon-battery0Bar"
    | "seldon-batteryFullAlt"
    | "seldon-batteryHoriz000"
    | "seldon-batteryHoriz050"
    | "seldon-batteryHoriz075"
    | "seldon-batteryLow"
    | "seldon-heartPlus"
    | "seldon-robot"
    | "seldon-thumbP"
    | "seldon-ticket"
    | "seldon-radioOff"
    | "seldon-radioOn"
    | "seldon-lines"
    | "seldon-text"
    | "seldon-font"
    | "seldon-fontFamily"
    | "seldon-fontLetterSpacing"
    | "seldon-fontLineHeight"
    | "seldon-fontSize"
    | "seldon-fontTextAlignCenter"
    | "seldon-fontTextAlignJustify"
    | "seldon-fontTextAlignLeft"
    | "seldon-fontTextAlignRight"
    | "seldon-fontTextDecoration"
    | "seldon-fontTextWrap"
    | "seldon-fontWeight"
    | "seldon-iconText"
    | "seldon-rtl"
    | "seldon-textAlign"
    | "material-monetizationOn"
    | "material-payment"
    | "material-receipt"
    | "material-restore"
    | "material-restoreFromTrash"
    | "material-sdCard"
    | "material-shoppingBag"
    | "material-shoppingCart"
    | "material-simCard"
    | "material-store"
    | "material-storefront"
    | "material-tag"
    | "material-workspacePremium"
    | "material-business"
    | "material-businessCenter"
    | "material-corporateFare"
    | "material-report"
    | "material-reportProblem"
    | "material-work"
    | "material-workOff"
    | "material-workOutline"
    | "material-filterList"
    | "material-filterListOff"
    | "material-gridView"
    | "material-storage"
    | "material-viewList"
    | "material-archive"
    | "material-cloud"
    | "material-cloudDone"
    | "material-cloudOff"
    | "material-cloudQueue"
    | "material-cloudSync"
    | "material-folder"
    | "material-folderOpen"
    | "material-bookmark"
    | "material-bookmarkBorder"
    | "material-emojiEmotions"
    | "material-favorite"
    | "material-favoriteBorder"
    | "material-flag"
    | "material-grade"
    | "material-mood"
    | "material-moodBad"
    | "material-star"
    | "material-starBorder"
    | "material-accountCircle"
    | "material-person"
    | "material-verifiedUser"
    | "material-engineering"
    | "material-fitnessCenter"
    | "material-fitPageHeight"
    | "material-fitPageWidth"
    | "material-localHospital"
    | "material-localPharmacy"
    | "material-apartment"
    | "material-hotel"
    | "material-house"
    | "material-meetingRoom"
    | "material-label"
    | "material-lightbulb"
    | "material-sports"
    | "material-airlineSeatFlat"
    | "material-airlineSeatFlatAngled"
    | "material-airlineSeatIndividualSuite"
    | "material-airlineSeatReclineExtra"
    | "material-airlineSeatReclineNormal"
    | "material-carpenter"
    | "material-directions"
    | "material-directionsBike"
    | "material-directionsBus"
    | "material-directionsCar"
    | "material-directionsRailway"
    | "material-directionsRun"
    | "material-directionsSubway"
    | "material-directionsTransit"
    | "material-directionsWalk"
    | "material-localTaxi"
    | "material-locationDisabled"
    | "material-locationOn"
    | "material-locationSearching"
    | "material-map"
    | "material-myLocation"
    | "material-pinDrop"
    | "material-batteryChargingFull"
    | "material-batteryFull"
    | "material-batteryStd"
    | "material-power"
    | "material-signalCellularOff"
    | "material-block"
    | "material-fingerprint"
    | "material-lock"
    | "material-lockOpen"
    | "material-security"
    | "material-vpnKey"
    | "material-adminPanelSettings"
    | "material-powerSettingsNew"
    | "material-settings"
    | "material-addCircle"
    | "material-addCircleOutline"
    | "material-apps"
    | "material-autorenew"
    | "material-build"
    | "material-cancel"
    | "material-cleaningServices"
    | "material-clear"
    | "material-cloudDownload"
    | "material-cloudUpload"
    | "material-contentCopy"
    | "material-contentCut"
    | "material-contentPaste"
    | "material-dashboard"
    | "material-delete"
    | "material-dns"
    | "material-domain"
    | "material-done"
    | "material-download"
    | "material-edit"
    | "material-electricalServices"
    | "material-extension"
    | "material-face"
    | "material-fileDownload"
    | "material-fileUpload"
    | "material-forum"
    | "material-handyman"
    | "material-help"
    | "material-inbox"
    | "material-memory"
    | "material-personAdd"
    | "material-plumbing"
    | "material-refresh"
    | "material-remove"
    | "material-removeCircle"
    | "material-save"
    | "material-search"
    | "material-share"
    | "material-sort"
    | "material-splitscreenAdd"
    | "material-splitscreenVerticalAdd"
    | "material-sync"
    | "material-upload"
    | "material-verified"
    | "material-widgets"
    | "material-zoomIn"
    | "material-zoomOut"
    | "material-comment"
    | "material-email"
    | "material-helpOutline"
    | "material-localLaundryService"
    | "material-phone"
    | "material-audiotrack"
    | "material-blurOff"
    | "material-colorLens"
    | "material-fastRewind"
    | "material-filter"
    | "material-fullscreen"
    | "material-fullscreenExit"
    | "material-gradient"
    | "material-image"
    | "material-invertColorsOff"
    | "material-palette"
    | "material-pause"
    | "material-photo"
    | "material-rateReview"
    | "material-reviews"
    | "material-stop"
    | "material-tune"
    | "material-videocam"
    | "material-volumeOff"
    | "material-arrowBack"
    | "material-arrowDownward"
    | "material-arrowForward"
    | "material-arrowLeft"
    | "material-arrowRight"
    | "material-arrowUpward"
    | "material-backspace"
    | "material-brightnessAuto"
    | "material-brightnessHigh"
    | "material-brightnessLow"
    | "material-brightnessMedium"
    | "material-chevronDoubleDown"
    | "material-chevronDoubleLeft"
    | "material-chevronDoubleRight"
    | "material-chevronDoubleUp"
    | "material-chevronLeft"
    | "material-chevronRight"
    | "material-event"
    | "material-fastForward"
    | "material-feedback"
    | "material-group"
    | "material-home"
    | "material-homeWork"
    | "material-keyboardArrowLeft"
    | "material-keyboardArrowUp"
    | "material-link"
    | "material-menu"
    | "material-more"
    | "material-moreVert"
    | "material-playArrow"
    | "material-router"
    | "material-skipNext"
    | "material-skipPrevious"
    | "material-support"
    | "material-thumbP"
    | "material-volumeDown"
    | "material-volumeUp"
    | "material-batteryAlert"
    | "material-blurOn"
    | "material-blurCircular"
    | "material-deblur"
    | "material-style"
    | "material-width"
    | "material-height"
    | "material-roundedCorner"
    | "material-lineWeight"
    | "material-alignCenter"
    | "material-alignEnd"
    | "material-alignFlexCenter"
    | "material-alignFlexEnd"
    | "material-alignFlexStart"
    | "material-alignHorizontalCenter"
    | "material-alignItemsStretch"
    | "material-alignJustifyCenter"
    | "material-alignJustifyFlexEnd"
    | "material-alignJustifyFlexStart"
    | "material-alignJustifySpaceAround"
    | "material-alignJustifySpaceBetween"
    | "material-alignJustifySpaceEven"
    | "material-alignJustifyStretch"
    | "material-alignSelfStretch"
    | "material-alignSpaceAround"
    | "material-alignSpaceBetween"
    | "material-alignSpaceEven"
    | "material-alignStart"
    | "material-alignStretch"
    | "material-alignVerticalBottom"
    | "material-alignVerticalCenter"
    | "material-alignVerticalTop"
    | "material-alignHorizontalLeft"
    | "material-alignHorizontalRight"
    | "material-desktopLandscape"
    | "material-desktopPortrait"
    | "material-formatTextdirectionLToR"
    | "material-formatTextdirectionRToL"
    | "material-formatTextdirectionVertical"
    | "material-bolt"
    | "material-check"
    | "material-checkCircle"
    | "material-checkCircleOutline"
    | "material-close"
    | "material-construction"
    | "material-contrast"
    | "material-colors"
    | "material-piano"
    | "material-formatSize"
    | "material-textFormat"
    | "material-titlecase"
    | "material-asterisk"
    | "material-article"
    | "material-attribution"
    | "material-doneAll"
    | "material-dryCleaning"
    | "material-error"
    | "material-expandLess"
    | "material-expandMore"
    | "material-info"
    | "material-invertColors"
    | "material-localFireDepartment"
    | "material-localPolice"
    | "material-nearMeDisabled"
    | "material-networkCheck"
    | "material-notifications"
    | "material-notificationsActive"
    | "material-notificationsNone"
    | "material-opacity"
    | "material-powerOff"
    | "material-print"
    | "material-robot"
    | "material-signalWifiOff"
    | "material-unfoldLess"
    | "material-visibility"
    | "material-visibilityOff"
    | "material-codeOff"
    | "material-codeXml"
    | "material-textSelectStart"
    | "material-deployedCode"
    | "material-dataObject"
    | "material-copyAll"
    | "material-aspectRatio"
    | "material-mouse"
    | "material-highlightMouseCursor"
    | "material-highlightTextCursor"
    | "material-dragPan"
    | "material-resize"
    | "material-adsClick"
    | "material-gridOn"
    | "material-driveFileMoveOutline"
    | "material-openWith"
    | "material-doNotDisturbOn"
    | "material-panTool"
    | "material-panToolAlt"
    | "material-syncAlt"
    | "material-circle"
    | "material-layers"
    | "material-lineStartCircle"
    | "material-lineEndCircle"
    | "material-formatAlignLeft"
    | "material-formatAlignRight"
    | "material-formatAlignCenter"
    | "material-formatAlignJustify"
    | "material-matchCase"
    | "material-warning"
    | "material-wifi"
    | "material-wifiOff"
    | "material-code"
    | "material-texture"
    | "material-viewModule"
    | "material-compassCalibration"
    | "material-navigation"
    | "material-nearMe"
    | "material-place"
    | "material-room"
    | "material-calendarToday"
    | "material-eventSeat"
    | "material-schedule"
    | "material-sentimentDissatisfied"
    | "material-sentimentNeutral"
    | "material-sentimentSatisfied"
}

/*****
 * Icon: Icon
 * Level: Primitive
 * Intent: Displays a vector or symbolic icon representing an action or concept.
 * Tags: icon, symbol, graphic, primitive, UI, decoration
 * Type: Default
 *
 * @example
 * ```tsx
 * <Icon
 *   icon="__default__"
 * />
 * ```
 *****/
export function Icon({ className = "", icon = sdn.icon, ...props }: IconProps) {
  const iconClassName = combineClassNames("sdn-icon", className)

  let Icon = iconMap[icon || "__default__"]
  if (!Icon) {
    Icon = iconMap["__default__"]
  }
  //
  // React JSX component with merged default and custom properties
  //
  return <Icon className={iconClassName} {...props} />
}

//
// Default property values
//
const sdn: IconProps = {
  icon: "__default__",
  className: "sdn-icon",
}
const iconMap = {
  __default__: Icons.IconDefault,
  "material-chevronDown": Icons.IconMaterialChevronDown,
  "material-keyboardArrowRight": Icons.IconMaterialKeyboardArrowRight,
  "material-keyboardArrowDown": Icons.IconMaterialKeyboardArrowDown,
  "seldon-more": Icons.IconSeldonMore,
  "material-add": Icons.IconMaterialAdd,
  "material-moreHoriz": Icons.IconMaterialMoreHoriz,
  "material-unfoldMore": Icons.IconMaterialUnfoldMore,
  "seldon-iconSocialFacebook": Icons.IconSocialFacebook,
  "seldon-iconSocialQuora": Icons.IconSocialQuora,
  "seldon-iconSocialReddit": Icons.IconSocialReddit,
  "seldon-iconSocialPinterest": Icons.IconSocialPinterest,
  "seldon-iconSocialTiktok": Icons.IconSocialTiktok,
  "seldon-iconSocialWhatsapp": Icons.IconSocialWhatsapp,
  "seldon-iconSocialLinkedin": Icons.IconSocialLinkedin,
  "seldon-iconSocialSpotify": Icons.IconSocialSpotify,
  "seldon-iconSocialTwitch": Icons.IconSocialTwitch,
  "seldon-iconSocialYoutube": Icons.IconSocialYoutube,
  "seldon-iconSocialDiscord": Icons.IconSocialDiscord,
  "seldon-iconSocialTwitter": Icons.IconSocialTwitter,
  "seldon-iconSocialMedium": Icons.IconSocialMedium,
  "seldon-iconSocialTelegram": Icons.IconSocialTelegram,
  "seldon-iconSocialInstagram": Icons.IconSocialInstagram,
  "seldon-iconSocialGithub": Icons.IconSocialGithub,
  "seldon-deviceCustom": Icons.IconSeldonDeviceCustom,
  "seldon-deviceDesktop": Icons.IconSeldonDeviceDesktop,
  "seldon-deviceLaptop": Icons.IconSeldonDeviceLaptop,
  "seldon-deviceMobile": Icons.IconSeldonDeviceMobile,
  "seldon-deviceTv": Icons.IconSeldonDeviceTV,
  "seldon-deviceTablet": Icons.IconSeldonDeviceTablet,
  "seldon-deviceWatch": Icons.IconSeldonDeviceWatch,
  "seldon-alignTop": Icons.IconSeldonAlignTop,
  "seldon-alignBottom": Icons.IconSeldonAlignBottom,
  "seldon-codeCube": Icons.IconSeldonCodeCube,
  "seldon-alignRight": Icons.IconSeldonAlignRight,
  "seldon-alignLeft": Icons.IconSeldonAlignLeft,
  "seldon-background": Icons.IconSeldonBackground,
  "seldon-angle": Icons.IconSeldonAngle,
  "seldon-border": Icons.IconSeldonBorder,
  "seldon-color": Icons.IconSeldonColor,
  "seldon-computed": Icons.IconSeldonComputed,
  "seldon-corner": Icons.IconSeldonCorner,
  "seldon-custom": Icons.IconSeldonCustom,
  "seldon-display": Icons.IconSeldonDisplay,
  "seldon-empty": Icons.IconSeldonEmpty,
  "seldon-frameColumns": Icons.IconSeldonFrameColumns,
  "seldon-frameRows": Icons.IconSeldonFrameRows,
  "seldon-gap": Icons.IconSeldonGap,
  "seldon-gradient": Icons.IconSeldonGradient,
  "seldon-hexagon": Icons.IconSeldonHexagon,
  "seldon-hidden": Icons.IconSeldonHidden,
  "seldon-none": Icons.IconSeldonNone,
  "seldon-positionBottom": Icons.IconSeldonPositionBottom,
  "seldon-positionCenter": Icons.IconSeldonPositionCenter,
  "seldon-positionTop": Icons.IconSeldonPositionTop,
  "seldon-positionBottomLeft": Icons.IconSeldonPositionBottomLeft,
  "seldon-positionBottomRight": Icons.IconSeldonPositionBottomRight,
  "seldon-positionLeft": Icons.IconSeldonPositionLeft,
  "seldon-positionRight": Icons.IconSeldonPositionRight,
  "seldon-positionTopLeft": Icons.IconSeldonPositionTopLeft,
  "seldon-positionTopRight": Icons.IconSeldonPositionTopRight,
  "seldon-frameBackground": Icons.IconSeldonFrameBackground,
  "seldon-screen": Icons.IconSeldonScreen,
  "seldon-shadow": Icons.IconSeldonShadow,
  "seldon-spread": Icons.IconSeldonSpread,
  "seldon-step": Icons.IconSeldonStep,
  "seldon-stub": Icons.IconSeldonStub,
  "seldon-theme": Icons.IconSeldonTheme,
  "seldon-valuePx": Icons.IconSeldonValuePx,
  "seldon-valueRem": Icons.IconSeldonValueRem,
  "seldon-fitHorizontal": Icons.IconSeldonFitHorizontal,
  "seldon-fitVertical": Icons.IconSeldonFitVertical,
  "seldon-orientationHorizontal": Icons.IconSeldonOrientationHorizontal,
  "seldon-orientationVertical": Icons.IconSeldonOrientationVertical,
  "seldon-swatch": Icons.IconSeldonSwatch,
  "seldon-padding": Icons.IconSeldonPadding,
  "seldon-margin": Icons.IconSeldonMargin,
  "seldon-width": Icons.IconSeldonWidth,
  "seldon-height": Icons.IconSeldonHeight,
  "seldon-opacity": Icons.IconSeldonOpacity,
  "seldon-brightness": Icons.IconSeldonBrightness,
  "seldon-case": Icons.IconSeldonCase,
  "seldon-style": Icons.IconSeldonStyle,
  "seldon-borderStyle": Icons.IconSeldonBorderStyle,
  "seldon-borderColor": Icons.IconSeldonBorderColor,
  "seldon-backgroundColor": Icons.IconSeldonBackgroundColor,
  "seldon-align": Icons.IconSeldonAlign,
  "seldon-rotation": Icons.IconSeldonRotation,
  "seldon-toolComponent": Icons.IconSeldonToolComponent,
  "seldon-toolSketch": Icons.IconSeldonToolSketch,
  "seldon-ai": Icons.IconSeldonAi,
  "seldon-cursor": Icons.IconSeldonCursor,
  "seldon-default": Icons.IconSeldonDefault,
  "seldon-edited": Icons.IconSeldonEdited,
  "seldon-frame": Icons.IconSeldonFrame,
  "seldon-missing": Icons.IconSeldonMissing,
  "seldon-reset": Icons.IconSeldonReset,
  "seldon-size": Icons.IconSeldonSize,
  "seldon-sketchCircle": Icons.IconSeldonSketchCircle,
  "seldon-sketchPencil": Icons.IconSeldonSketchPencil,
  "seldon-sketchRectangle": Icons.IconSeldonSketchRectangle,
  "seldon-sketchText": Icons.IconSeldonSketchText,
  "seldon-toolArrow": Icons.IconSeldonToolArrow,
  "seldon-toolImageAi": Icons.IconSeldonToolImageAi,
  "seldon-clip": Icons.IconSeldonClip,
  "seldon-addChart": Icons.IconSeldonAddChart,
  "seldon-assistantNavigation": Icons.IconSeldonAssistantNavigation,
  "seldon-checkboxOff": Icons.IconSeldonCheckboxOff,
  "seldon-checkboxOn": Icons.IconSeldonCheckboxOn,
  "seldon-iconInput": Icons.IconSeldonIconInput,
  "seldon-inputType": Icons.IconSeldonInputType,
  "seldon-minus": Icons.IconSeldonMinus,
  "seldon-plus": Icons.IconSeldonPlus,
  "seldon-retry": Icons.IconSeldonRetry,
  "seldon-x": Icons.IconSeldonX,
  "seldon-token": Icons.IconSeldonToken,
  "seldon-upload": Icons.IconSeldonUpload,
  "seldon-duplicate": Icons.IconSeldonDuplicate,
  "seldon-preview": Icons.IconSeldonPreview,
  "seldon-fullScreen": Icons.IconSeldonFullScreen,
  "seldon-spark": Icons.IconSeldonSpark,
  "seldon-component": Icons.IconSeldonComponent,
  "seldon-componentDefault": Icons.IconSeldonComponentDefault,
  "seldon-componentVariant": Icons.IconSeldonComponentVariant,
  "seldon-icon": Icons.IconSeldonIcon,
  "seldon-input": Icons.IconSeldonInput,
  "seldon-image": Icons.IconSeldonImage,
  "seldon-imageFit": Icons.IconSeldonImageFit,
  "seldon-content": Icons.IconSeldonContent,
  "seldon-iconFrame": Icons.IconSeldonIconFrame,
  "seldon-iconImage": Icons.IconSeldonIconImage,
  "seldon-vector": Icons.IconSeldonVector,
  "seldon-parts": Icons.IconSeldonParts,
  "seldon-primitives": Icons.IconSeldonPrimitives,
  "seldon-modules": Icons.IconSeldonModules,
  "seldon-elements": Icons.IconSeldonElements,
  "seldon-panels": Icons.IconSeldonPanels,
  "seldon-catalog": Icons.IconSeldonCatalog,
  "seldon-photograph": Icons.IconSeldonPhotograph,
  "seldon-chevronDoubleDown": Icons.IconSeldonChevronDoubleDown,
  "seldon-chevronDoubleLeft": Icons.IconSeldonChevronDoubleLeft,
  "seldon-chevronDoubleP": Icons.IconSeldonChevronDoubleP,
  "seldon-chevronDoubleRight": Icons.IconSeldonChevronDoubleRight,
  "seldon-chevronDown": Icons.IconSeldonChevronDown,
  "seldon-chevronP": Icons.IconSeldonChevronP,
  "seldon-battery0Bar": Icons.IconSeldonBattery0Bar,
  "seldon-batteryFullAlt": Icons.IconSeldonBatteryFullAlt,
  "seldon-batteryHoriz000": Icons.IconSeldonBatteryHoriz000,
  "seldon-batteryHoriz050": Icons.IconSeldonBatteryHoriz050,
  "seldon-batteryHoriz075": Icons.IconSeldonBatteryHoriz075,
  "seldon-batteryLow": Icons.IconSeldonBatteryLow,
  "seldon-heartPlus": Icons.IconSeldonHeartPlus,
  "seldon-robot": Icons.IconSeldonRobot,
  "seldon-thumbP": Icons.IconSeldonThumbP,
  "seldon-ticket": Icons.IconSeldonTicket,
  "seldon-radioOff": Icons.IconSeldonRadioOff,
  "seldon-radioOn": Icons.IconSeldonRadioOn,
  "seldon-lines": Icons.IconSeldonLines,
  "seldon-text": Icons.IconSeldonText,
  "seldon-font": Icons.IconSeldonFont,
  "seldon-fontFamily": Icons.IconSeldonFontFamily,
  "seldon-fontLetterSpacing": Icons.IconSeldonFontLetterSpacing,
  "seldon-fontLineHeight": Icons.IconSeldonFontLineHeight,
  "seldon-fontSize": Icons.IconSeldonFontSize,
  "seldon-fontTextAlignCenter": Icons.IconSeldonFontTextAlignCenter,
  "seldon-fontTextAlignJustify": Icons.IconSeldonFontTextAlignJustify,
  "seldon-fontTextAlignLeft": Icons.IconSeldonFontTextAlignLeft,
  "seldon-fontTextAlignRight": Icons.IconSeldonFontTextAlignRight,
  "seldon-fontTextDecoration": Icons.IconSeldonFontTextDecoration,
  "seldon-fontTextWrap": Icons.IconSeldonFontTextWrap,
  "seldon-fontWeight": Icons.IconSeldonFontWeight,
  "seldon-iconText": Icons.IconSeldonIconText,
  "seldon-rtl": Icons.IconSeldonRtl,
  "seldon-textAlign": Icons.IconSeldonTextAlign,
  "material-monetizationOn": Icons.IconMaterialMonetizationOn,
  "material-payment": Icons.IconMaterialPayment,
  "material-receipt": Icons.IconMaterialReceipt,
  "material-restore": Icons.IconMaterialRestore,
  "material-restoreFromTrash": Icons.IconMaterialRestoreFromTrash,
  "material-sdCard": Icons.IconMaterialSdCard,
  "material-shoppingBag": Icons.IconMaterialShoppingBag,
  "material-shoppingCart": Icons.IconMaterialShoppingCart,
  "material-simCard": Icons.IconMaterialSimCard,
  "material-store": Icons.IconMaterialStore,
  "material-storefront": Icons.IconMaterialStorefront,
  "material-tag": Icons.IconMaterialTag,
  "material-workspacePremium": Icons.IconMaterialWorkspacePremium,
  "material-business": Icons.IconMaterialBusiness,
  "material-businessCenter": Icons.IconMaterialBusinessCenter,
  "material-corporateFare": Icons.IconMaterialCorporateFare,
  "material-report": Icons.IconMaterialReport,
  "material-reportProblem": Icons.IconMaterialReportProblem,
  "material-work": Icons.IconMaterialWork,
  "material-workOff": Icons.IconMaterialWorkOff,
  "material-workOutline": Icons.IconMaterialWorkOutline,
  "material-filterList": Icons.IconMaterialFilterList,
  "material-filterListOff": Icons.IconMaterialFilterListOff,
  "material-gridView": Icons.IconMaterialGridView,
  "material-storage": Icons.IconMaterialStorage,
  "material-viewList": Icons.IconMaterialViewList,
  "material-archive": Icons.IconMaterialArchive,
  "material-cloud": Icons.IconMaterialCloud,
  "material-cloudDone": Icons.IconMaterialCloudDone,
  "material-cloudOff": Icons.IconMaterialCloudOff,
  "material-cloudQueue": Icons.IconMaterialCloudQueue,
  "material-cloudSync": Icons.IconMaterialCloudSync,
  "material-folder": Icons.IconMaterialFolder,
  "material-folderOpen": Icons.IconMaterialFolderOpen,
  "material-bookmark": Icons.IconMaterialBookmark,
  "material-bookmarkBorder": Icons.IconMaterialBookmarkBorder,
  "material-emojiEmotions": Icons.IconMaterialEmojiEmotions,
  "material-favorite": Icons.IconMaterialFavorite,
  "material-favoriteBorder": Icons.IconMaterialFavoriteBorder,
  "material-flag": Icons.IconMaterialFlag,
  "material-grade": Icons.IconMaterialGrade,
  "material-mood": Icons.IconMaterialMood,
  "material-moodBad": Icons.IconMaterialMoodBad,
  "material-star": Icons.IconMaterialStar,
  "material-starBorder": Icons.IconMaterialStarBorder,
  "material-accountCircle": Icons.IconMaterialAccountCircle,
  "material-person": Icons.IconMaterialPerson,
  "material-verifiedUser": Icons.IconMaterialVerifiedUser,
  "material-engineering": Icons.IconMaterialEngineering,
  "material-fitnessCenter": Icons.IconMaterialFitnessCenter,
  "material-fitPageHeight": Icons.IconMaterialFitPageHeight,
  "material-fitPageWidth": Icons.IconMaterialFitPageWidth,
  "material-localHospital": Icons.IconMaterialLocalHospital,
  "material-localPharmacy": Icons.IconMaterialLocalPharmacy,
  "material-apartment": Icons.IconMaterialApartment,
  "material-hotel": Icons.IconMaterialHotel,
  "material-house": Icons.IconMaterialHouse,
  "material-meetingRoom": Icons.IconMaterialMeetingRoom,
  "material-label": Icons.IconMaterialLabel,
  "material-lightbulb": Icons.IconMaterialLightbulb,
  "material-sports": Icons.IconMaterialSports,
  "material-airlineSeatFlat": Icons.IconMaterialAirlineSeatFlat,
  "material-airlineSeatFlatAngled": Icons.IconMaterialAirlineSeatFlatAngled,
  "material-airlineSeatIndividualSuite":
    Icons.IconMaterialAirlineSeatIndividualSuite,
  "material-airlineSeatReclineExtra": Icons.IconMaterialAirlineSeatReclineExtra,
  "material-airlineSeatReclineNormal":
    Icons.IconMaterialAirlineSeatReclineNormal,
  "material-carpenter": Icons.IconMaterialCarpenter,
  "material-directions": Icons.IconMaterialDirections,
  "material-directionsBike": Icons.IconMaterialDirectionsBike,
  "material-directionsBus": Icons.IconMaterialDirectionsBus,
  "material-directionsCar": Icons.IconMaterialDirectionsCar,
  "material-directionsRailway": Icons.IconMaterialDirectionsRailway,
  "material-directionsRun": Icons.IconMaterialDirectionsRun,
  "material-directionsSubway": Icons.IconMaterialDirectionsSubway,
  "material-directionsTransit": Icons.IconMaterialDirectionsTransit,
  "material-directionsWalk": Icons.IconMaterialDirectionsWalk,
  "material-localTaxi": Icons.IconMaterialLocalTaxi,
  "material-locationDisabled": Icons.IconMaterialLocationDisabled,
  "material-locationOn": Icons.IconMaterialLocationOn,
  "material-locationSearching": Icons.IconMaterialLocationSearching,
  "material-map": Icons.IconMaterialMap,
  "material-myLocation": Icons.IconMaterialMyLocation,
  "material-pinDrop": Icons.IconMaterialPinDrop,
  "material-batteryChargingFull": Icons.IconMaterialBatteryChargingFull,
  "material-batteryFull": Icons.IconMaterialBatteryFull,
  "material-batteryStd": Icons.IconMaterialBatteryStd,
  "material-power": Icons.IconMaterialPower,
  "material-signalCellularOff": Icons.IconMaterialSignalCellularOff,
  "material-block": Icons.IconMaterialBlock,
  "material-fingerprint": Icons.IconMaterialFingerprint,
  "material-lock": Icons.IconMaterialLock,
  "material-lockOpen": Icons.IconMaterialLockOpen,
  "material-security": Icons.IconMaterialSecurity,
  "material-vpnKey": Icons.IconMaterialVpnKey,
  "material-adminPanelSettings": Icons.IconMaterialAdminPanelSettings,
  "material-powerSettingsNew": Icons.IconMaterialPowerSettingsNew,
  "material-settings": Icons.IconMaterialSettings,
  "material-addCircle": Icons.IconMaterialAddCircle,
  "material-addCircleOutline": Icons.IconMaterialAddCircleOutline,
  "material-apps": Icons.IconMaterialApps,
  "material-autorenew": Icons.IconMaterialAutorenew,
  "material-build": Icons.IconMaterialBuild,
  "material-cancel": Icons.IconMaterialCancel,
  "material-cleaningServices": Icons.IconMaterialCleaningServices,
  "material-clear": Icons.IconMaterialClear,
  "material-cloudDownload": Icons.IconMaterialCloudDownload,
  "material-cloudUpload": Icons.IconMaterialCloudUpload,
  "material-contentCopy": Icons.IconMaterialContentCopy,
  "material-contentCut": Icons.IconMaterialContentCut,
  "material-contentPaste": Icons.IconMaterialContentPaste,
  "material-dashboard": Icons.IconMaterialDashboard,
  "material-delete": Icons.IconMaterialDelete,
  "material-dns": Icons.IconMaterialDns,
  "material-domain": Icons.IconMaterialDomain,
  "material-done": Icons.IconMaterialDone,
  "material-download": Icons.IconMaterialDownload,
  "material-edit": Icons.IconMaterialEdit,
  "material-electricalServices": Icons.IconMaterialElectricalServices,
  "material-extension": Icons.IconMaterialExtension,
  "material-face": Icons.IconMaterialFace,
  "material-fileDownload": Icons.IconMaterialFileDownload,
  "material-fileUpload": Icons.IconMaterialFileUpload,
  "material-forum": Icons.IconMaterialForum,
  "material-handyman": Icons.IconMaterialHandyman,
  "material-help": Icons.IconMaterialHelp,
  "material-inbox": Icons.IconMaterialInbox,
  "material-memory": Icons.IconMaterialMemory,
  "material-personAdd": Icons.IconMaterialPersonAdd,
  "material-plumbing": Icons.IconMaterialPlumbing,
  "material-refresh": Icons.IconMaterialRefresh,
  "material-remove": Icons.IconMaterialRemove,
  "material-removeCircle": Icons.IconMaterialRemoveCircle,
  "material-save": Icons.IconMaterialSave,
  "material-search": Icons.IconMaterialSearch,
  "material-share": Icons.IconMaterialShare,
  "material-sort": Icons.IconMaterialSort,
  "material-splitscreenAdd": Icons.IconMaterialSplitscreenAdd,
  "material-splitscreenVerticalAdd": Icons.IconMaterialSplitscreenVerticalAdd,
  "material-sync": Icons.IconMaterialSync,
  "material-upload": Icons.IconMaterialUpload,
  "material-verified": Icons.IconMaterialVerified,
  "material-widgets": Icons.IconMaterialWidgets,
  "material-zoomIn": Icons.IconMaterialZoomIn,
  "material-zoomOut": Icons.IconMaterialZoomOut,
  "material-comment": Icons.IconMaterialComment,
  "material-email": Icons.IconMaterialEmail,
  "material-helpOutline": Icons.IconMaterialHelpOutline,
  "material-localLaundryService": Icons.IconMaterialLocalLaundryService,
  "material-phone": Icons.IconMaterialPhone,
  "material-audiotrack": Icons.IconMaterialAudiotrack,
  "material-blurOff": Icons.IconMaterialBlurOff,
  "material-colorLens": Icons.IconMaterialColorLens,
  "material-fastRewind": Icons.IconMaterialFastRewind,
  "material-filter": Icons.IconMaterialFilter,
  "material-fullscreen": Icons.IconMaterialFullscreen,
  "material-fullscreenExit": Icons.IconMaterialFullscreenExit,
  "material-gradient": Icons.IconMaterialGradient,
  "material-image": Icons.IconMaterialImage,
  "material-invertColorsOff": Icons.IconMaterialInvertColorsOff,
  "material-palette": Icons.IconMaterialPalette,
  "material-pause": Icons.IconMaterialPause,
  "material-photo": Icons.IconMaterialPhoto,
  "material-rateReview": Icons.IconMaterialRateReview,
  "material-reviews": Icons.IconMaterialReviews,
  "material-stop": Icons.IconMaterialStop,
  "material-tune": Icons.IconMaterialTune,
  "material-videocam": Icons.IconMaterialVideocam,
  "material-volumeOff": Icons.IconMaterialVolumeOff,
  "material-arrowBack": Icons.IconMaterialArrowBack,
  "material-arrowDownward": Icons.IconMaterialArrowDownward,
  "material-arrowForward": Icons.IconMaterialArrowForward,
  "material-arrowLeft": Icons.IconMaterialArrowLeft,
  "material-arrowRight": Icons.IconMaterialArrowRight,
  "material-arrowUpward": Icons.IconMaterialArrowUpward,
  "material-backspace": Icons.IconMaterialBackspace,
  "material-brightnessAuto": Icons.IconMaterialBrightnessAuto,
  "material-brightnessHigh": Icons.IconMaterialBrightnessHigh,
  "material-brightnessLow": Icons.IconMaterialBrightnessLow,
  "material-brightnessMedium": Icons.IconMaterialBrightnessMedium,
  "material-chevronDoubleDown": Icons.IconMaterialChevronDoubleDown,
  "material-chevronDoubleLeft": Icons.IconMaterialChevronDoubleLeft,
  "material-chevronDoubleRight": Icons.IconMaterialChevronDoubleRight,
  "material-chevronDoubleUp": Icons.IconMaterialChevronDoubleUp,
  "material-chevronLeft": Icons.IconMaterialChevronLeft,
  "material-chevronRight": Icons.IconMaterialChevronRight,
  "material-event": Icons.IconMaterialEvent,
  "material-fastForward": Icons.IconMaterialFastForward,
  "material-feedback": Icons.IconMaterialFeedback,
  "material-group": Icons.IconMaterialGroup,
  "material-home": Icons.IconMaterialHome,
  "material-homeWork": Icons.IconMaterialHomeWork,
  "material-keyboardArrowLeft": Icons.IconMaterialKeyboardArrowLeft,
  "material-keyboardArrowUp": Icons.IconMaterialKeyboardArrowUp,
  "material-link": Icons.IconMaterialLink,
  "material-menu": Icons.IconMaterialMenu,
  "material-more": Icons.IconMaterialMore,
  "material-moreVert": Icons.IconMaterialMoreVert,
  "material-playArrow": Icons.IconMaterialPlayArrow,
  "material-router": Icons.IconMaterialRouter,
  "material-skipNext": Icons.IconMaterialSkipNext,
  "material-skipPrevious": Icons.IconMaterialSkipPrevious,
  "material-support": Icons.IconMaterialSupport,
  "material-thumbP": Icons.IconMaterialThumbP,
  "material-volumeDown": Icons.IconMaterialVolumeDown,
  "material-volumeUp": Icons.IconMaterialVolumeUp,
  "material-batteryAlert": Icons.IconMaterialBatteryAlert,
  "material-blurOn": Icons.IconMaterialBlurOn,
  "material-blurCircular": Icons.IconMaterialBlurCircular,
  "material-deblur": Icons.IconMaterialDeblur,
  "material-style": Icons.IconMaterialStyle,
  "material-width": Icons.IconMaterialWidth,
  "material-height": Icons.IconMaterialHeight,
  "material-roundedCorner": Icons.IconMaterialRoundedCorner,
  "material-lineWeight": Icons.IconMaterialLineWeight,
  "material-alignCenter": Icons.IconMaterialAlignCenter,
  "material-alignEnd": Icons.IconMaterialAlignEnd,
  "material-alignFlexCenter": Icons.IconMaterialAlignFlexCenter,
  "material-alignFlexEnd": Icons.IconMaterialAlignFlexEnd,
  "material-alignFlexStart": Icons.IconMaterialAlignFlexStart,
  "material-alignHorizontalCenter": Icons.IconMaterialAlignHorizontalCenter,
  "material-alignItemsStretch": Icons.IconMaterialAlignItemsStretch,
  "material-alignJustifyCenter": Icons.IconMaterialAlignJustifyCenter,
  "material-alignJustifyFlexEnd": Icons.IconMaterialAlignJustifyFlexEnd,
  "material-alignJustifyFlexStart": Icons.IconMaterialAlignJustifyFlexStart,
  "material-alignJustifySpaceAround": Icons.IconMaterialAlignJustifySpaceAround,
  "material-alignJustifySpaceBetween":
    Icons.IconMaterialAlignJustifySpaceBetween,
  "material-alignJustifySpaceEven": Icons.IconMaterialAlignJustifySpaceEven,
  "material-alignJustifyStretch": Icons.IconMaterialAlignJustifyStretch,
  "material-alignSelfStretch": Icons.IconMaterialAlignSelfStretch,
  "material-alignSpaceAround": Icons.IconMaterialAlignSpaceAround,
  "material-alignSpaceBetween": Icons.IconMaterialAlignSpaceBetween,
  "material-alignSpaceEven": Icons.IconMaterialAlignSpaceEven,
  "material-alignStart": Icons.IconMaterialAlignStart,
  "material-alignStretch": Icons.IconMaterialAlignStretch,
  "material-alignVerticalBottom": Icons.IconMaterialAlignVerticalBottom,
  "material-alignVerticalCenter": Icons.IconMaterialAlignVerticalCenter,
  "material-alignVerticalTop": Icons.IconMaterialAlignVerticalTop,
  "material-alignHorizontalLeft": Icons.IconMaterialAlignHorizontalLeft,
  "material-alignHorizontalRight": Icons.IconMaterialAlignHorizontalRight,
  "material-desktopLandscape": Icons.IconMaterialDesktopLandscape,
  "material-desktopPortrait": Icons.IconMaterialDesktopPortrait,
  "material-formatTextdirectionLToR": Icons.IconMaterialFormatTextdirectionLToR,
  "material-formatTextdirectionRToL": Icons.IconMaterialFormatTextdirectionRToL,
  "material-formatTextdirectionVertical":
    Icons.IconMaterialFormatTextdirectionVertical,
  "material-bolt": Icons.IconMaterialBolt,
  "material-check": Icons.IconMaterialCheck,
  "material-checkCircle": Icons.IconMaterialCheckCircle,
  "material-checkCircleOutline": Icons.IconMaterialCheckCircleOutline,
  "material-close": Icons.IconMaterialClose,
  "material-construction": Icons.IconMaterialConstruction,
  "material-contrast": Icons.IconMaterialContrast,
  "material-colors": Icons.IconMaterialColors,
  "material-piano": Icons.IconMaterialPiano,
  "material-formatSize": Icons.IconMaterialFormatSize,
  "material-textFormat": Icons.IconMaterialTextFormat,
  "material-titlecase": Icons.IconMaterialTitlecase,
  "material-asterisk": Icons.IconMaterialAsterisk,
  "material-article": Icons.IconMaterialArticle,
  "material-attribution": Icons.IconMaterialAttribution,
  "material-doneAll": Icons.IconMaterialDoneAll,
  "material-dryCleaning": Icons.IconMaterialDryCleaning,
  "material-error": Icons.IconMaterialError,
  "material-expandLess": Icons.IconMaterialExpandLess,
  "material-expandMore": Icons.IconMaterialExpandMore,
  "material-info": Icons.IconMaterialInfo,
  "material-invertColors": Icons.IconMaterialInvertColors,
  "material-localFireDepartment": Icons.IconMaterialLocalFireDepartment,
  "material-localPolice": Icons.IconMaterialLocalPolice,
  "material-nearMeDisabled": Icons.IconMaterialNearMeDisabled,
  "material-networkCheck": Icons.IconMaterialNetworkCheck,
  "material-notifications": Icons.IconMaterialNotifications,
  "material-notificationsActive": Icons.IconMaterialNotificationsActive,
  "material-notificationsNone": Icons.IconMaterialNotificationsNone,
  "material-opacity": Icons.IconMaterialOpacity,
  "material-powerOff": Icons.IconMaterialPowerOff,
  "material-print": Icons.IconMaterialPrint,
  "material-robot": Icons.IconMaterialRobot,
  "material-signalWifiOff": Icons.IconMaterialSignalWifiOff,
  "material-unfoldLess": Icons.IconMaterialUnfoldLess,
  "material-visibility": Icons.IconMaterialVisibility,
  "material-visibilityOff": Icons.IconMaterialVisibilityOff,
  "material-codeOff": Icons.IconMaterialCodeOff,
  "material-codeXml": Icons.IconMaterialCodeXml,
  "material-textSelectStart": Icons.IconMaterialTextSelectStart,
  "material-deployedCode": Icons.IconMaterialDeployedCode,
  "material-dataObject": Icons.IconMaterialDataObject,
  "material-copyAll": Icons.IconMaterialCopyAll,
  "material-aspectRatio": Icons.IconMaterialAspectRatio,
  "material-mouse": Icons.IconMaterialMouse,
  "material-highlightMouseCursor": Icons.IconMaterialHighlightMouseCursor,
  "material-highlightTextCursor": Icons.IconMaterialHighlightTextCursor,
  "material-dragPan": Icons.IconMaterialDragPan,
  "material-resize": Icons.IconMaterialResize,
  "material-adsClick": Icons.IconMaterialAdsClick,
  "material-gridOn": Icons.IconMaterialGridOn,
  "material-driveFileMoveOutline": Icons.IconMaterialDriveFileMoveOutline,
  "material-openWith": Icons.IconMaterialOpenWith,
  "material-doNotDisturbOn": Icons.IconMaterialDoNotDisturbOn,
  "material-panTool": Icons.IconMaterialPanTool,
  "material-panToolAlt": Icons.IconMaterialPanToolAlt,
  "material-syncAlt": Icons.IconMaterialSyncAlt,
  "material-circle": Icons.IconMaterialCircle,
  "material-layers": Icons.IconMaterialLayers,
  "material-lineStartCircle": Icons.IconMaterialLineStartCircle,
  "material-lineEndCircle": Icons.IconMaterialLineEndCircle,
  "material-formatAlignLeft": Icons.IconMaterialFormatAlignLeft,
  "material-formatAlignRight": Icons.IconMaterialFormatAlignRight,
  "material-formatAlignCenter": Icons.IconMaterialFormatAlignCenter,
  "material-formatAlignJustify": Icons.IconMaterialFormatAlignJustify,
  "material-matchCase": Icons.IconMaterialMatchCase,
  "material-warning": Icons.IconMaterialWarning,
  "material-wifi": Icons.IconMaterialWifi,
  "material-wifiOff": Icons.IconMaterialWifiOff,
  "material-code": Icons.IconMaterialCode,
  "material-texture": Icons.IconMaterialTexture,
  "material-viewModule": Icons.IconMaterialViewModule,
  "material-compassCalibration": Icons.IconMaterialCompassCalibration,
  "material-navigation": Icons.IconMaterialNavigation,
  "material-nearMe": Icons.IconMaterialNearMe,
  "material-place": Icons.IconMaterialPlace,
  "material-room": Icons.IconMaterialRoom,
  "material-calendarToday": Icons.IconMaterialCalendarToday,
  "material-eventSeat": Icons.IconMaterialEventSeat,
  "material-schedule": Icons.IconMaterialSchedule,
  "material-sentimentDissatisfied": Icons.IconMaterialSentimentDissatisfied,
  "material-sentimentNeutral": Icons.IconMaterialSentimentNeutral,
  "material-sentimentSatisfied": Icons.IconMaterialSentimentSatisfied,
}
