// All icons from seldon icon set, organized by category
// user-interface/text
export { IconSeldonLines } from "./user-interface/text/IconSeldonLines"
export { IconSeldonText } from "./user-interface/text/IconSeldonText"
export { IconSeldonIconText } from "./user-interface/text/IconSeldonIconText"

// user-interface/navigation
export { IconSeldonMore } from "./user-interface/navigation/IconSeldonMore"

// system/devices
export { IconSeldonDeviceCustom } from "./system/devices/IconSeldonDeviceCustom"

// system/settings
export { IconSeldonAngle } from "./system/settings/IconSeldonAngle"
export { IconSeldonBackground } from "./system/settings/IconSeldonBackground"
export { IconSeldonCodeCube } from "./system/settings/IconSeldonCodeCube"
export { IconSeldonColor } from "./system/settings/IconSeldonColor"
export { IconSeldonComputed } from "./system/settings/IconSeldonComputed"
export { IconSeldonCustom } from "./system/settings/IconSeldonCustom"
export { IconSeldonDisplay } from "./system/settings/IconSeldonDisplay"
export { IconSeldonEmpty } from "./system/settings/IconSeldonEmpty"
export { IconSeldonFrameBackground } from "./system/settings/IconSeldonFrameBackground"
export { IconSeldonFrameColumns } from "./system/settings/IconSeldonFrameColumns"
export { IconSeldonFrameRows } from "./system/settings/IconSeldonFrameRows"
export { IconSeldonGap } from "./system/settings/IconSeldonGap"
export { IconSeldonHexagon } from "./system/settings/IconSeldonHexagon"
export { IconSeldonHidden } from "./system/settings/IconSeldonHidden"
export { IconSeldonNone } from "./system/settings/IconSeldonNone"
export { IconSeldonPositionBottom } from "./system/settings/IconSeldonPositionBottom"
export { IconSeldonPositionBottomLeft } from "./system/settings/IconSeldonPositionBottomLeft"
export { IconSeldonPositionBottomRight } from "./system/settings/IconSeldonPositionBottomRight"
export { IconSeldonPositionCenter } from "./system/settings/IconSeldonPositionCenter"
export { IconSeldonPositionLeft } from "./system/settings/IconSeldonPositionLeft"
export { IconSeldonPositionRight } from "./system/settings/IconSeldonPositionRight"
export { IconSeldonPositionTop } from "./system/settings/IconSeldonPositionTop"
export { IconSeldonPositionTopLeft } from "./system/settings/IconSeldonPositionTopLeft"
export { IconSeldonPositionTopRight } from "./system/settings/IconSeldonPositionTopRight"
export { IconSeldonScreen } from "./system/settings/IconSeldonScreen"
export { IconSeldonShadow } from "./system/settings/IconSeldonShadow"
export { IconSeldonSpread } from "./system/settings/IconSeldonSpread"
export { IconSeldonStep } from "./system/settings/IconSeldonStep"
export { IconSeldonStub } from "./system/settings/IconSeldonStub"
export { IconSeldonTheme } from "./system/settings/IconSeldonTheme"
export { IconSeldonSwatch } from "./system/settings/IconSeldonSwatch"
export { IconSeldonValuePx } from "./system/settings/IconSeldonValuePx"
export { IconSeldonValueRem } from "./system/settings/IconSeldonValueRem"
export { IconSeldonOrientationHorizontal } from "./system/settings/IconSeldonOrientationHorizontal"
export { IconSeldonOrientationVertical } from "./system/settings/IconSeldonOrientationVertical"
export { IconSeldonBackgroundColor } from "./system/settings/IconSeldonBackgroundColor"
export { IconSeldonAlign } from "./system/settings/IconSeldonAlign"

// user-interface/actions (includes former misc icons)
export { IconSeldonClip } from "./user-interface/actions/IconSeldonClip"
export { IconSeldonIconInput } from "./user-interface/actions/IconSeldonIconInput"
export { IconSeldonInputType } from "./user-interface/actions/IconSeldonInputType"
export { IconSeldonMinus } from "./user-interface/actions/IconSeldonMinus"
export { IconSeldonPlus } from "./user-interface/actions/IconSeldonPlus"
export { IconSeldonRetry } from "./user-interface/actions/IconSeldonRetry"
export { IconSeldonCursor } from "./user-interface/actions/IconSeldonCursor"
export { IconSeldonDefault } from "./user-interface/actions/IconSeldonDefault"
export { IconSeldonEdited } from "./user-interface/actions/IconSeldonEdited"
export { IconSeldonFrame } from "./user-interface/actions/IconSeldonFrame"
export { IconSeldonMissing } from "./user-interface/actions/IconSeldonMissing"
export { IconSeldonReset } from "./user-interface/actions/IconSeldonReset"
export { IconSeldonSize } from "./user-interface/actions/IconSeldonSize"
export { IconSeldonSketchCircle } from "./user-interface/actions/IconSeldonSketchCircle"
export { IconSeldonSketchPencil } from "./user-interface/actions/IconSeldonSketchPencil"
export { IconSeldonSketchRectangle } from "./user-interface/actions/IconSeldonSketchRectangle"
export { IconSeldonSketchText } from "./user-interface/actions/IconSeldonSketchText"
export { IconSeldonToolArrow } from "./user-interface/actions/IconSeldonToolArrow"
export { IconSeldonToolImageAi } from "./user-interface/actions/IconSeldonToolImageAi"
export { IconSeldonToolComponent } from "./user-interface/actions/IconSeldonToolComponent"
export { IconSeldonToolSketch } from "./user-interface/actions/IconSeldonToolSketch"

// user-interface/status
export { IconSeldonHeartPlus } from "./user-interface/status/IconSeldonHeartPlus"

// user-interface/media
export { IconSeldonComponent } from "./user-interface/media/IconSeldonComponent"
export { IconSeldonComponentDefault } from "./user-interface/media/IconSeldonComponentDefault"
export { IconSeldonComponentVariant } from "./user-interface/media/IconSeldonComponentVariant"
export { IconSeldonIcon } from "./user-interface/media/IconSeldonIcon"
export { IconSeldonImage } from "./user-interface/media/IconSeldonImage"
export { IconSeldonInput } from "./user-interface/media/IconSeldonInput"
export { IconSeldonContent } from "./user-interface/media/IconSeldonContent"
export { IconSeldonIconFrame } from "./user-interface/media/IconSeldonIconFrame"
export { IconSeldonIconImage } from "./user-interface/media/IconSeldonIconImage"
export { IconSeldonVector } from "./user-interface/media/IconSeldonVector"
export { IconSeldonParts } from "./user-interface/media/IconSeldonParts"
export { IconSeldonPrimitives } from "./user-interface/media/IconSeldonPrimitives"
export { IconSeldonModules } from "./user-interface/media/IconSeldonModules"
export { IconSeldonElements } from "./user-interface/media/IconSeldonElements"
export { IconSeldonPanels } from "./user-interface/media/IconSeldonPanels"
export { IconSeldonCatalog } from "./user-interface/media/IconSeldonCatalog"

// social-media/social
export { IconSocialFacebook } from "./social-media/social/IconSocialFacebook"
export { IconSocialReddit } from "./social-media/social/IconSocialReddit"
export { IconSocialPinterest } from "./social-media/social/IconSocialPinterest"
export { IconSocialTiktok } from "./social-media/social/IconSocialTiktok"
export { IconSocialWhatsapp } from "./social-media/social/IconSocialWhatsapp"
export { IconSocialLinkedin } from "./social-media/social/IconSocialLinkedin"
export { IconSocialSpotify } from "./social-media/social/IconSocialSpotify"
export { IconSocialTwitch } from "./social-media/social/IconSocialTwitch"
export { IconSocialYoutube } from "./social-media/social/IconSocialYoutube"
export { IconSocialDiscord } from "./social-media/social/IconSocialDiscord"
export { IconSocialTwitter } from "./social-media/social/IconSocialTwitter"
export { IconSocialMedium } from "./social-media/social/IconSocialMedium"
export { IconSocialTelegram } from "./social-media/social/IconSocialTelegram"
export { IconSocialInstagram } from "./social-media/social/IconSocialInstagram"
export { IconSocialGithub } from "./social-media/social/IconSocialGithub"
