/**
 * Dynamic theme token catalog entries for token tables that depend on the loaded theme
 * (swatches, shadow recipes, font presets, …). Entries may use `propertyKey` → `PROPERTY_SCHEMAS`;
 * see `helpers/resolve-theme-token-schema.ts`. Static entries live in `theme-static-schemas.ts`.
 */
import { getDynamicSwatchName } from "../../compute/get-dynamic-swatch-names"
import { LOOK_FACETS, isBridgedLookFacet } from "../../looks/look-facets"
import type { LookSection } from "../../looks/look-facets"
import type { ComputedTheme, StockTheme } from "../../types/theme"
import type {
  ThemeTokenSchemaUnresolved,
} from "../../types/schema"
import type { StockThemeSwatch, ThemeSwatch } from "../../values"
import { isDynamicSwatchToken } from "../../values"
import { finalizeThemeTokenSchema } from "../helpers/finalize-theme-token-schema"

export type ThemeOrStock = StockTheme | ComputedTheme

function swatchSchemaLabel(
  swatch: StockThemeSwatch | ThemeSwatch,
  theme: ThemeOrStock,
): string {
  if (isDynamicSwatchToken(swatch)) {
    return getDynamicSwatchName(swatch.role, theme)
  }
  return (swatch as ThemeSwatch).name ?? ""
}

/**
 * Generate schemas for swatch properties.
 *
 * Slots are emitted in three groups, in order:
 *   1. Dynamic palette slots (`white`, `gray`, …, `swatch4`) — labels generated by
 *      {@link getDynamicSwatchName} from the theme's harmony.
 *   2. Reserved fixed slots (`background`).
 *   3. Free-named user swatches — any other key in the swatch table. The cell's
 *      `name` is the source of truth; an empty string falls back here.
 */
export function generateSwatchSchemas(
  theme: ThemeOrStock,
): ThemeTokenSchemaUnresolved[] {
  const schemas: ThemeTokenSchemaUnresolved[] = []
  let order = 0
  const swatchTable = theme.swatch as Record<
    string,
    StockThemeSwatch | ThemeSwatch
  >

  const dynamicSlots = [
    "white",
    "gray",
    "black",
    "primary",
    "swatch1",
    "swatch2",
    "swatch3",
    "swatch4",
  ]
  const RESERVED_SLOTS = ["background"]

  for (const swatchId of dynamicSlots) {
    const swatch = swatchTable[swatchId]
    if (swatch) {
      schemas.push({
        key: `swatch.${swatchId}`,
        propertyKey: "color",
        label: swatchSchemaLabel(swatch, theme),
        section: "swatch",
        order: order++,
      })
    }
  }

  for (const swatchId of RESERVED_SLOTS) {
    const swatch = swatchTable[swatchId]
    if (swatch) {
      schemas.push({
        key: `swatch.${swatchId}`,
        propertyKey: "color",
        label: swatchSchemaLabel(swatch, theme),
        section: "swatch",
        order: order++,
      })
    }
  }

  for (const [key, swatch] of Object.entries(swatchTable)) {
    if (dynamicSlots.includes(key)) continue
    if (RESERVED_SLOTS.includes(key)) continue
    schemas.push({
      key: `swatch.${key}`,
      propertyKey: "color",
      label: swatchSchemaLabel(
        swatch as StockThemeSwatch | ThemeSwatch,
        theme,
      ),
      section: "swatch",
      order: order++,
    })
  }

  return schemas
}

/**
 * Generate schemas for one look section.
 *
 * Each look emits a parent row (the disclosure group) followed by one row per
 * facet from {@link LOOK_FACETS}. Bridged facets carry a `propertyKey` so their
 * control and options resolve from the property schema. Inline facets carry
 * explicit `valueType` / `controlType` and are finalized here.
 */
export function generateLookSchemas(
  theme: ThemeOrStock,
  section: LookSection,
): ThemeTokenSchemaUnresolved[] {
  const schemas: ThemeTokenSchemaUnresolved[] = []
  const facets = LOOK_FACETS[section]
  const stride = facets.length + 1
  const lookTable = (theme as unknown as Record<string, Record<string, { name?: string }>>)[
    section
  ]
  if (!lookTable) return schemas

  let index = 0
  for (const [lookId, look] of Object.entries(lookTable)) {
    if (!look) continue
    const baseOrder = index * stride

    schemas.push({
      key: `${section}.${lookId}`,
      label: look.name ?? lookId,
      section,
      order: baseOrder,
      supports: [],
      validation: {},
      isLookParent: true,
    })

    facets.forEach((facet, facetIndex) => {
      const base = {
        key: `${section}.${lookId}.${facet.facet}`,
        label: facet.label,
        section,
        order: baseOrder + facetIndex + 1,
        isSubProperty: true,
      }
      if (isBridgedLookFacet(facet)) {
        schemas.push({ ...base, propertyKey: facet.propertyKey })
      } else {
        schemas.push(
          finalizeThemeTokenSchema({
            ...base,
            valueType: facet.valueType,
            controlType: facet.controlType,
          }),
        )
      }
    })

    index++
  }

  return schemas
}
