/**
 * Dynamic theme token catalog entries for token tables that depend on the loaded theme
 * (swatches, shadow recipes, font presets, …). Entries may use `propertyKey` → `PROPERTY_SCHEMAS`;
 * see `helpers/resolve-theme-token-schema.ts`. Static entries live in `theme-static-schemas.ts`.
 */
import { getDynamicSwatchName } from "../../compute/get-dynamic-swatch-names"
import type { ComputedTheme, StockTheme } from "../../types/theme"
import type {
  ThemeTokenCatalogDraft,
  ThemeTokenSchema,
  ThemeTokenSchemaUnresolved,
} from "../../types/schema"
import type { StockThemeSwatch, ThemeSwatch } from "../../values"
import { isDynamicSwatchToken } from "../../values"
import { finalizeThemeTokenSchema } from "../helpers/finalize-theme-token-schema"

export type ThemeOrStock = StockTheme | ComputedTheme

function swatchSchemaLabel(
  swatch: StockThemeSwatch | ThemeSwatch,
  theme: ThemeOrStock,
): string {
  if (isDynamicSwatchToken(swatch)) {
    return getDynamicSwatchName(swatch.role, theme)
  }
  return (swatch as ThemeSwatch).name ?? ""
}

/**
 * Generate schemas for swatch properties.
 *
 * Slots are emitted in three groups, in order:
 *   1. Dynamic palette slots (`white`, `gray`, …, `swatch4`) — labels generated by
 *      {@link getDynamicSwatchName} from the theme's harmony.
 *   2. Reserved fixed slots (`background`).
 *   3. Free-named user swatches — any other key in the swatch table. The cell's
 *      `name` is the source of truth; an empty string falls back here.
 */
export function generateSwatchSchemas(
  theme: ThemeOrStock,
): ThemeTokenSchemaUnresolved[] {
  const schemas: ThemeTokenSchemaUnresolved[] = []
  let order = 0
  const swatchTable = theme.swatch as Record<
    string,
    StockThemeSwatch | ThemeSwatch
  >

  const dynamicSlots = [
    "white",
    "gray",
    "black",
    "primary",
    "swatch1",
    "swatch2",
    "swatch3",
    "swatch4",
  ]
  const RESERVED_SLOTS = ["background"]

  for (const swatchId of dynamicSlots) {
    const swatch = swatchTable[swatchId]
    if (swatch) {
      schemas.push({
        key: `swatch.${swatchId}`,
        propertyKey: "color",
        label: swatchSchemaLabel(swatch, theme),
        section: "swatch",
        order: order++,
      })
    }
  }

  for (const swatchId of RESERVED_SLOTS) {
    const swatch = swatchTable[swatchId]
    if (swatch) {
      schemas.push({
        key: `swatch.${swatchId}`,
        propertyKey: "color",
        label: swatchSchemaLabel(swatch, theme),
        section: "swatch",
        order: order++,
      })
    }
  }

  for (const [key, swatch] of Object.entries(swatchTable)) {
    if (dynamicSlots.includes(key)) continue
    if (RESERVED_SLOTS.includes(key)) continue
    schemas.push({
      key: `swatch.${key}`,
      propertyKey: "color",
      label: swatchSchemaLabel(
        swatch as StockThemeSwatch | ThemeSwatch,
        theme,
      ),
      section: "swatch",
      order: order++,
    })
  }

  return schemas
}

/**
 * Generate schemas for shadow properties
 */
export function generateShadowSchemas(
  theme: ThemeOrStock,
): ThemeTokenSchemaUnresolved[] {
  const schemas: ThemeTokenSchemaUnresolved[] = []
  let order = 0

  Object.entries(theme.shadow).forEach(([shadowId, shadow]) => {
    if (!shadow) return
    const baseOrder = order * 6

    schemas.push(
      {
        key: `shadow.${shadowId}`,
        label: shadow.name,
        section: "shadow",
        order: baseOrder,
        supports: [],
        validation: {},
        isLookParent: true,
      },
      {
        key: `shadow.${shadowId}.offsetX`,
        propertyKey: "shadowOffsetX",
        label: "Offset X",
        section: "shadow",
        order: baseOrder + 1,
        isSubProperty: true,
      },
      {
        key: `shadow.${shadowId}.offsetY`,
        propertyKey: "shadowOffsetY",
        label: "Offset Y",
        section: "shadow",
        order: baseOrder + 2,
        isSubProperty: true,
      },
      {
        key: `shadow.${shadowId}.blur`,
        propertyKey: "shadowBlur",
        label: "Blur",
        section: "shadow",
        order: baseOrder + 3,
        isSubProperty: true,
      },
      {
        key: `shadow.${shadowId}.spread`,
        propertyKey: "shadowSpread",
        label: "Spread",
        section: "shadow",
        order: baseOrder + 4,
        isSubProperty: true,
      },
      {
        key: `shadow.${shadowId}.color`,
        propertyKey: "shadowColor",
        label: "Color",
        section: "shadow",
        order: baseOrder + 5,
        isSubProperty: true,
      },
    )

    order++
  })

  return schemas
}

/**
 * Generate schemas for border properties
 */
export function generateBorderSchemas(
  theme: ThemeOrStock,
): ThemeTokenSchemaUnresolved[] {
  const schemas: ThemeTokenSchemaUnresolved[] = []
  let order = 0

  Object.entries(theme.border).forEach(([borderId, border]) => {
    if (!border) return
    const baseOrder = order * 4

    schemas.push(
      {
        key: `border.${borderId}`,
        label: border.name,
        section: "border",
        order: baseOrder,
        supports: [],
        validation: {},
        isLookParent: true,
      },
      {
        key: `border.${borderId}.width`,
        propertyKey: "borderWidth",
        label: "Width",
        section: "border",
        order: baseOrder + 1,
        isSubProperty: true,
      },
      {
        key: `border.${borderId}.style`,
        propertyKey: "borderStyle",
        label: "Style",
        section: "border",
        order: baseOrder + 2,
        isSubProperty: true,
      },
      {
        key: `border.${borderId}.color`,
        propertyKey: "borderColor",
        label: "Color",
        section: "border",
        order: baseOrder + 3,
        isSubProperty: true,
      },
    )

    order++
  })

  return schemas
}

/**
 * Generate schemas for gradient properties
 */
export function generateGradientSchemas(
  theme: ThemeOrStock,
): ThemeTokenSchemaUnresolved[] {
  const schemas: ThemeTokenSchemaUnresolved[] = []
  let order = 0

  Object.entries(theme.gradient).forEach(([gradientId, gradient]) => {
    if (!gradient) return
    const baseOrder = order * 4

    schemas.push(
      {
        key: `gradient.${gradientId}`,
        label: gradient.name,
        section: "gradient",
        order: baseOrder,
        supports: [],
        validation: {},
        isLookParent: true,
      },
      {
        key: `gradient.${gradientId}.angle`,
        propertyKey: "gradientAngle",
        label: "Angle",
        section: "gradient",
        order: baseOrder + 1,
        isSubProperty: true,
      },
      {
        key: `gradient.${gradientId}.startColor`,
        propertyKey: "gradientStartColor",
        label: "Start Color",
        section: "gradient",
        order: baseOrder + 2,
        isSubProperty: true,
      },
      {
        key: `gradient.${gradientId}.endColor`,
        propertyKey: "gradientEndColor",
        label: "End Color",
        section: "gradient",
        order: baseOrder + 3,
        isSubProperty: true,
      },
    )

    order++
  })

  return schemas
}

/**
 * Generate schemas for background properties
 */
export function generateBackgroundSchemas(
  theme: ThemeOrStock,
): ThemeTokenSchemaUnresolved[] {
  const schemas: ThemeTokenSchemaUnresolved[] = []
  let order = 0

  Object.entries(theme.background).forEach(([backgroundId, background]) => {
    if (!background) return
    const baseOrder = order * 2

    schemas.push(
      {
        key: `background.${backgroundId}`,
        label: background.name,
        section: "background",
        order: baseOrder,
        supports: [],
        validation: {},
        isLookParent: true,
      },
      {
        key: `background.${backgroundId}.color`,
        propertyKey: "backgroundColor",
        label: "Color",
        section: "background",
        order: baseOrder + 1,
        isSubProperty: true,
      },
    )

    order++
  })

  return schemas
}

/**
 * Generate schemas for font properties (font presets)
 */
export function generateFontSchemas(
  theme: ThemeOrStock,
): ThemeTokenSchemaUnresolved[] {
  const schemas: ThemeTokenSchemaUnresolved[] = []
  let order = 0

  Object.entries(theme.font).forEach(([fontId, font]) => {
    if (!font) return
    const baseOrder = order * 5

    schemas.push(
      {
        key: `font.${fontId}`,
        label: font.name,
        section: "font",
        order: baseOrder,
        supports: [],
        validation: {},
        isLookParent: true,
      },
      {
        key: `font.${fontId}.family`,
        propertyKey: "fontFamily",
        label: "Family",
        section: "font",
        order: baseOrder + 1,
        isSubProperty: true,
      },
      {
        key: `font.${fontId}.size`,
        propertyKey: "fontSize",
        label: "Size",
        section: "font",
        order: baseOrder + 2,
        isSubProperty: true,
      },
      {
        key: `font.${fontId}.weight`,
        propertyKey: "fontWeight",
        label: "Weight",
        section: "font",
        order: baseOrder + 3,
        isSubProperty: true,
      },
      {
        key: `font.${fontId}.lineHeight`,
        propertyKey: "fontLineHeight",
        label: "Line Height",
        section: "font",
        order: baseOrder + 4,
        isSubProperty: true,
      },
    )

    order++
  })

  return schemas
}

/**
 * Generate schemas for scrollbar properties
 */
export function generateScrollbarSchemas(
  theme: ThemeOrStock,
): ThemeTokenSchema[] {
  const schemas: ThemeTokenSchema[] = []
  let order = 0

  Object.entries(theme.scrollbar).forEach(([scrollbarId, scrollbar]) => {
    if (!scrollbar) return
    const baseOrder = order * 6

    const facets: ThemeTokenCatalogDraft[] = [
      {
        key: `scrollbar.${scrollbarId}.trackSize`,
        label: "Track Size",
        valueType: "text",
        controlType: "text",
        section: "scrollbar",
        order: baseOrder + 1,
        isSubProperty: true,
      },
      {
        key: `scrollbar.${scrollbarId}.trackColor`,
        label: "Track Color",
        valueType: "color",
        controlType: "color",
        section: "scrollbar",
        order: baseOrder + 2,
        isSubProperty: true,
      },
      {
        key: `scrollbar.${scrollbarId}.thumbColor`,
        label: "Thumb Color",
        valueType: "color",
        controlType: "color",
        section: "scrollbar",
        order: baseOrder + 3,
        isSubProperty: true,
      },
      {
        key: `scrollbar.${scrollbarId}.thumbHoverColor`,
        label: "Thumb Hover Color",
        valueType: "color",
        controlType: "color",
        section: "scrollbar",
        order: baseOrder + 4,
        isSubProperty: true,
      },
      {
        key: `scrollbar.${scrollbarId}.rounded`,
        label: "Rounded",
        valueType: "boolean",
        controlType: "boolean",
        section: "scrollbar",
        order: baseOrder + 5,
        isSubProperty: true,
      },
    ]

    schemas.push(
      {
        key: `scrollbar.${scrollbarId}`,
        label: scrollbar.name,
        section: "scrollbar",
        order: baseOrder,
        supports: [],
        validation: {},
        isLookParent: true,
      },
      ...facets.map(finalizeThemeTokenSchema),
    )

    order++
  })

  return schemas
}
