/**
 * This file is auto generated by running bun scripts/generate-catalog.ts
 * DO NOT EDIT THIS FILE MANUALLY
 */
import { ComponentId } from "@seldon/core/components/constants"
import {
  exportConfig as avatarExportConfig,
  schema as avatarSchema,
} from "./elements/avatars/Avatar.schema"
import {
  exportConfig as avatarIconExportConfig,
  schema as avatarIconSchema,
} from "./elements/avatars/AvatarIcon.schema"
import {
  exportConfig as avatarProductExportConfig,
  schema as avatarProductSchema,
} from "./elements/avatars/AvatarProduct.schema"
import {
  exportConfig as buttonExportConfig,
  schema as buttonSchema,
} from "./elements/buttons/Button.schema"
import {
  exportConfig as buttonSegmentedExportConfig,
  schema as buttonSegmentedSchema,
} from "./elements/buttons/ButtonSegmented.schema"
import {
  exportConfig as buttonSocialExportConfig,
  schema as buttonSocialSchema,
} from "./elements/buttons/ButtonSocial.schema"
import {
  exportConfig as buttonToolsExportConfig,
  schema as buttonToolsSchema,
} from "./elements/buttons/ButtonTools.schema"
import {
  exportConfig as calendarWeekExportConfig,
  schema as calendarWeekSchema,
} from "./elements/calendars/CalendarWeek.schema"
import {
  exportConfig as calendarWeekdaysExportConfig,
  schema as calendarWeekdaysSchema,
} from "./elements/calendars/CalendarWeekdays.schema"
import {
  exportConfig as chipExportConfig,
  schema as chipSchema,
} from "./elements/chips/Chip.schema"
import {
  exportConfig as chipCountExportConfig,
  schema as chipCountSchema,
} from "./elements/chips/ChipCount.schema"
import {
  exportConfig as inputCheckboxExportConfig,
  schema as inputCheckboxSchema,
} from "./elements/forms/InputCheckbox.schema"
import {
  exportConfig as inputDropdownExportConfig,
  schema as inputDropdownSchema,
} from "./elements/forms/InputDropdown.schema"
import {
  exportConfig as inputIconicExportConfig,
  schema as inputIconicSchema,
} from "./elements/forms/InputIconic.schema"
import {
  exportConfig as inputRadioExportConfig,
  schema as inputRadioSchema,
} from "./elements/forms/InputRadio.schema"
import {
  exportConfig as inputSearchExportConfig,
  schema as inputSearchSchema,
} from "./elements/forms/InputSearch.schema"
import {
  exportConfig as inputTextExportConfig,
  schema as inputTextSchema,
} from "./elements/forms/InputText.schema"
import {
  exportConfig as optionGroupExportConfig,
  schema as optionGroupSchema,
} from "./elements/forms/OptionGroup.schema"
import {
  exportConfig as headerActionExportConfig,
  schema as headerActionSchema,
} from "./elements/headers/HeaderAction.schema"
import {
  exportConfig as headerCardExportConfig,
  schema as headerCardSchema,
} from "./elements/headers/HeaderCard.schema"
import {
  exportConfig as listItemAvatarExportConfig,
  schema as listItemAvatarSchema,
} from "./elements/list-items/ListItemAvatar.schema"
import {
  exportConfig as listItemGeneralExportConfig,
  schema as listItemGeneralSchema,
} from "./elements/list-items/ListItemGeneral.schema"
import {
  exportConfig as listItemInputExportConfig,
  schema as listItemInputSchema,
} from "./elements/list-items/ListItemInput.schema"
import {
  exportConfig as listItemProductExportConfig,
  schema as listItemProductSchema,
} from "./elements/list-items/ListItemProduct.schema"
import {
  exportConfig as listItemStandardExportConfig,
  schema as listItemStandardSchema,
} from "./elements/list-items/ListItemStandard.schema"
import {
  exportConfig as listItemTodoExportConfig,
  schema as listItemTodoSchema,
} from "./elements/list-items/ListItemTodo.schema"
import {
  exportConfig as listItemTreeExportConfig,
  schema as listItemTreeSchema,
} from "./elements/list-items/ListItemTree.schema"
import {
  exportConfig as sectionBrandExportConfig,
  schema as sectionBrandSchema,
} from "./elements/sections/SectionBrand.schema"
import {
  exportConfig as sectionLegalExportConfig,
  schema as sectionLegalSchema,
} from "./elements/sections/SectionLegal.schema"
import {
  exportConfig as sectionNavExportConfig,
  schema as sectionNavSchema,
} from "./elements/sections/SectionNav.schema"
import {
  exportConfig as sectionNewsletterExportConfig,
  schema as sectionNewsletterSchema,
} from "./elements/sections/SectionNewsletter.schema"
import {
  exportConfig as sectionSocialExportConfig,
  schema as sectionSocialSchema,
} from "./elements/sections/SectionSocial.schema"
// Elements
import {
  exportConfig as tableRowDataExportConfig,
  schema as tableRowDataSchema,
} from "./elements/tables/TableRowData.schema"
import {
  exportConfig as tableRowHeaderExportConfig,
  schema as tableRowHeaderSchema,
} from "./elements/tables/TableRowHeader.schema"
import {
  exportConfig as textblockExportConfig,
  schema as textblockSchema,
} from "./elements/textblocks/Textblock.schema"
import {
  exportConfig as textblockAvatarExportConfig,
  schema as textblockAvatarSchema,
} from "./elements/textblocks/TextblockAvatar.schema"
import {
  exportConfig as textblockDetailsExportConfig,
  schema as textblockDetailsSchema,
} from "./elements/textblocks/TextblockDetails.schema"
import {
  exportConfig as textblockHeaderExportConfig,
  schema as textblockHeaderSchema,
} from "./elements/textblocks/TextblockHeader.schema"
import {
  exportConfig as textblockTitleExportConfig,
  schema as textblockTitleSchema,
} from "./elements/textblocks/TextblockTitle.schema"
import {
  exportConfig as boardExportConfig,
  schema as boardSchema,
} from "./frames/Board.schema"
// Frames
import {
  exportConfig as frameExportConfig,
  schema as frameSchema,
} from "./frames/Frame.schema"
import {
  exportConfig as calendarExportConfig,
  schema as calendarSchema,
} from "./modules/calendars/Calendar.schema"
import {
  exportConfig as footerExportConfig,
  schema as footerSchema,
} from "./modules/footers/Footer.schema"
import {
  exportConfig as panelDialogExportConfig,
  schema as panelDialogSchema,
} from "./modules/panels/PanelDialog.schema"
import {
  exportConfig as panelSidebarExportConfig,
  schema as panelSidebarSchema,
} from "./modules/panels/PanelSidebar.schema"
// Modules
import {
  exportConfig as tableExportConfig,
  schema as tableSchema,
} from "./modules/tables/Table.schema"
import {
  exportConfig as widgetTodoExportConfig,
  schema as widgetTodoSchema,
} from "./modules/widgets/WidgetTodo.schema"
import {
  exportConfig as adIabExportConfig,
  schema as adIabSchema,
} from "./parts/advertisements/AdIab.schema"
import {
  exportConfig as adInstagramExportConfig,
  schema as adInstagramSchema,
} from "./parts/advertisements/AdInstagram.schema"
import {
  exportConfig as adLinkedInExportConfig,
  schema as adLinkedInSchema,
} from "./parts/advertisements/AdLinkedIn.schema"
import {
  exportConfig as adSocialMediaExportConfig,
  schema as adSocialMediaSchema,
} from "./parts/advertisements/AdSocialMedia.schema"
import {
  exportConfig as adTikTokExportConfig,
  schema as adTikTokSchema,
} from "./parts/advertisements/AdTikTok.schema"
import {
  exportConfig as adYouTubeExportConfig,
  schema as adYouTubeSchema,
} from "./parts/advertisements/AdYouTube.schema"
import {
  exportConfig as barButtonsExportConfig,
  schema as barButtonsSchema,
} from "./parts/bars/BarButtons.schema"
import {
  exportConfig as barFooterExportConfig,
  schema as barFooterSchema,
} from "./parts/bars/BarFooter.schema"
import {
  exportConfig as barHeaderExportConfig,
  schema as barHeaderSchema,
} from "./parts/bars/BarHeader.schema"
import {
  exportConfig as barNavigationExportConfig,
  schema as barNavigationSchema,
} from "./parts/bars/BarNavigation.schema"
import {
  exportConfig as barStatusExportConfig,
  schema as barStatusSchema,
} from "./parts/bars/BarStatus.schema"
import {
  exportConfig as barTabsExportConfig,
  schema as barTabsSchema,
} from "./parts/bars/BarTabs.schema"
import {
  exportConfig as barTopExportConfig,
  schema as barTopSchema,
} from "./parts/bars/BarTop.schema"
import {
  exportConfig as calendarHeaderExportConfig,
  schema as calendarHeaderSchema,
} from "./parts/calendars/CalendarHeader.schema"
import {
  exportConfig as calendarMonthExportConfig,
  schema as calendarMonthSchema,
} from "./parts/calendars/CalendarMonth.schema"
import {
  exportConfig as cardHorizontalExportConfig,
  schema as cardHorizontalSchema,
} from "./parts/cards/CardHorizontal.schema"
import {
  exportConfig as cardProductExportConfig,
  schema as cardProductSchema,
} from "./parts/cards/CardProduct.schema"
import {
  exportConfig as cardStackedExportConfig,
  schema as cardStackedSchema,
} from "./parts/cards/CardStacked.schema"
import {
  exportConfig as fieldsetExportConfig,
  schema as fieldsetSchema,
} from "./parts/forms/Fieldset.schema"
import {
  exportConfig as fieldsetCheckboxesExportConfig,
  schema as fieldsetCheckboxesSchema,
} from "./parts/forms/FieldsetCheckboxes.schema"
import {
  exportConfig as fieldsetRadiosExportConfig,
  schema as fieldsetRadiosSchema,
} from "./parts/forms/FieldsetRadios.schema"
import {
  exportConfig as listContactsExportConfig,
  schema as listContactsSchema,
} from "./parts/lists/ListContacts.schema"
import {
  exportConfig as listGridExportConfig,
  schema as listGridSchema,
} from "./parts/lists/ListGrid.schema"
import {
  exportConfig as listProductsExportConfig,
  schema as listProductsSchema,
} from "./parts/lists/ListProducts.schema"
import {
  exportConfig as listStandardExportConfig,
  schema as listStandardSchema,
} from "./parts/lists/ListStandard.schema"
import {
  exportConfig as listTodoExportConfig,
  schema as listTodoSchema,
} from "./parts/lists/ListTodo.schema"
import {
  exportConfig as tableBodyExportConfig,
  schema as tableBodySchema,
} from "./parts/tables/TableBody.schema"
// Parts
import {
  exportConfig as tableFootExportConfig,
  schema as tableFootSchema,
} from "./parts/tables/TableFoot.schema"
import {
  exportConfig as tableHeadExportConfig,
  schema as tableHeadSchema,
} from "./parts/tables/TableHead.schema"
import {
  exportConfig as hrExportConfig,
  schema as hrSchema,
} from "./primitives/Hr.schema"
import {
  exportConfig as iconExportConfig,
  schema as iconSchema,
} from "./primitives/Icon.schema"
import {
  exportConfig as imageExportConfig,
  schema as imageSchema,
} from "./primitives/Image.schema"
import {
  exportConfig as navExportConfig,
  schema as navSchema,
} from "./primitives/Nav.schema"
import {
  exportConfig as checkboxExportConfig,
  schema as checkboxSchema,
} from "./primitives/controls/Checkbox.schema"
import {
  exportConfig as inputExportConfig,
  schema as inputSchema,
} from "./primitives/controls/Input.schema"
import {
  exportConfig as labelExportConfig,
  schema as labelSchema,
} from "./primitives/controls/Label.schema"
import {
  exportConfig as legendExportConfig,
  schema as legendSchema,
} from "./primitives/controls/Legend.schema"
import {
  exportConfig as optionExportConfig,
  schema as optionSchema,
} from "./primitives/controls/Option.schema"
import {
  exportConfig as radioExportConfig,
  schema as radioSchema,
} from "./primitives/controls/Radio.schema"
import {
  exportConfig as selectExportConfig,
  schema as selectSchema,
} from "./primitives/controls/Select.schema"
import {
  exportConfig as descriptionDetailsExportConfig,
  schema as descriptionDetailsSchema,
} from "./primitives/lists/DescriptionDetails.schema"
import {
  exportConfig as descriptionListExportConfig,
  schema as descriptionListSchema,
} from "./primitives/lists/DescriptionList.schema"
import {
  exportConfig as descriptionTermExportConfig,
  schema as descriptionTermSchema,
} from "./primitives/lists/DescriptionTerm.schema"
import {
  exportConfig as listItemExportConfig,
  schema as listItemSchema,
} from "./primitives/lists/ListItem.schema"
import {
  exportConfig as orderedListExportConfig,
  schema as orderedListSchema,
} from "./primitives/lists/OrderedList.schema"
import {
  exportConfig as unorderedListExportConfig,
  schema as unorderedListSchema,
} from "./primitives/lists/UnorderedList.schema"
import {
  exportConfig as tableDataExportConfig,
  schema as tableDataSchema,
} from "./primitives/tables/TableData.schema"
// Primitives
import {
  exportConfig as tableHeaderExportConfig,
  schema as tableHeaderSchema,
} from "./primitives/tables/TableHeader.schema"
import {
  exportConfig as tableInputExportConfig,
  schema as tableInputSchema,
} from "./primitives/tables/TableInput.schema"
import {
  exportConfig as blockquoteExportConfig,
  schema as blockquoteSchema,
} from "./primitives/texts/Blockquote.schema"
import {
  exportConfig as calloutExportConfig,
  schema as calloutSchema,
} from "./primitives/texts/Callout.schema"
import {
  exportConfig as citeExportConfig,
  schema as citeSchema,
} from "./primitives/texts/Cite.schema"
import {
  exportConfig as codeblockExportConfig,
  schema as codeblockSchema,
} from "./primitives/texts/Codeblock.schema"
import {
  exportConfig as descriptionExportConfig,
  schema as descriptionSchema,
} from "./primitives/texts/Description.schema"
import {
  exportConfig as displayExportConfig,
  schema as displaySchema,
} from "./primitives/texts/Display.schema"
import {
  exportConfig as headingExportConfig,
  schema as headingSchema,
} from "./primitives/texts/Heading.schema"
import {
  exportConfig as linkExportConfig,
  schema as linkSchema,
} from "./primitives/texts/Link.schema"
import {
  exportConfig as subheadingExportConfig,
  schema as subheadingSchema,
} from "./primitives/texts/Subheading.schema"
import {
  exportConfig as subtitleExportConfig,
  schema as subtitleSchema,
} from "./primitives/texts/Subtitle.schema"
import {
  exportConfig as taglineExportConfig,
  schema as taglineSchema,
} from "./primitives/texts/Tagline.schema"
import {
  exportConfig as textExportConfig,
  schema as textSchema,
} from "./primitives/texts/Text.schema"
import {
  exportConfig as titleExportConfig,
  schema as titleSchema,
} from "./primitives/texts/Title.schema"
import {
  exportConfig as sourceExportConfig,
  schema as sourceSchema,
} from "./primitives/video/Source.schema"
import {
  exportConfig as trackExportConfig,
  schema as trackSchema,
} from "./primitives/video/Track.schema"
import {
  exportConfig as videoExportConfig,
  schema as videoSchema,
} from "./primitives/video/Video.schema"
// Screens
import {
  exportConfig as screenExportConfig,
  schema as screenSchema,
} from "./screens/Screen.schema"

export const elements = [
  tableRowDataSchema,
  tableRowHeaderSchema,
  listItemInputSchema,
  listItemStandardSchema,
  listItemGeneralSchema,
  listItemAvatarSchema,
  listItemProductSchema,
  listItemTodoSchema,
  listItemTreeSchema,
  sectionNewsletterSchema,
  sectionSocialSchema,
  sectionLegalSchema,
  sectionBrandSchema,
  sectionNavSchema,
  calendarWeekdaysSchema,
  calendarWeekSchema,
  inputIconicSchema,
  inputCheckboxSchema,
  inputTextSchema,
  optionGroupSchema,
  inputDropdownSchema,
  inputRadioSchema,
  inputSearchSchema,
  buttonToolsSchema,
  buttonSocialSchema,
  buttonSchema,
  buttonSegmentedSchema,
  chipSchema,
  chipCountSchema,
  textblockDetailsSchema,
  textblockSchema,
  textblockAvatarSchema,
  textblockTitleSchema,
  textblockHeaderSchema,
  headerActionSchema,
  headerCardSchema,
  avatarIconSchema,
  avatarSchema,
  avatarProductSchema,
]

export const primitives = [
  tableHeaderSchema,
  tableInputSchema,
  tableDataSchema,
  videoSchema,
  trackSchema,
  sourceSchema,
  descriptionListSchema,
  descriptionDetailsSchema,
  listItemSchema,
  unorderedListSchema,
  descriptionTermSchema,
  orderedListSchema,
  hrSchema,
  navSchema,
  iconSchema,
  checkboxSchema,
  radioSchema,
  selectSchema,
  legendSchema,
  labelSchema,
  inputSchema,
  optionSchema,
  codeblockSchema,
  subtitleSchema,
  calloutSchema,
  subheadingSchema,
  headingSchema,
  citeSchema,
  blockquoteSchema,
  titleSchema,
  descriptionSchema,
  linkSchema,
  taglineSchema,
  displaySchema,
  textSchema,
  imageSchema,
]

export const parts = [
  tableFootSchema,
  tableBodySchema,
  tableHeadSchema,
  calendarHeaderSchema,
  calendarMonthSchema,
  fieldsetRadiosSchema,
  fieldsetCheckboxesSchema,
  fieldsetSchema,
  listContactsSchema,
  listGridSchema,
  listProductsSchema,
  listStandardSchema,
  listTodoSchema,
  cardStackedSchema,
  cardProductSchema,
  cardHorizontalSchema,
  barFooterSchema,
  barButtonsSchema,
  barNavigationSchema,
  barTopSchema,
  barHeaderSchema,
  barStatusSchema,
  barTabsSchema,
  adInstagramSchema,
  adYouTubeSchema,
  adIabSchema,
  adLinkedInSchema,
  adSocialMediaSchema,
  adTikTokSchema,
]

export const modules = [
  tableSchema,
  calendarSchema,
  footerSchema,
  panelDialogSchema,
  panelSidebarSchema,
  widgetTodoSchema,
]

export const screens = [screenSchema]

export const frames = [frameSchema, boardSchema]

export const exportConfig = {
  [ComponentId.TABLE_ROW_DATA]: tableRowDataExportConfig,
  [ComponentId.TABLE_ROW_HEADER]: tableRowHeaderExportConfig,
  [ComponentId.LIST_ITEM_INPUT]: listItemInputExportConfig,
  [ComponentId.LIST_ITEM_STANDARD]: listItemStandardExportConfig,
  [ComponentId.LIST_ITEM_GENERAL]: listItemGeneralExportConfig,
  [ComponentId.LIST_ITEM_AVATAR]: listItemAvatarExportConfig,
  [ComponentId.LIST_ITEM_PRODUCT]: listItemProductExportConfig,
  [ComponentId.LIST_ITEM_TODO]: listItemTodoExportConfig,
  [ComponentId.LIST_ITEM_TREE]: listItemTreeExportConfig,
  [ComponentId.SECTION_NEWSLETTER]: sectionNewsletterExportConfig,
  [ComponentId.SECTION_SOCIAL]: sectionSocialExportConfig,
  [ComponentId.SECTION_LEGAL]: sectionLegalExportConfig,
  [ComponentId.SECTION_BRAND]: sectionBrandExportConfig,
  [ComponentId.SECTION_NAV]: sectionNavExportConfig,
  [ComponentId.CALENDAR_WEEKDAYS]: calendarWeekdaysExportConfig,
  [ComponentId.CALENDAR_WEEK]: calendarWeekExportConfig,
  [ComponentId.INPUT_ICONIC]: inputIconicExportConfig,
  [ComponentId.INPUT_CHECKBOX]: inputCheckboxExportConfig,
  [ComponentId.INPUT_TEXT]: inputTextExportConfig,
  [ComponentId.OPTION_GROUP]: optionGroupExportConfig,
  [ComponentId.INPUT_DROPDOWN]: inputDropdownExportConfig,
  [ComponentId.INPUT_RADIO]: inputRadioExportConfig,
  [ComponentId.INPUT_SEARCH]: inputSearchExportConfig,
  [ComponentId.BUTTON_TOOLS]: buttonToolsExportConfig,
  [ComponentId.BUTTON_SOCIAL]: buttonSocialExportConfig,
  [ComponentId.BUTTON]: buttonExportConfig,
  [ComponentId.BUTTON_SEGMENTED]: buttonSegmentedExportConfig,
  [ComponentId.CHIP]: chipExportConfig,
  [ComponentId.CHIP_COUNT]: chipCountExportConfig,
  [ComponentId.TEXTBLOCK_DETAILS]: textblockDetailsExportConfig,
  [ComponentId.TEXTBLOCK]: textblockExportConfig,
  [ComponentId.TEXTBLOCK_AVATAR]: textblockAvatarExportConfig,
  [ComponentId.TEXTBLOCK_TITLE]: textblockTitleExportConfig,
  [ComponentId.TEXTBLOCK_HEADER]: textblockHeaderExportConfig,
  [ComponentId.HEADER_ACTION]: headerActionExportConfig,
  [ComponentId.HEADER_CARD]: headerCardExportConfig,
  [ComponentId.AVATAR_ICON]: avatarIconExportConfig,
  [ComponentId.AVATAR]: avatarExportConfig,
  [ComponentId.AVATAR_PRODUCT]: avatarProductExportConfig,
  [ComponentId.TABLE_HEADER]: tableHeaderExportConfig,
  [ComponentId.TABLE_INPUT]: tableInputExportConfig,
  [ComponentId.TABLE_DATA]: tableDataExportConfig,
  [ComponentId.VIDEO]: videoExportConfig,
  [ComponentId.TRACK]: trackExportConfig,
  [ComponentId.SOURCE]: sourceExportConfig,
  [ComponentId.DESCRIPTION_LIST]: descriptionListExportConfig,
  [ComponentId.DESCRIPTION_DETAILS]: descriptionDetailsExportConfig,
  [ComponentId.LIST_ITEM]: listItemExportConfig,
  [ComponentId.UNORDERED_LIST]: unorderedListExportConfig,
  [ComponentId.DESCRIPTION_TERM]: descriptionTermExportConfig,
  [ComponentId.ORDERED_LIST]: orderedListExportConfig,
  [ComponentId.HR]: hrExportConfig,
  [ComponentId.NAV]: navExportConfig,
  [ComponentId.ICON]: iconExportConfig,
  [ComponentId.CHECKBOX]: checkboxExportConfig,
  [ComponentId.RADIO]: radioExportConfig,
  [ComponentId.SELECT]: selectExportConfig,
  [ComponentId.LEGEND]: legendExportConfig,
  [ComponentId.LABEL]: labelExportConfig,
  [ComponentId.INPUT]: inputExportConfig,
  [ComponentId.OPTION]: optionExportConfig,
  [ComponentId.CODEBLOCK]: codeblockExportConfig,
  [ComponentId.SUBTITLE]: subtitleExportConfig,
  [ComponentId.CALLOUT]: calloutExportConfig,
  [ComponentId.SUBHEADING]: subheadingExportConfig,
  [ComponentId.HEADING]: headingExportConfig,
  [ComponentId.CITE]: citeExportConfig,
  [ComponentId.BLOCKQUOTE]: blockquoteExportConfig,
  [ComponentId.TITLE]: titleExportConfig,
  [ComponentId.DESCRIPTION]: descriptionExportConfig,
  [ComponentId.LINK]: linkExportConfig,
  [ComponentId.TAGLINE]: taglineExportConfig,
  [ComponentId.DISPLAY]: displayExportConfig,
  [ComponentId.TEXT]: textExportConfig,
  [ComponentId.IMAGE]: imageExportConfig,
  [ComponentId.TABLE_FOOT]: tableFootExportConfig,
  [ComponentId.TABLE_BODY]: tableBodyExportConfig,
  [ComponentId.TABLE_HEAD]: tableHeadExportConfig,
  [ComponentId.CALENDAR_HEADER]: calendarHeaderExportConfig,
  [ComponentId.CALENDAR_MONTH]: calendarMonthExportConfig,
  [ComponentId.FIELDSET_RADIOS]: fieldsetRadiosExportConfig,
  [ComponentId.FIELDSET_CHECKBOXES]: fieldsetCheckboxesExportConfig,
  [ComponentId.FIELDSET]: fieldsetExportConfig,
  [ComponentId.LIST_CONTACTS]: listContactsExportConfig,
  [ComponentId.LIST_GRID]: listGridExportConfig,
  [ComponentId.LIST_PRODUCTS]: listProductsExportConfig,
  [ComponentId.LIST_STANDARD]: listStandardExportConfig,
  [ComponentId.LIST_TODO]: listTodoExportConfig,
  [ComponentId.CARD_STACKED]: cardStackedExportConfig,
  [ComponentId.CARD_PRODUCT]: cardProductExportConfig,
  [ComponentId.CARD_HORIZONTAL]: cardHorizontalExportConfig,
  [ComponentId.BAR_FOOTER]: barFooterExportConfig,
  [ComponentId.BAR_BUTTONS]: barButtonsExportConfig,
  [ComponentId.BAR_NAVIGATION]: barNavigationExportConfig,
  [ComponentId.BAR_TOP]: barTopExportConfig,
  [ComponentId.BAR_HEADER]: barHeaderExportConfig,
  [ComponentId.BAR_STATUS]: barStatusExportConfig,
  [ComponentId.BAR_TABS]: barTabsExportConfig,
  [ComponentId.AD_INSTAGRAM]: adInstagramExportConfig,
  [ComponentId.AD_YOU_TUBE]: adYouTubeExportConfig,
  [ComponentId.AD_IAB]: adIabExportConfig,
  [ComponentId.AD_LINKED_IN]: adLinkedInExportConfig,
  [ComponentId.AD_SOCIAL_MEDIA]: adSocialMediaExportConfig,
  [ComponentId.AD_TIK_TOK]: adTikTokExportConfig,
  [ComponentId.TABLE]: tableExportConfig,
  [ComponentId.CALENDAR]: calendarExportConfig,
  [ComponentId.FOOTER]: footerExportConfig,
  [ComponentId.PANEL_DIALOG]: panelDialogExportConfig,
  [ComponentId.PANEL_SIDEBAR]: panelSidebarExportConfig,
  [ComponentId.WIDGET_TODO]: widgetTodoExportConfig,
  [ComponentId.SCREEN]: screenExportConfig,
  [ComponentId.FRAME]: frameExportConfig,
  [ComponentId.BOARD]: boardExportConfig,
}
