/**
 * Generated by scripts/generate-font-metadata.mjs. Do not edit by hand.
 * Descriptive metadata captured from the vendor, keyed by family slot id.
 */
import type { FontFamilyMeta } from "../../types/font-collection"

export const googleFontMetadata: Record<string, FontFamilyMeta> = {
  abel: {
    category: "Sans Serif",
    designer: "MADType",
    description:
      "Abel is a modern interpretation of the condensed flat-sided sans serif. Originally used for newspaper headlines and posters, this style can also be used for text on the web. Its angled terminals and spiked stems give it enough style to be unique at display sizes, while its mono-weight still works well at smaller text sizes.",
  },
  anton: {
    category: "Display",
    designer: "Vernon Adams",
    description:
      "Anton is a reworking of a traditional advertising sans serif typeface. The letter forms have been digitised and then reshaped for use as a webfont, the counters have been opened up a little and the stems optimised for use as bold display font in modern web browsers.",
  },
  archivo: {
    category: "Sans Serif",
    designer: "Omnibus-Type",
    description:
      "Archivo is a grotesque sans serif typeface family originally designed for highlights and headlines. This family is reminiscent of late nineteenth century American typefaces. The technical and aesthetic characteristics of the font are both crafted for high performance typography. It was designed to be used simultaneously in print and online platforms and supports over 200 world languages.",
  },
  arimo: {
    category: "Sans Serif",
    designer: "Steve Matteson",
    description:
      "Arimo was designed by Steve Matteson as an innovative, refreshing sans serif design that is metrically compatible with Arial™. Arimo offers improved on-screen readability characteristics and the pan-European WGL character set and solves the needs of developers looking for width-compatible fonts to address document portability across platforms.",
  },
  arvo: {
    category: "Serif",
    designer: "Anton Koovit",
    description:
      "Arvo is a geometric slab-serif typeface family suited for screen and print. The family includes 4 cuts: Roman, Italic, Roman Bold, Bold Italic. It is a libre font, first published in Google Fonts. The flavour of the font is rather mixed. It's monolinear-ish, but has a tiny bit of contrast (which increases the legibility a little in Mac OS X.)",
  },
  assistant: {
    category: "Sans Serif",
    designer: "Adobe Systems Inc., Ben Nathan",
    description:
      "Assistant is a Hebrew and Latin type family, with a contemporary sans serif Hebrew design. The family contains 6 upright styles, from ExtraLight to Black.",
  },
  "atkinson-hyperlegible-next": {
    category: "Sans Serif",
    designer:
      "Braille Institute, Applied Design Works, Elliott Scott, Megan Eiswerth, Letters From Sweden",
  },
  barlow: {
    category: "Sans Serif",
    designer: "Jeremy Tribby",
    description:
      "Barlow is a slightly rounded, low-contrast, grotesk type family. Drawing from the visual style of the California public, Barlow shares qualities with the state's car plates, highway signs, busses, and trains.",
  },
  "barlow-condensed": {
    category: "Sans Serif",
    designer: "Jeremy Tribby",
    description:
      "Barlow is a slightly rounded, low-contrast, grotesk type family. Drawing from the visual style of the California public, Barlow shares qualities with the state's car plates, highway signs, busses, and trains.",
  },
  "bebas-neue": {
    category: "Display",
    designer: "Ryoichi Tsunekawa",
    description:
      "Bebas Neue is a display family suitable for headlines, captions, and packaging, designed by Ryoichi Tsunekawa. It's based on the original Bebas typeface. The family is suitable for pro users due to its extended character set and OpenType features.",
  },
  "bricolage-grotesque": {
    category: "Sans Serif",
    designer: "Mathieu Triay",
    description:
      "Bricolage Grotesque is a collage of lots of different things: historical sources, technical decisions and personal feelings. It started as a fork of Mayenne Sans , an open-source single weight font designed by Jérémy Landes (Studio Triple). It evolved by reinforcing cues from French sources and British sources: the compressed weights lean more towards the anxious and wonky tones of Grotesque Nº9 and the regular weights have a bit more of Antique Olive's relaxed and confident attitude. The smaller optical sizes become more neutral and reflective of contemporary sans serifs, notably through the use of exaggerated ink traps.",
  },
  cabin: {
    category: "Sans Serif",
    designer: "Impallari Type, Rodrigo Fuenzalida",
    description:
      "Cabin is a humanist sans inspired by Edward Johnston&apos;s and Eric Gill&apos;s typefaces, with a touch of modernism. Cabin incorporates modern proportions, optical adjustments, and some elements of the geometric sans. It remains true to its roots, but has its own personality.",
  },
  cairo: {
    category: "Display",
    designer: "Mohamed Gaber, Accademia di Belle Arti di Urbino",
    description:
      "Cairo is a contemporary multilingual typeface family. Mohamed Gaber extended the Latin typeface family Titillum Web to support the Arabic script, with a design that is based on the Kufi calligraphic style. Now available as a variable font.",
  },
  caveat: {
    category: "Handwriting",
    designer: "Impallari Type",
    description:
      "Caveat is a handwriting type family designed by Pablo Impallari. It is designed for both short annotations and body text usage. For a different style, there is also a sister family, Caveat Brush",
  },
  comfortaa: {
    category: "Display",
    designer: "Johan Aakerlund",
    description:
      "Comfortaa is a rounded geometric sans-serif type design intended for large sizes. It is absolutely free, both for personal and commercial use.",
  },
  "comic-neue": {
    category: "Handwriting",
    designer: "Craig Rozynski, Hrant Papazian",
    description: "Comic Neue is an original reinterpretation of the classic, Comic Sans.",
  },
  "cormorant-garamond": {
    category: "Serif",
    designer: "Christian Thalmann",
    description:
      "Cormorant is a free display type family developed by Christian Thalmann. The project currently comprises a total of 45 font files spanning 9 different visual styles (Roman, Italic, Infant, Infant Italic, Garamond, Garamond Italic, Upright Cursive, Small Caps, and Unicase) and 5 weights (Light, Regular, Medium, SemiBold, and Bold.) Cormorant was conceived, drawn, spaced, kerned, programmed, interpolated, and produced in its entirety by Christian Thalmann of Catharsis Fonts. For an illustrated presentation and description of the family, please visit its B&#275;hance page .",
  },
  "crimson-text": {
    category: "Serif",
    designer: "Sebastian Kosch",
    description:
      "Crimson Text is a font family for book production in the tradition of beautiful oldstyle typefaces.",
  },
  "dm-sans": {
    category: "Sans Serif",
    designer: "Colophon Foundry",
    description:
      "DM Sans is a low-contrast geometric sans serif design, intended for use at smaller text sizes.",
  },
  dosis: {
    category: "Sans Serif",
    designer: "Impallari Type",
    description:
      "Dosis is a rounded sans-serif type family. It started with the Extra Light style, useful only at size 36pt or upm and the Extended Latin character set included many alternative characters, all designed by Edgar Tolentino and Pablo Impallari.",
  },
  "eb-garamond": {
    category: "Serif",
    designer: "Georg Duffner, Octavio Pardo",
    description:
      "EB Garamond is intended to be an excellent, classical, Garamond. It is a community project to create a revival of Claude Garamont’s famous humanist typefaces from the mid-16th century. This digital version reproduces the original design by Claude Garamont closely: The source for the letterforms is a scan of a specimen known as the “Berner specimen,” which was composed in 1592 by Conrad Berner, the son-in-law of Christian Egenolff and his successor at the Egenolff print office. This specimen shows Garamont’s roman and Granjon’s italic types at different sizes. Hence the name of this project: Egenolff-Berner Garamond.",
  },
  "exo-2": {
    category: "Sans Serif",
    designer: "Natanael Gama",
    description:
      "Exo 2 is a complete redrawing of Exo , a contemporary geometric sans serif typeface that tries to convey a technological/futuristic feeling while keeping an elegant design. Exo is a very versatile font, so it has 9 weights (the maximum on the web) and each with a true italic version. Exo 2 has a more organic look that will perform much better at small text sizes and in long texts.",
  },
  figtree: { category: "Sans Serif", designer: "Erik Kennedy" },
  "fira-sans": {
    category: "Sans Serif",
    designer: "Carrois Apostrophe",
    description:
      "Designed to integrate with the character of the Mozilla FirefoxOS, the Fira typefaces also aim to cover the legibility needs for a large range of handsets varying in screen quality and rendering.",
  },
  "fjalla-one": {
    category: "Sans Serif",
    designer: "Sorkin Type, Irina Smirnova",
    description:
      "Fjalla One is a medium contrast display sans serif. Fjalla One has been carefully adjusted to the restrictions of the screen. Despite having display characteristics Fjalla One can be used in a wide range of sizes.",
  },
  fraunces: {
    category: "Serif",
    designer: "Undercase Type, Phaedra Charles, Flavia Zimbardi",
    description:
      'Fraunces is a display, "Old Style" soft-serif typeface inspired by the mannerisms of early 20th century typefaces such as Windsor , Souvenir, and the Cooper Series. Fraunces was designed by Phaedra Charles and Flavia Zimbardi, partners at Undercase Type .',
  },
  geist: {
    category: "Sans Serif",
    designer:
      "Andrés Briganti, Mateo Zaragoza, Guillermo Rauch, Evil Rabbit, José Rago, Facundo Santana",
  },
  "hanken-grotesk": {
    category: "Sans Serif",
    designer: "Alfredo Marco Pradil, Hanken Design Co.",
    description:
      "Hanken Grotesk is a sans serif typeface inspired by the classic grotesques. Geometry, metrics, punctuations and OpenType features have been updated to support a wide range of projects such as environmental signage, textface for books and magazines, Interface, Websites and Mobile Applications.",
  },
  heebo: {
    category: "Sans Serif",
    designer: "Oded Ezer",
    description:
      "Heebo is a Hebrew and Latin typeface family, which extends Christian Roberton's Roboto Latin to Hebrew. The Hebrew was drawn by Oded Ezer and the font files were mastered by Meir Sadan.",
  },
  hind: {
    category: "Sans Serif",
    designer: "Indian Type Foundry",
    description:
      "Hind is an Open Source typeface supporting the Devanagari and Latin scripts. Developed explicitly for use in User Interface design, the Hind font family includes five styles. Hind’s letterforms have a humanist-style construction, which is paired with seemingly monolinear strokes. Most of these strokes have flat endings: they either terminate with a horizontal or a vertical shear, rather than on a diagonal. This helps create clear-cut counter forms between the characters. In addition to this, Hind’s letterforms feature open apertures. The entire typeface family feels very legible when used to set text.",
  },
  "hind-siliguri": {
    category: "Sans Serif",
    designer: "Indian Type Foundry",
    description:
      "Hind Siliguri is a family of five Bengali fonts, which are part of the Indian Type Foundry’s larger Open Source Hind Multi-Script project. Hind Multi-Script is a type system providing nine stylistically-matching font families – one for each of the following writing systems used in Bangladesh, India, Nepal, and Sri Lanka: Bengali, Devanagari, Gujarati, Gurmukhi, Kannada, Malayalam, Tamil, Telugu, and Sinhala. In addition to Bengali, the Hind Siliguri fonts also include Latin-script characters.",
  },
  "ibm-plex-mono": {
    category: "Monospace",
    designer: "Mike Abbink, Bold Monday",
    description:
      "IBM Plex® is the corporate typeface for IBM worldwide and an open-source project developed by the IBM Brand & Experience team (BX&D). Plex is an international typeface family designed to capture IBM’s brand spirit and history and to illustrate the unique relationship between mankind and machine—a principal theme for IBM since the turn of the century. The result is a neutral yet friendly Grotesque style typeface that balances design with the engineered details that make Plex distinctly IBM. The family includes a Sans, Sans Condensed, Mono, and Serif and has excellent legibility in print, web, and mobile interfaces.",
  },
  "ibm-plex-sans": {
    category: "Sans Serif",
    designer: "Mike Abbink, Bold Monday",
    description:
      "IBM Plex™ is an international typeface family designed by Mike Abbink, IBM BX&D, in collaboration with Bold Monday, an independent Dutch type foundry. Plex was designed to capture IBM’s spirit and history, and to illustrate the unique relationship between mankind and machine—a principal theme for IBM since the turn of the century. The result is a neutral, yet friendly Grotesque style typeface that includes a Sans, Sans Condensed, Mono, Serif, and several other styles for several languages , and has excellent legibility in print, web and mobile interfaces. Plex’s three designs work well independently, and even better together. Use the Sans as a contemporary compadre, the Serif for editorial storytelling, or the Mono to show code snippets. The unexpectedly expressive nature of the italics give you even more options for your designs.",
  },
  "ibm-plex-serif": {
    category: "Serif",
    designer: "Mike Abbink, Bold Monday",
    description:
      "IBM Plex® is the corporate typeface for IBM worldwide and an open-source project developed by the IBM Brand & Experience team (BX&D). Plex is an international typeface family designed to capture IBM’s brand spirit and history and to illustrate the unique relationship between mankind and machine—a principal theme for IBM since the turn of the century. The result is a neutral yet friendly Grotesque style typeface that balances design with the engineered details that make Plex distinctly IBM. The family includes a Sans, Sans Condensed, Mono, and Serif and has excellent legibility in print, web, and mobile interfaces.",
  },
  inconsolata: {
    category: "Sans Serif",
    designer: "Raph Levien",
    description:
      "Inconsolata was Raph Levien's first serious original font release. It is a monospace font, designed for printed code listings and the like. There are a great many &#8220;programmer fonts,&#8221; designed primarily for use on the screen, but in most cases do not have the attention to detail for high resolution rendering.",
  },
  "instrument-sans": {
    category: "Sans Serif",
    designer: "Rodrigo Fuenzalida, Jordan Egstad",
    description:
      "Instrument Sans is a font designed for the Instrument brand. It's a variable sans-serif which balances an abundance of precision with subtle notes of playfulness. Inspiration was drawn from our enduring interest in neo-grotesques. In a way, this family of weights, widths, and italics represent an orchestration of all of our favorite qualities in a sans-serif while featuring contemporary characteristics that make this typeface distinctly our own.",
  },
  inter: {
    category: "Sans Serif",
    designer: "Rasmus Andersson",
    description:
      "Inter is a variable font family carefully crafted & designed for computer screens.",
  },
  "josefin-sans": {
    category: "Sans Serif",
    designer: "Santiago Orozco",
    description:
      "The idea of this typeface is to be geometric, elegant, with a vintage feeling, for use at larger sizes. It is inspired by geometric sans serif designs from the 1920s. The x-height is half way from baseline to cap height, an unusual proportion.",
  },
  jost: {
    category: "Sans Serif",
    designer: "Owen Earl",
    description:
      "Jost is an original font created by indestructible type*. It is inspired by 1920s German sans-serifs. This is version 3.7. Jost is designed and maintained by Owen Earl, who is the creator of the font foundry indestructible type*. in 2020 Owen Earl, and Mirko Velimirovic worked together to make Jost a variable font.",
  },
  kanit: {
    category: "Sans Serif",
    designer: "Cadson Demak",
    description:
      "Kanit means mathematics in Thai, and the Kanit typeface family is a formal Loopless Thai and Sans Latin design. It is a combination of concepts, mixing a Humanist Sans Serif motif with the curves of Capsulated Geometric styles that makes it suitable for various uses, contemporary and futuristic. A notable detail is that the stroke terminals have flat angles, which allows the design to enjoy decreased spacing between letters while preserving readability and legibility at smaller point sizes.",
  },
  karla: {
    category: "Sans Serif",
    designer: "Jonny Pinhorn",
    description:
      "Karla is a grotesque sans serif family which has been expanded now to a variable font with a weight axis ranging from ExtraLight to ExtraBold plus full support of Western, Central, and South-Eastern European languages.",
  },
  lato: {
    category: "Sans Serif",
    designer: "Łukasz Dziedzic",
    description:
      "Lato means “Summer” in Polish, and it is a sans serif typeface family started in the summer of 2010 by Warsaw-based designer Łukasz Dziedzic. Originally conceived as part of a corporate identity for a large client, the family became available for a public release when they decided to go in different stylistic direction.",
  },
  lexend: {
    category: "Sans Serif",
    designer: "Bonnie Shaver-Troup, Thomas Jockin, Santiago Orozco, Héctor Gómez, Superunion",
    description:
      "Lexend fonts are intended to reduce visual stress and so improve reading performance. Initially they were designed with dyslexia and struggling readers in mind, but Bonnie Shaver-Troup, creator of the Lexend project, soon found out that these fonts are also great for everyone else.",
  },
  "libre-baskerville": {
    category: "Serif",
    designer: "Impallari Type",
    description:
      "Libre Baskerville is a web font optimized for body text (typically 16px.) It is based on the American Type Founder's Baskerville from 1941, but it has a taller x-height, wider counters and a little less contrast, that allow it to work well for reading on-screen.",
  },
  "libre-franklin": {
    category: "Sans Serif",
    designer: "Impallari Type",
    description:
      "Libre Franklin is an interpretation and expansion of the 1912 Morris Fuller Benton classic.",
  },
  lobster: {
    category: "Display",
    designer: "Impallari Type",
    description:
      'The Lobster font took a different approach. The new OpenType format gives us the possibility to have multiple versions of each letter, and that\'s exactly what we are doing: Instead of compromising the design of our letters to force connections, we do what lettering artist do. We draw many versions of each letter and a lot of different letter-pairs (aka "ligatures") so we always use the best possible variation of each letter depending of the context of the letter inside each word. All this happens automatically in any browser that supports ligatures.',
  },
  lora: {
    category: "Serif",
    designer: "Cyreal",
    description:
      "Lora is a well-balanced contemporary serif with roots in calligraphy. It is a text typeface with moderate contrast well suited for body text.",
  },
  manrope: {
    category: "Sans Serif",
    designer: "Mikhail Sharanda",
    description:
      "Manrope is an open-source modern sans-serif font family, designed by Mikhail Sharanda in 2018. In 2019, Mirko Velimirovic worked with Mikhail Sharanda to convert Manrope into a variable font.",
  },
  merriweather: {
    category: "Serif",
    designer: "Sorkin Type",
    description:
      "Merriweather was designed to be a text face that is pleasant to read on screens. It features a very large x height, slightly condensed letterforms, a mild diagonal stress, sturdy serifs and open forms.",
  },
  "mona-sans": {
    category: "Sans Serif",
    designer: "Tobias Bjerrome Ahlin, GitHub, Degarism Studio, Sebastian Carewe",
  },
  montserrat: {
    category: "Sans Serif",
    designer: "Julieta Ulanovsky, Sol Matas, Juan Pablo del Peral, Jacques Le Bailly",
    description:
      "The old posters and signs in the traditional Montserrat neighborhood of Buenos Aires inspired Julieta Ulanovsky to design this typeface and rescue the beauty of urban typography that emerged in the first half of the twentieth century. As urban development changes that place, it will never return to its original form and loses forever the designs that are so special and unique. The letters that inspired this project have work, dedication, care, color, contrast, light and life, day and night! These are the types that make the city look so beautiful. The Montserrat Project began with the idea to rescue what is in Montserrat and set it free under a libre license, the SIL Open Font License.",
  },
  mukta: {
    category: "Sans Serif",
    designer: "Ek Type",
    description:
      "Mukta is a Unicode compliant, versatile, contemporary, humanist, mono-linear typeface family available in seven weights, supporting Devanagari, Gujarati, Gurumukhi, Tamil and Latin scripts. This type family is a libre licensed version of Ek's self-titled multi-script project, an ongoing effort to develop a unified type family for each Indian script. The goal is to build one harmonious family across all Indian scripts without letting the visual features of one script dominate over others. This ensures that the fonts can be used successfully for both single and multi-script purposes.",
  },
  mulish: {
    category: "Sans Serif",
    designer: "Vernon Adams, Cyreal, Jacques Le Bailly",
    description:
      "Mulish is a minimalist Sans Serif typeface, designed for both display and text typography.",
  },
  "nanum-gothic": {
    category: "Sans Serif",
    designer: "Sandoll Communication",
    description:
      "The Nanum fonts (Korean : 나눔글꼴) are unicode fonts designed especially for the Korean-language script, designed by Sandoll Communications (Korean : 산돌 커뮤니케이션) and Fontrix (Korean : 폰트릭스). The publisher is Naver. Nanum Gothic is a contemporary sans-serif with a warm touch and is expertly hinted for screen use.",
  },
  "national-park": {
    category: "Sans Serif",
    designer: "Andrea Herstowski, Ben Hoepner, Jeremy Shellhorn",
  },
  "noto-sans": {
    category: "Sans Serif",
    designer: "Google",
    description:
      "Noto is a global font collection for writing in all modern and ancient languages. Noto Sans is an unmodulated (“sans serif”) design for texts in the Latin, Cyrillic and Greek scripts, which is also suitable as the complementary choice for other script-specific Noto Sans fonts. It has italic styles, multiple weights and widths, and 3,741 glyphs.",
  },
  "noto-sans-arabic": {
    category: "Sans Serif",
    designer: "Google",
    description:
      "Noto is a global font collection for writing in all modern and ancient languages. Noto Sans Arabic is an unmodulated (“sans serif”) design for texts in the Middle Eastern Arabic script. It has multiple weights and widths, and 1,642 glyphs.",
  },
  "noto-sans-jp": {
    category: "Sans Serif",
    designer: "Google",
    description:
      "Noto is a global font collection for writing in all modern and ancient languages. Noto Sans JP is an unmodulated (“sans serif”) design for the Japanese language and other languages used in Japan. It covers Hiragana , Katakana and Kanji . It also supports Latin, Cyrillic, Greek and Hangul . It has multiple weights.",
  },
  "noto-sans-kr": {
    category: "Sans Serif",
    designer: "Google",
    description:
      "Noto is a global font collection for writing in all modern and ancient languages. Noto Sans KR is an unmodulated (“sans serif”) design for the Korean language using Hangul and the Korean Hanja scripts. It also supports Hiragana, Katakana, Latin, Cyrillic and Greek . It has multiple weights.",
  },
  "noto-sans-sc": {
    category: "Sans Serif",
    designer: "Google",
    description:
      "Noto is a global font collection for writing in all modern and ancient languages. Noto Sans SC is an unmodulated (“sans serif”) design for languages in mainland China that use the Simplified Chinese variant of the Han ideograms. It also supports Hiragana, Katakana, Latin, Cyrillic, Greek and Hangul . It has multiple weights.",
  },
  "noto-sans-tc": {
    category: "Sans Serif",
    designer: "Google",
    description:
      "Noto is a global font collection for writing in all modern and ancient languages. Noto Sans TC is an unmodulated (“sans serif”) design for languages in Taiwan and Macau that use the Traditional Chinese variant of the Han ideograms. It also supports Hiragana, Katakana, Latin, Cyrillic, Greek and Hangul . It has multiple weights.",
  },
  "noto-serif": {
    category: "Serif",
    designer: "Google",
    description:
      "Noto is a global font collection for writing in all modern and ancient languages. Noto Serif is a modulated (“serif”) design for texts in the Latin, Cyrillic and Greek scripts, also suitable as the complementary font for other script-specific Noto Serif fonts. It has italic styles, multiple weights and widths, and 3,256 glyphs.",
  },
  "noto-serif-jp": {
    category: "Serif",
    designer: "Google",
    description:
      "Noto is a global font collection for writing in all modern and ancient languages. Noto Serif JP is a modulated (“serif”) design for the Japanese language and other languages used in Japan. It supports Hiragana , Katakana , Kanji , Latin, Cyrillic, Greek and Hangul . It has multiple weights.",
  },
  nunito: {
    category: "Sans Serif",
    designer: "Vernon Adams, Cyreal, Jacques Le Bailly",
    description:
      "Nunito is a well balanced sans serif typeface superfamily, with 2 versions: The project began with Nunito, created by Vernon Adams as a rounded terminal sans serif for display typography. Jacques Le Bailly extended it to a full set of weights, and an accompanying regular non-rounded terminal version, Nunito Sans .",
  },
  "nunito-sans": {
    category: "Sans Serif",
    designer: "Vernon Adams, Jacques Le Bailly, Manvel Shmavonyan, Alexei Vanyashin",
    description:
      "Nunito is a well balanced sans serif typeface superfamily, with 2 versions: The project began with Nunito , created by Vernon Adams as a rounded terminal sans serif for display typography. Jacques Le Bailly extended it to a full set of weights, and an accompanying regular non-rounded terminal version, Nunito Sans.",
  },
  onest: { category: "Sans Serif", designer: "Dmitri Voloshin, Andrey Kudryavtsev" },
  "open-sans": {
    category: "Sans Serif",
    designer: "Steve Matteson",
    description:
      "Open Sans is a humanist sans serif typeface designed by Steve Matteson, Type Director of Ascender Corp. This version contains the complete 897 character set, which includes the standard ISO Latin 1, Latin CE, Greek and Cyrillic character sets. Open Sans was designed with an upright stress, open forms and a neutral, yet friendly appearance. It was optimized for print, web, and mobile interfaces, and has excellent legibility characteristics in its letterforms.",
  },
  oswald: {
    category: "Sans Serif",
    designer: "Vernon Adams, Kalapi Gajjar, Cyreal",
    description:
      "Oswald is a reworking of the classic style historically represented by the 'Alternate Gothic' sans serif typefaces. The characters of Oswald were initially re-drawn and reformed to better fit the pixel grid of standard digital screens. Oswald is designed to be used freely across the internet by web browsers on desktop computers, laptops and mobile devices.",
  },
  outfit: {
    category: "Sans Serif",
    designer: "Smartsheet Inc, Rodrigo Fuenzalida",
    description:
      "A beautiful geometric sans: The official typeface for brand automation company outfit.io. Inspired by the ligature-rich outfit wordmark, Outfit.io is delighted to release it's own type family. The Outfit typeface links the Outfit written voice to Outfit product marks; on brand by default.",
  },
  overpass: {
    category: "Sans Serif",
    designer: "Delve Withrington, Dave Bailey, Thomas Jockin",
    description:
      "Overpass is a free, Open Source typeface designed by Delve Fonts . The design of Overpass is an interpretation of the well-known “Highway Gothic” letterforms from the Standard Alphabets for Traffic Control Devices published by the U.S. Federal Highway Administration. Starting from those specifications, critical adjustments were made to the letterforms to create an optimal presentation at smaller sizes on-screen and later for display sizes, especially in the lighter weights.",
  },
  oxygen: {
    category: "Sans Serif",
    designer: "Vernon Adams",
    description:
      "The Oxygen typeface family is created as part of the KDE Project, a libre desktop for the GNU+Linux operating system. The design is optimized for the FreeType font rendering system and works well in all graphical user interfaces, desktops and devices.",
  },
  "playfair-display": {
    category: "Serif",
    designer: "Claus Eggers Sørensen",
    description:
      "Playfair is a transitional design. In the European Enlightenment in the late 18th century, broad nib quills were replaced by pointed steel pens as the popular writing tool of the day. Together with developments in printing technology, ink, and paper making, it became fashionable to print letterforms of high contrast and delicate hairlines that were increasingly detached from the written letterforms. This design lends itself to this period, and while it is not a revival of any particular design, it takes influence from the designs of John Baskerville and from ‘Scotch Roman’ designs.",
  },
  "plus-jakarta-sans": {
    category: "Sans Serif",
    designer: "Tokotype",
    description:
      "Plus Jakarta Sans is a fresh take on geometric sans serif styles, designed by Gumpita Rahayu from Tokotype. The fonts were originally commissioned by 6616 Studio for Jakarta Provincial Government program's +Jakarta City of Collaboration identity in 2020.",
  },
  poppins: {
    category: "Sans Serif",
    designer: "Indian Type Foundry, Jonny Pinhorn, Ninad Kale",
    description:
      "Geometric sans serif typefaces have always been popular, and with support for both the Devanagari and Latin writing systems, Poppins is an internationalist addition to the genre.",
  },
  prompt: {
    category: "Sans Serif",
    designer: "Cadson Demak",
    description:
      "Prompt in Thai means &#8220;ready,&#8221; the same as in English. Prompt is a loopless Thai and sans Latin typeface. The simple and geometric Latin was developed to work harmoniously with the loopless Thai that has wide proportions and airy negative space. It is suitable for both web and print usage, such as magazines, newspapers, and posters.",
  },
  "pt-sans": {
    category: "Sans Serif",
    designer: "ParaType",
    description:
      'PT Sans was developed for the project "Public Types of Russian Federation." The second family of the project, PT Serif, is also available.',
  },
  "pt-sans-narrow": {
    category: "Sans Serif",
    designer: "ParaType",
    description:
      'PT Sans was developed for the project "Public Types of Russian Federation." The second family of the project, PT Serif, is also available.',
  },
  "pt-serif": {
    category: "Serif",
    designer: "ParaType",
    description:
      "PT Serif™ is the second pan-Cyrillic font family developed for the project “Public Types of the Russian Federation.” The first family of the project, PT Sans, was released in 2009.",
  },
  "public-sans": {
    category: "Sans Serif",
    designer: "USWDS, Dan Williams, Pablo Impallari, Rodrigo Fuenzalida",
    description:
      "Based on Libre Franklin , Public Sans is a strong, neutral typeface for interfaces, text, and headings. It was Developed by the United States Web Design System .",
  },
  quicksand: {
    category: "Sans Serif",
    designer: "Andrew Paglinawan",
    description:
      "Quicksand is a display sans serif with rounded terminals. The project was initiated by Andrew Paglinawan in 2008 using geometric shapes as a core foundation. It is designed for display purposes but kept legible enough to use in small sizes as well. In 2016, in collaboration with Andrew, it was thoroughly revised by Thomas Jockin to improve the quality. In 2019, Mirko Velimirovic converted the family into a variable font.",
  },
  "radio-canada-big": {
    category: "Sans Serif",
    designer: "Étienne Aubert Bonn",
    description:
      "CBC/Radio-Canada is Canada's national public broadcaster. Their mandate is to inform, enlighten, and entertain in order to strengthen Canadian culture on radio, television, and digital platforms.",
  },
  rajdhani: {
    category: "Sans Serif",
    designer: "Indian Type Foundry",
    description:
      "Rajdhani has modularized letterforms and supports the Devanagari and Latin writing systems. The squared and condensed appearance may be interpreted as technical or even futuristic. Typically round bowls and other letterform elements have straight sides in Rajdhani. The stroke terminals typically end in flat line segments that are horizontal or vertical, rather than diagonal. Their corners are slightly rounded, giving stroke-endings a softer feeling, rather than a pointy one.",
  },
  raleway: {
    category: "Sans Serif",
    designer: "Matt McInerney, Pablo Impallari, Rodrigo Fuenzalida",
    description:
      "Raleway is an elegant sans-serif typeface family. Initially designed by Matt McInerney as a single thin weight, it was expanded into a 9 weight family by Pablo Impallari and Rodrigo Fuenzalida in 2012 and iKerned by Igino Marini. A thorough review and italic was added in 2016.",
  },
  "red-hat-display": {
    category: "Sans Serif",
    designer: "MCKL",
    description:
      "Red Hat is a family of typefaces produced in 2 optical sizes and a monospace style, in a range of weights with italics. The fonts were originally commissioned by Paula Scher, Pentagram and designed by Jeremy Mickel, MCKL for the new Red Hat identity.",
  },
  "reddit-sans": {
    category: "Sans Serif",
    designer: "Stephen Hutchings, OrangeRed",
    description:
      "Reddit Sans is a humanist sans-serif designed for Reddit. Reddit Sans is complemented by Reddit Sans Condensed and Reddit Mono.",
  },
  roboto: {
    category: "Sans Serif",
    designer: "Christian Robertson, ParaType, Font Bureau",
    description:
      "Roboto has a dual nature. It has a mechanical skeleton and the forms are largely geometric. At the same time, the font features friendly and open curves. While some grotesks distort their letterforms to force a rigid rhythm, Roboto doesn’t compromise, allowing letters to be settled into their natural width. This makes for a more natural reading rhythm more commonly found in humanist and serif types.",
  },
  "roboto-condensed": {
    category: "Sans Serif",
    designer: "Christian Robertson",
    description:
      "Roboto has a dual nature. It has a mechanical skeleton and the forms are largely geometric. At the same time, the font features friendly and open curves. While some grotesks distort their letterforms to force a rigid rhythm, Roboto doesn’t compromise, allowing letters to be settled into their natural width. This makes for a more natural reading rhythm more commonly found in humanist and serif types.",
  },
  "roboto-flex": {
    category: "Sans Serif",
    designer:
      "Font Bureau, David Berlow, Santiago Orozco, Irene Vlachou, Ilya Ruderman, Yury Ostromentsky, Mikhail Strukov",
    description:
      "Roboto Flex upgrades Roboto so it becomes a more powerful typeface system. With Flex, you can customize Roboto to express and finesse your text in ways never before possible. Today, people are constantly switching between devices, resizing browsers, and spreading our viewports across multiple screens. So Google commissioned Font Bureau to re-imagine Roboto to “flex” along with us, with a special emphasis on large-screen capabilities. This was achieved by amplifying the original design to an extreme range of weights, grades, widths and optical sizes.",
  },
  "roboto-mono": {
    category: "Monospace",
    designer: "Christian Robertson",
    description:
      "Roboto Mono is a monospaced addition to the Roboto type family. Like the other members of the Roboto family, the fonts are optimized for readability on screens across a wide variety of devices and reading environments. While the monospaced version is related to its variable width cousin, it doesn&#8217;t hesitate to change forms to better fit the constraints of a monospaced environment. For example, narrow glyphs like &#8216;I&#8217;, &#8216;l&#8217; and &#8216;i&#8217; have added serifs for more even texture while wider glyphs are adjusted for weight. Curved caps like &#8216;C&#8217; and &#8216;O&#8217; take on the straighter sides from Roboto Condensed.",
  },
  "roboto-slab": {
    category: "Serif",
    designer: "Christian Robertson",
    description:
      "Roboto has a dual nature. It has a mechanical skeleton and the forms are largely geometric. At the same time, the font features friendly and open curves. While some grotesks distort their letterforms to force a rigid rhythm, Roboto doesn’t compromise, allowing letters to be settled into their natural width. This makes for a more natural reading rhythm more commonly found in humanist and serif types.",
  },
  rubik: {
    category: "Sans Serif",
    designer: "Hubert and Fischer, Meir Sadan, Cyreal, Daniel Grumer, Omaima Dajani",
    description:
      "Rubik is a sans serif font family with slightly rounded corners designed by Philipp Hubert and Sebastian Fischer at Hubert & Fischer as part of the Chrome Cube Lab project.",
  },
  saira: {
    category: "Sans Serif",
    designer: "Omnibus-Type",
    description:
      "Saira is a sans serif system. It features a huge range of weights and widths, ready for all kind of typographic challenges.",
  },
  "schibsted-grotesk": {
    category: "Sans Serif",
    designer: "Bakken & Bæck, Henrik Kongsvoll",
    description:
      "Schibsted Grotesk is a digital-first font family crafted for user interfaces. Taking visual cues from Schibsted's proud history of printed media as well as our pioneering digital nature, Schibsted Grotesk was designed to become an active tool that empowers brand ambassadors and inspires internal and external audiences.",
  },
  sora: {
    category: "Sans Serif",
    designer: "Jonathan Barnbrook, Julián Moncada",
    description:
      "Sora, meaning sky in Japanese, is a typeface family commissioned for the Sora decentralized autonomous economy focused on empowering projects that benefit society. Soramitsu, the developer of Sora, is a Japanese technology company specializing in blockchain development and well-known for creating the first central bank digital currency.",
  },
  "source-code-pro": {
    category: "Monospace",
    designer: "Paul D. Hunt",
    description:
      "Source Code was designed by Paul D. Hunt as a companion to Source Sans.This complementary family was adapted from the Source design due to a request to create a monospaced version for coding applications. Source Code preserves the design features and vertical proportions of Source Sans, but alters the glyph widths so that they are uniform across all glyphs and weights.",
  },
  "source-sans-3": {
    category: "Sans Serif",
    designer: "Paul D. Hunt",
    description:
      "Source&#174; Sans Pro, Adobe's first open source typeface family, was designed by Paul D. Hunt. It is a sans serif typeface intended to work well in user interfaces.",
  },
  "space-grotesk": {
    category: "Sans Serif",
    designer: "Florian Karsten",
    description:
      "Space Grotesk is a proportional sans-serif typeface variant based on Colophon Foundry's fixed-width Space Mono family (2016). Originally designed by Florian Karsten in 2018, Space Grotesk retains the monospace's idiosyncratic details while optimizing for improved readability at non-display sizes.",
  },
  syne: {
    category: "Display",
    designer: "Bonjour Monde, Lucas Descroix, George Triantafyllakos",
    description:
      'The Syne family was originally designed in 2017 for the Art Center "Synesthésie", based in Saint-Denis — a suburb of Paris. The Art Center aims to gather diverse artistic personalities in order to create new and enriching situations. Based on that idea, Syne is an exploration of atypical associations of weights and styles.',
  },
  tajawal: {
    category: "Sans Serif",
    designer: "Boutros Fonts, Mourad Boutros, Soulaf Khalifeh",
    description:
      "Tajawal is a distinctive low contrast Arabic and sans serif Latin typeface family in 7 weights was created and designed by Boutros™ following a modern geometric style while still respecting the calligraphy rules of the Arabic script. Its fluid geometry makes it the perfect choice to use in both print and web applications, and alongside other Latin typefaces.",
  },
  teko: {
    category: "Sans Serif",
    designer: "Indian Type Foundry",
    description:
      "Teko is an Open Source typeface that currently supports the Devanagari and Latin scripts. This font family has been created for use in headlines and other display-sized text on screen. Five font styles make up the initial release.",
  },
  "tiktok-sans": {
    category: "Sans Serif",
    designer: "Grilli Type, Contrast Foundry, Type Network",
  },
  "titillium-web": {
    category: "Sans Serif",
    designer: "Accademia di Belle Arti di Urbino",
    description:
      "Titillium is born inside the Accademia di Belle Arti di Urbino as a didactic project Course Type design of the Master of Visual Design Campi Visivi.",
  },
  ubuntu: {
    category: "Sans Serif",
    designer: "Dalton Maag",
    description:
      "The Ubuntu Font Family are a set of matching new libre/open fonts in development during 2010-2011. The development is being funded by Canonical Ltd on behalf the wider Free Software community and the Ubuntu project. The technical font design work and implementation is being undertaken by Dalton Maag .",
  },
  urbanist: {
    category: "Sans Serif",
    designer: "Corey Hu",
    description:
      "Urbanist is a low-contrast, geometric sans-serif inspired by Modernist typography and design. The project was launched by Corey Hu in 2020 with 9 weights and accompanying italics. Conceived from elementary shapes, Urbanist's neutrality makes it a versatile display font for print and digital mediums. It is currently available as a variable font with a weight axis.",
  },
  "work-sans": {
    category: "Sans Serif",
    designer: "Wei Huang",
    description:
      "Work Sans is a typeface family based loosely on early Grotesques, such as those by Stephenson Blake , Miller & Richard and Bauerschen Giesserei . The Regular weight and others in the middle of the family are optimised for on-screen text usage at medium-sizes (14px-48px) and can also be used in print design. The fonts closer to the extreme weights are designed more for display use both on the web and in print. Overall, features are simplified and optimised for screen resolutions; for example, diacritic marks are larger than how they would be in print. A version optimised for desktop applications is available from the Work Sans github project page.",
  },
}
