/**
 * Icon glyph data, keyed by set. Each set ships one generated `<set>.icons.json`
 * of compact {@link IconData} rather than a source file per icon. The workspace
 * engine never imports this module; only rendering and export do.
 *
 * Data is generated by `scripts/generate-icons.mjs` from a pinned upstream
 * Iconify package. Regenerate deliberately; a consumer install never reads
 * upstream.
 */
import materialIcons from "./material.icons.json"

import type { IconId } from "../../icon-sets"
import type { IconData } from "./types"

const ICON_DATA_BY_PREFIX: Record<string, Record<string, IconData>> = {
  material: materialIcons as Record<string, IconData>,
}

/** Glyph data for an icon id, or `undefined` when the set has no data file. */
export function getIconData(iconId: IconId): IconData | undefined {
  const dash = iconId.indexOf("-")

  if (dash < 0) return undefined
  const prefix = iconId.slice(0, dash)
  const suffix = iconId.slice(dash + 1)

  return ICON_DATA_BY_PREFIX[prefix]?.[suffix]
}

/** True when the icon id resolves to a glyph data entry. */
export function hasIconData(iconId: IconId): boolean {
  return getIconData(iconId) !== undefined
}

export type { IconData }
