primary_region = 'fra'

[env]
  NODE_ENV = "production"

[deploy]
  release_command = 'npx prisma migrate deploy'

[http_service]
  internal_port = 2300
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
