/**
 * Cursor style values for element interaction.
 */
export enum Cursor {
  DEFAULT = "default",
  NONE = "none",
  CONTEXT_MENU = "context-menu",
  HELP = "help",
  POINTER = "pointer",
  PROGRESS = "progress",
  WAIT = "wait",
  CELL = "cell",
  CROSSHAIR = "crosshair",
  TEXT = "text",
  VERTICAL_TEXT = "vertical-text",
  ALIAS = "alias",
  COPY = "copy",
  MOVE = "move",
  NO_DROP = "no-drop",
  NOT_ALLOWED = "not-allowed",
  GRAB = "grab",
  GRABBING = "grabbing",
  E_RESIZE = "e-resize",
  N_RESIZE = "n-resize",
  NE_RESIZE = "ne-resize",
  NW_RESIZE = "nw-resize",
  S_RESIZE = "s-resize",
  SE_RESIZE = "se-resize",
  SW_RESIZE = "sw-resize",
  W_RESIZE = "w-resize",
  EW_RESIZE = "ew-resize",
  NS_RESIZE = "ns-resize",
  NESW_RESIZE = "nesw-resize",
  NWSE_RESIZE = "nwse-resize",
  COL_RESIZE = "col-resize",
  ROW_RESIZE = "row-resize",
  ALL_SCROLL = "all-scroll",
  ZOOM_IN = "zoom-in",
  ZOOM_OUT = "zoom-out",
}

/**
 * Readable cursor options for interface.
 */
export const CURSOR_OPTIONS: { value: Cursor; name: string }[] = [
  { value: Cursor.DEFAULT, name: "Default" },
  { value: Cursor.NONE, name: "None" },
  { value: Cursor.CONTEXT_MENU, name: "Context Menu" },
  { value: Cursor.HELP, name: "Help" },
  { value: Cursor.POINTER, name: "Pointer" },
  { value: Cursor.PROGRESS, name: "Progress" },
  { value: Cursor.WAIT, name: "Wait" },
  { value: Cursor.CELL, name: "Cell" },
  { value: Cursor.CROSSHAIR, name: "Crosshair" },
  { value: Cursor.TEXT, name: "Text" },
  { value: Cursor.VERTICAL_TEXT, name: "Vertical Text" },
  { value: Cursor.ALIAS, name: "Alias" },
  { value: Cursor.COPY, name: "Copy" },
  { value: Cursor.MOVE, name: "Move" },
  { value: Cursor.NO_DROP, name: "No Drop" },
  { value: Cursor.NOT_ALLOWED, name: "Not Allowed" },
  { value: Cursor.GRAB, name: "Grab" },
  { value: Cursor.GRABBING, name: "Grabbing" },
  { value: Cursor.E_RESIZE, name: "East Resize" },
  { value: Cursor.N_RESIZE, name: "North Resize" },
  { value: Cursor.NE_RESIZE, name: "Northeast Resize" },
  { value: Cursor.NW_RESIZE, name: "Northwest Resize" },
  { value: Cursor.S_RESIZE, name: "South Resize" },
  { value: Cursor.SE_RESIZE, name: "Southeast Resize" },
  { value: Cursor.SW_RESIZE, name: "Southwest Resize" },
  { value: Cursor.W_RESIZE, name: "West Resize" },
  { value: Cursor.EW_RESIZE, name: "East-West Resize" },
  { value: Cursor.NS_RESIZE, name: "North-South Resize" },
  { value: Cursor.NESW_RESIZE, name: "Northeast-Southwest Resize" },
  { value: Cursor.NWSE_RESIZE, name: "Northwest-Southeast Resize" },
  { value: Cursor.COL_RESIZE, name: "Column Resize" },
  { value: Cursor.ROW_RESIZE, name: "Row Resize" },
  { value: Cursor.ALL_SCROLL, name: "All Scroll" },
  { value: Cursor.ZOOM_IN, name: "Zoom In" },
  { value: Cursor.ZOOM_OUT, name: "Zoom Out" },
]
