/**
 * Vendors search tags for the icon catalog from the upstream icon projects'
 * own metadata (the same projects the icons themselves are vendored from):
 *
 *   carbon    @carbon/icons metadata.json `aliases`      (Apache-2.0)
 *   material  fonts.google.com/metadata/icons `tags`     (Apache-2.0)
 *   lucide    lucide-static tags.json                    (ISC)
 *
 * Output: src/icon-tags.ts — a GENERATED, committed module mapping icon id →
 * tags. It feeds both search layers (keyword tagWords and the embedding
 * passage text), giving icons the concept vocabulary their labels lack
 * ("Renew" ← refresh/restart, "Close" ← x/dismiss). Network happens HERE, at
 * generation time — never in the server. Core is untouched.
 *
 * Usage: npm run build:icon-tags   (rerun when Core's icon catalog changes)
 */
import fs from "node:fs"
import { register } from "node:module"
import { fileURLToPath } from "node:url"

register(new URL("../src/runtime/hooks.mjs", import.meta.url))

const { iconIds } = await import("@seldon/core/icon-sets")

const CARBON_URL = "https://unpkg.com/@carbon/icons@11.83.0/metadata.json"
const MATERIAL_URL =
  "https://fonts.google.com/metadata/icons?incomplete=1&key=material_symbols"
const LUCIDE_URL = "https://unpkg.com/lucide-static@1.24.0/tags.json"

/**
 * Material metadata tags every icon in sight with UI boilerplate; these carry
 * no discriminating signal and would let e.g. "button" match hundreds of
 * icons at tag strength.
 */
const GENERIC_TAGS = new Set([
  "app",
  "application",
  "application--house",
  "button",
  "component",
  "components",
  "design",
  "icon",
  "icons",
  "interface",
  "material",
  "screen",
  "site",
  "symbol",
  "ui",
  "ux",
  "web",
  "website",
])

const MAX_TAGS = 12

async function fetchJson(url: string): Promise<unknown> {
  const response = await fetch(url)
  if (!response.ok) throw new Error(`${url} → HTTP ${response.status}`)
  const text = await response.text()
  // fonts.google.com prefixes its JSON with an XSSI guard line (")]}'").
  return JSON.parse(text.replace(/^\)\]\}'/, ""))
}

/** "trash-can" / "shopping_cart" / "Trash Can" → "trashcan" (match key). */
const normalize = (name: string) =>
  name.replace(/[^a-z0-9]/gi, "").toLowerCase()

function cleanTags(raw: string[], selfName: string): string[] {
  const self = normalize(selfName)
  const seen = new Set<string>()
  const tags: string[] = []
  for (const tag of raw) {
    const trimmed = tag.trim().toLowerCase()
    if (!trimmed || GENERIC_TAGS.has(trimmed)) continue
    if (normalize(trimmed) === self) continue // the label itself adds nothing
    if (seen.has(trimmed)) continue
    seen.add(trimmed)
    tags.push(trimmed)
    if (tags.length >= MAX_TAGS) break
  }
  return tags
}

// ---- Collect upstream tags by (set, normalized name) -----------------------
const upstream = new Map<string, string[]>() // "carbon:trashcan" → tags

const carbon = (await fetchJson(CARBON_URL)) as {
  icons: Array<{ name: string; aliases?: string[] }>
}
for (const icon of carbon.icons) {
  upstream.set(
    `carbon:${normalize(icon.name)}`,
    cleanTags(icon.aliases ?? [], icon.name),
  )
}

const material = (await fetchJson(MATERIAL_URL)) as {
  icons: Array<{ name: string; tags?: string[] }>
}
for (const icon of material.icons) {
  upstream.set(
    `material:${normalize(icon.name)}`,
    cleanTags(icon.tags ?? [], icon.name),
  )
}

const lucide = (await fetchJson(LUCIDE_URL)) as Record<string, string[]>
for (const [name, tags] of Object.entries(lucide)) {
  upstream.set(`lucide:${normalize(name)}`, cleanTags(tags, name))
}

// ---- Match against the shipped catalog -------------------------------------
const entries: Array<[string, string[]]> = []
const counts: Record<string, { matched: number; total: number }> = {}

for (const iconId of iconIds as readonly string[]) {
  if (iconId.startsWith("__")) continue
  const set = iconId.slice(0, iconId.indexOf("-"))
  const name = iconId.slice(iconId.indexOf("-") + 1)
  counts[set] ??= { matched: 0, total: 0 }
  counts[set].total++
  const tags = upstream.get(`${set}:${normalize(name)}`)
  if (tags && tags.length > 0) {
    counts[set].matched++
    entries.push([iconId, tags])
  }
}

// ---- Emit the generated module ----------------------------------------------
const body = entries
  .map(([id, tags]) => `  "${id}": ${JSON.stringify(tags)},`)
  .join("\n")
const header = `/**
 * GENERATED by scripts/build-icon-tags.ts — DO NOT EDIT MANUALLY.
 *
 * Search tags for the packaged icon catalog, vendored from the upstream
 * icon projects' own search metadata (carbon aliases, Apache-2.0; material
 * symbols tags, Apache-2.0; lucide tags, ISC). Icons without upstream
 * metadata (including the seldon set) are simply absent.
 *
 * Regenerate: npm run build:icon-tags
 */
export const ICON_TAGS: Record<string, readonly string[]> = {
${body}
}
`
const out = fileURLToPath(new URL("../src/icon-tags.ts", import.meta.url))
fs.writeFileSync(out, header)

for (const [set, c] of Object.entries(counts)) {
  console.log(`${set}: tagged ${c.matched}/${c.total}`)
}
console.log(
  `wrote ${out} (${entries.length} icons, ${Math.round(header.length / 1024)} KB)`,
)
