/**
 * The component id union for the catalog. Each id matches a schema's `id` and a
 * `ComponentId` key. Keep this enum aligned with the schema files and
 * `packages/core/components/catalog`. To sync it after schema changes, invoke
 * `@foundation-components-catalog`.
 *
 * `ComponentId` stays an enum because it is part of the serialized workspace API.
 */
export enum ComponentId {
  ARTICLE_CARD = "articleCard",
  ACCORDION = "accordion",
  ACTIVITY_TIMELINE = "activityTimeline",
  AVATAR = "avatar",
  BADGE = "badge",
  BAR = "bar",
  BLOCKQUOTE = "blockquote",
  BOARD = "board",
  LINKS_FOOTER = "linksFooter",
  BUTTON = "button",
  CALENDAR = "calendar",
  CALENDAR_DAY = "calendarDay",
  CARD_STACKED = "cardStacked",
  CAROUSEL = "carousel",
  CHART = "chart",
  CHIP = "chip",
  COLOR_CHIP = "colorChip",
  COLOR_SPECIMEN = "colorSpecimen",
  COMBOBOX = "combobox",
  COMBOBOX_FIELD = "comboboxField",
  CONTAINER = "container",
  CTA = "cta",
  SUBSCRIBE_CTA = "subscribeCta",
  BOLD_CTA = "boldCta",
  JOIN_CTA = "joinCta",
  SOCIAL_PROOF_CTA = "socialProofCta",
  TOPBAR = "topbar",
  MEDIA_CARD = "mediaCard",
  NOTIFICATION_CARD = "notificationCard",
  PRICING_CARD = "pricingCard",
  PRODUCT_CARD = "productCard",
  PROFILE_CARD = "profileCard",
  PROGRESS = "progress",
  RESIZABLE = "resizable",
  SKELETON = "skeleton",
  SLIDER = "slider",
  STAT_CARD = "statCard",
  STEPPER = "stepper",
  CITE = "cite",
  DESCRIPTION_LIST = "descriptionList",
  EMPTY = "empty",
  PANEL = "panel",
  FIELDSET = "fieldset",
  FILTER_BAR = "filterBar",
  FOOTER = "footer",
  FORM_CONTROL = "formControl",
  FRAME = "frame",
  HEADER = "header",
  HR = "hr",
  ICON = "icon",
  IMAGE = "image",
  INPUT = "input",
  KBD = "kbd",
  LEGEND = "legend",
  LINK = "link",
  LIST = "list",
  ITEM = "item",
  LIST_STANDARD = "listStandard",
  LIST_ITEM = "listItem",
  MENU = "menu",
  MENU_ITEM = "menuItem",
  MESSAGE = "message",
  MASTER_DETAIL = "masterDetail",
  METRIC = "metric",
  NAV = "nav",
  OPTION_GROUP = "optionGroup",
  ORDINAL_CHIP = "ordinalChip",
  PAGINATION = "pagination",
  PROPERTY_GRID = "propertyGrid",
  PARAGRAPH = "paragraph",
  ORDINAL_SPECIMEN = "ordinalSpecimen",
  SANDBOX = "sandbox",
  SCREEN = "screen",
  THEME_SPEC = "themeSpec",
  SECTION = "section",
  SELECT = "select",
  SIDEBAR = "sidebar",
  SMALL_MULTIPLES = "smallMultiples",
  SOURCE = "source",
  TOGGLE_SWITCH = "toggleSwitch",
  TABLE = "table",
  TABLE_BODY = "tableBody",
  TABLE_DATA = "tableData",
  TABLE_GRID = "tableGrid",
  TABLE_HEAD = "tableHead",
  TABLE_HEADER = "tableHeader",
  TABLE_ROW_DATA = "tableRowData",
  TEXT = "text",
  TEXTAREA = "textarea",
  TOOLTIP = "tooltip",
  TRACK = "track",
  TYPE_SPECIMEN = "typeSpecimen",
  VIDEO = "video",
  WIDGET_TODO = "widgetTodo",
}

export const isComponentId = (id: string): id is ComponentId => {
  return Object.values(ComponentId).includes(id as ComponentId)
}
