/**
 * The component id union for the catalog. Each id matches a schema's `id` and a
 * `ComponentId` key. Keep this enum aligned with the schema files and
 * `packages/core/components/catalog`. To sync it after schema changes, invoke
 * `@components-catalog`.
 *
 * `ComponentId` stays an enum because it is part of the serialized workspace API.
 */
export enum ComponentId {
  AD_IAB = "adIab",
  AD_SOCIAL_MEDIA = "adSocialMedia",
  AVATAR = "avatar",
  BAR_BUTTONS = "barButtons",
  BAR_FOOTER = "barFooter",
  BAR_HEADER = "barHeader",
  BAR_NAVIGATION = "barNavigation",
  BAR_STATUS = "barStatus",
  BAR_TABS = "barTabs",
  BLOCKQUOTE = "blockquote",
  BOARD = "board",
  BUTTON = "button",
  CALENDAR = "calendar",
  CALLOUT = "callout",
  CARD_HORIZONTAL = "cardHorizontal",
  CARD_PRODUCT = "cardProduct",
  CARD_STACKED = "cardStacked",
  CHECKBOX = "checkbox",
  CHIP = "chip",
  CITE = "cite",
  CODEBLOCK = "codeblock",
  DESCRIPTION = "description",
  DESCRIPTION_DETAILS = "descriptionDetails",
  DESCRIPTION_LIST = "descriptionList",
  DESCRIPTION_TERM = "descriptionTerm",
  DISPLAY = "display",
  DIALOG = "dialog",
  FIELDSET = "fieldset",
  FIELDSET_CHECKBOXES = "fieldsetCheckboxes",
  FIELDSET_RADIOS = "fieldsetRadios",
  FOOTER = "footer",
  FORM_CONTROL = "formControl",
  FRAME = "frame",
  HEADER_ACTION = "headerAction",
  HEADER_CARD = "headerCard",
  HEADING = "heading",
  HR = "hr",
  ICON = "icon",
  IMAGE = "image",
  INPUT = "input",
  LABEL = "label",
  LEGEND = "legend",
  LINK = "link",
  LIST_CONTACTS = "listContacts",
  LIST_GRID = "listGrid",
  LIST_ITEM = "listItem",
  ITEM = "item",
  LIST_PRODUCTS = "listProducts",
  LIST_STANDARD = "listStandard",
  LIST_TODO = "listTodo",
  NAV = "nav",
  OPTION = "option",
  OPTION_GROUP = "optionGroup",
  ORDERED_LIST = "orderedList",
  RADIO = "radio",
  SCREEN = "screen",
  SECTION = "section",
  SELECT = "select",
  SIDEBAR = "sidebar",
  SOURCE = "source",
  SUBHEADING = "subheading",
  SUBTITLE = "subtitle",
  TABLE = "table",
  TABLE_DATA = "tableData",
  TABLE_HEADER = "tableHeader",
  TABLE_INPUT = "tableInput",
  TABLE_ROW_DATA = "tableRowData",
  TAGLINE = "tagline",
  TEXT = "text",
  TITLE = "title",
  TRACK = "track",
  TYPE_SPECIMEN = "typeSpecimen",
  UNORDERED_LIST = "unorderedList",
  VIDEO = "video",
  WIDGET_TODO = "widgetTodo",
}

export const isComponentId = (id: string): id is ComponentId => {
  return Object.values(ComponentId).includes(id as ComponentId)
}
