export const HEADER_HEIGHT = 52

export const PANEL_MIN_WIDTH = 300
export const PANEL_MIN_HEIGHT = 300
export const PANEL_INITIAL_WIDTH = 520
export const PANEL_INITIAL_HEIGHT = 520

export const PROPERTIES_PANEL_INITIAL_WIDTH = 320

export const SKETCH_PANEL_INITIAL_WIDTH = 680
export const SKETCH_PANEL_INITIAL_HEIGHT = 640

export const SUGGEST_PANEL_INITIAL_HEIGHT = 300
export const SUGGEST_PANEL_INITIAL_WIDTH = 680
