export type IconSetId = "google-material"

export const iconIds = [
  "__default__",
  "material-360",
  "material-accountCircle",
  "material-add",
  "material-addBox",
  "material-addBusiness",
  "material-addChart",
  "material-addCircle",
  "material-addComment",
  "material-addLocation",
  "material-addLocationAlt",
  "material-addRoad",
  "material-adfScanner",
  "material-agriculture",
  "material-airlineStops",
  "material-airlines",
  "material-alignHorizontalCenter",
  "material-alignHorizontalLeft",
  "material-alignHorizontalRight",
  "material-alignVerticalBottom",
  "material-alignVerticalCenter",
  "material-alignVerticalTop",
  "material-altRoute",
  "material-apps",
  "material-areaChart",
  "material-arrowBack",
  "material-arrowBackIosNew",
  "material-arrowCircleDown",
  "material-arrowCircleLeft",
  "material-arrowCircleRight",
  "material-arrowCircleUp",
  "material-arrowDownward",
  "material-arrowDropDown",
  "material-arrowDropDownCircle",
  "material-arrowDropUp",
  "material-arrowForward",
  "material-arrowForwardIos",
  "material-arrowLeft",
  "material-arrowOutward",
  "material-arrowRight",
  "material-arrowRightAlt",
  "material-arrowUpward",
  "material-assistantNavigation",
  "material-atm",
  "material-attachFile",
  "material-attachMoney",
  "material-attractions",
  "material-autoGraph",
  "material-autorenew",
  "material-backspace",
  "material-badge",
  "material-bakeryDining",
  "material-barChart",
  "material-battery0Bar",
  "material-batteryFullAlt",
  "material-batteryHoriz000",
  "material-batteryHoriz050",
  "material-batteryHoriz075",
  "material-batteryLow",
  "material-beenhere",
  "material-bikeScooter",
  "material-block",
  "material-bolt",
  "material-border",
  "material-borderAll",
  "material-borderBottom",
  "material-borderClear",
  "material-borderColor",
  "material-borderHorizontal",
  "material-borderInner",
  "material-borderLeft",
  "material-borderOuter",
  "material-borderRight",
  "material-borderStyle",
  "material-borderTop",
  "material-borderVertical",
  "material-breakfastDining",
  "material-browserNotSupported",
  "material-browserUpdated",
  "material-brunchDining",
  "material-bubbleChart",
  "material-busAlert",
  "material-cached",
  "material-cancel",
  "material-candlestickChart",
  "material-carCrash",
  "material-carRental",
  "material-carRepair",
  "material-cast",
  "material-castConnected",
  "material-castForEducation",
  "material-castle",
  "material-category",
  "material-celebration",
  "material-changeCircle",
  "material-check",
  "material-checkBox",
  "material-checkBoxOutlineBlank",
  "material-checkboxOff",
  "material-checkboxOn",
  "material-checklist",
  "material-checklistRtl",
  "material-chevronDoubleDown",
  "material-chevronDoubleLeft",
  "material-chevronDoubleP",
  "material-chevronDoubleRight",
  "material-chevronDown",
  "material-chevronLeft",
  "material-chevronP",
  "material-chevronRight",
  "material-church",
  "material-cleaningServices",
  "material-clearAll",
  "material-clip",
  "material-close",
  "material-closeFullscreen",
  "material-code",
  "material-color",
  "material-compareArrows",
  "material-compassCalibration",
  "material-computed",
  "material-computer",
  "material-connectedTv",
  "material-connectingAirports",
  "material-content",
  "material-corner",
  "material-createNewFolder",
  "material-crisisAlert",
  "material-cursor",
  "material-custom",
  "material-dataArray",
  "material-dataObject",
  "material-dataset",
  "material-delete",
  "material-deleteForever",
  "material-deleteSweep",
  "material-deliveryDining",
  "material-densityMedium",
  "material-departureBoard",
  "material-designServices",
  "material-desktopMac",
  "material-desktopWindows",
  "material-developerBoard",
  "material-developerBoardOff",
  "material-deviceCustom",
  "material-deviceDesktop",
  "material-deviceHub",
  "material-deviceLaptop",
  "material-deviceMobile",
  "material-deviceTV",
  "material-deviceTablet",
  "material-deviceUnknown",
  "material-deviceWatch",
  "material-devicesOther",
  "material-diamond",
  "material-dinnerDining",
  "material-directionLTR",
  "material-directionRTL",
  "material-directions",
  "material-directionsBike",
  "material-directionsBoat",
  "material-directionsBoatFilled",
  "material-directionsBus",
  "material-directionsBusFilled",
  "material-directionsCar",
  "material-directionsCarFilled",
  "material-directionsRailway",
  "material-directionsRailwayFilled",
  "material-directionsRun",
  "material-directionsSubway",
  "material-directionsSubwayFilled",
  "material-directionsTransit",
  "material-directionsTransitFilled",
  "material-directionsWalk",
  "material-disabledByDefault",
  "material-display",
  "material-doNotDisturbOn",
  "material-dock",
  "material-doneAll",
  "material-doneOutline",
  "material-doubleArrow",
  "material-download",
  "material-downloadDone",
  "material-downloadForOffline",
  "material-downloading",
  "material-dragHandle",
  "material-dragIndicator",
  "material-draw",
  "material-dryCleaning",
  "material-earbuds",
  "material-earbudsBattery",
  "material-editAttributes",
  "material-editLocation",
  "material-editLocationAlt",
  "material-editNote",
  "material-editRoad",
  "material-edited",
  "material-egg",
  "material-eggAlt",
  "material-electricBike",
  "material-electricCar",
  "material-electricMoped",
  "material-electricRickshaw",
  "material-electricScooter",
  "material-electricalServices",
  "material-emergency",
  "material-emergencyRecording",
  "material-emergencyShare",
  "material-empty",
  "material-evStation",
  "material-exitToApp",
  "material-expand",
  "material-expandCircleDown",
  "material-factory",
  "material-fastfood",
  "material-favorite",
  "material-festival",
  "material-fileOpen",
  "material-filterList",
  "material-fireHydrantAlt",
  "material-fireTruck",
  "material-firstPage",
  "material-fitHorizontal",
  "material-fitVertical",
  "material-flight",
  "material-flightClass",
  "material-font",
  "material-fontFamily",
  "material-fontLetterSpacing",
  "material-fontLineHeight",
  "material-fontSize",
  "material-fontTextAlignCenter",
  "material-fontTextAlignJustify",
  "material-fontTextAlignLeft",
  "material-fontTextAlignRight",
  "material-fontTextDecoration",
  "material-fontTextWrap",
  "material-fontWeight",
  "material-forest",
  "material-forkLeft",
  "material-forkRight",
  "material-formatAlignCenter",
  "material-formatAlignJustify",
  "material-formatAlignLeft",
  "material-formatAlignRight",
  "material-formatBold",
  "material-formatClear",
  "material-formatColorFill",
  "material-formatColorReset",
  "material-formatColorText",
  "material-formatIndentDecrease",
  "material-formatIndentIncrease",
  "material-formatItalic",
  "material-formatLineSpacing",
  "material-formatListBulleted",
  "material-formatListNumbered",
  "material-formatListNumberedRtl",
  "material-formatPaint",
  "material-formatQuote",
  "material-formatShapes",
  "material-formatSize",
  "material-formatStrikethrough",
  "material-formatTextdirectionLToR",
  "material-formatTextdirectionRToL",
  "material-formatUnderlined",
  "material-fort",
  "material-forward",
  "material-fullscreen",
  "material-fullscreenExit",
  "material-functions",
  "material-gamepad",
  "material-grade",
  "material-hail",
  "material-handyman",
  "material-hardware",
  "material-headphones",
  "material-headphonesBattery",
  "material-headset",
  "material-headsetMic",
  "material-headsetOff",
  "material-heartPlus",
  "material-height",
  "material-hexagon",
  "material-highlight",
  "material-home",
  "material-homeMax",
  "material-homeMini",
  "material-homeRepairService",
  "material-horizontalDistribute",
  "material-horizontalRule",
  "material-hotel",
  "material-hvac",
  "material-icecream",
  "material-iconFrame",
  "material-iconImage",
  "material-iconInput",
  "material-iconText",
  "material-image",
  "material-indeterminateCheckBox",
  "material-inputType",
  "material-insertChart",
  "material-insertChartOutlined",
  "material-insertComment",
  "material-insertDriveFile",
  "material-insertEmoticon",
  "material-insertInvitation",
  "material-insertLink",
  "material-insertPageBreak",
  "material-insertPhoto",
  "material-iosShare",
  "material-kebabDining",
  "material-key",
  "material-keyboard",
  "material-keyboardAlt",
  "material-keyboardArrowDown",
  "material-keyboardArrowLeft",
  "material-keyboardArrowRight",
  "material-keyboardArrowUp",
  "material-keyboardBackspace",
  "material-keyboardCapslock",
  "material-keyboardCommandKey",
  "material-keyboardControlKey",
  "material-keyboardDoubleArrowDown",
  "material-keyboardDoubleArrowLeft",
  "material-keyboardDoubleArrowRight",
  "material-keyboardDoubleArrowUp",
  "material-keyboardHide",
  "material-keyboardOptionKey",
  "material-keyboardReturn",
  "material-keyboardTab",
  "material-keyboardVoice",
  "material-laptop",
  "material-laptopChromebook",
  "material-laptopMac",
  "material-laptopWindows",
  "material-lastPage",
  "material-layers",
  "material-layersClear",
  "material-libraryAdd",
  "material-lineAxis",
  "material-linearScale",
  "material-liquor",
  "material-localActivity",
  "material-localAirport",
  "material-localAtm",
  "material-localBar",
  "material-localCafe",
  "material-localCarWash",
  "material-localConvenienceStore",
  "material-localDining",
  "material-localDrink",
  "material-localFireDepartment",
  "material-localFlorist",
  "material-localGasStation",
  "material-localGroceryStore",
  "material-localHospital",
  "material-localHotel",
  "material-localLaundryService",
  "material-localLibrary",
  "material-localMall",
  "material-localMovies",
  "material-localOffer",
  "material-localParking",
  "material-localPharmacy",
  "material-localPhone",
  "material-localPizza",
  "material-localPlay",
  "material-localPolice",
  "material-localPostOffice",
  "material-localPrintshop",
  "material-localSee",
  "material-localShipping",
  "material-localTaxi",
  "material-login",
  "material-logout",
  "material-lunchDining",
  "material-manageSearch",
  "material-map",
  "material-mapsUgc",
  "material-margin",
  "material-medicalInformation",
  "material-medicalServices",
  "material-memory",
  "material-menu",
  "material-menuBook",
  "material-menuOpen",
  "material-merge",
  "material-mergeType",
  "material-minorCrash",
  "material-minus",
  "material-miscellaneousServices",
  "material-mode",
  "material-modeComment",
  "material-modeEdit",
  "material-modeEditOutline",
  "material-modeOfTravel",
  "material-monetizationOn",
  "material-money",
  "material-moneyOff",
  "material-moneyOffCsred",
  "material-monitor",
  "material-moped",
  "material-more",
  "material-moreHoriz",
  "material-moreVert",
  "material-mosque",
  "material-mouse",
  "material-moveDown",
  "material-moveUp",
  "material-moving",
  "material-multilineChart",
  "material-multipleStop",
  "material-museum",
  "material-myLocation",
  "material-navigation",
  "material-nearMe",
  "material-nearMeDisabled",
  "material-nightlife",
  "material-noCrash",
  "material-noMeals",
  "material-noTransfer",
  "material-none",
  "material-notListedLocation",
  "material-notes",
  "material-numbers",
  "material-opacity",
  "material-openInFull",
  "material-openInNew",
  "material-openWith",
  "material-orientationHorizontal",
  "material-orientationVertical",
  "material-padding",
  "material-park",
  "material-pedalBike",
  "material-pentagon",
  "material-person",
  "material-personPin",
  "material-personPinCircle",
  "material-pestControl",
  "material-pestControlRodent",
  "material-phoneAndroid",
  "material-phoneIphone",
  "material-phonelink",
  "material-phonelinkOff",
  "material-pieChart",
  "material-pieChartOutline",
  "material-pinDrop",
  "material-place",
  "material-plumbing",
  "material-plus",
  "material-pointOfSale",
  "material-polyline",
  "material-postAdd",
  "material-powerInput",
  "material-preview",
  "material-publish",
  "material-queryStats",
  "material-questionMark",
  "material-radioButtonChecked",
  "material-radioButtonUnchecked",
  "material-radioOff",
  "material-radioOn",
  "material-railwayAlert",
  "material-ramenDining",
  "material-rampLeft",
  "material-rampRight",
  "material-rateReview",
  "material-rectangle",
  "material-redo",
  "material-refresh",
  "material-remove",
  "material-removeRoad",
  "material-reply",
  "material-restaurant",
  "material-restaurantMenu",
  "material-retry",
  "material-robot",
  "material-roundaboutLeft",
  "material-roundaboutRight",
  "material-route",
  "material-router",
  "material-runCircle",
  "material-safetyCheck",
  "material-sailing",
  "material-satellite",
  "material-scanner",
  "material-scatterPlot",
  "material-schema",
  "material-score",
  "material-screenRotationAlt",
  "material-search",
  "material-security",
  "material-send",
  "material-setMeal",
  "material-settings",
  "material-settingsApplications",
  "material-settingsBackupRestore",
  "material-shadow",
  "material-shapeLine",
  "material-share",
  "material-shoppingCartCheckout",
  "material-shortText",
  "material-showChart",
  "material-signalCellularAlt",
  "material-signpost",
  "material-simCard",
  "material-size",
  "material-smartDisplay",
  "material-smartScreen",
  "material-smartToy",
  "material-smartphone",
  "material-snowmobile",
  "material-sort",
  "material-sortByAlpha",
  "material-sos",
  "material-soupKitchen",
  "material-spaceBar",
  "material-speaker",
  "material-speakerGroup",
  "material-spread",
  "material-square",
  "material-stackedLineChart",
  "material-stadium",
  "material-star",
  "material-starBorder",
  "material-starBorderPurple500",
  "material-starHalf",
  "material-starOutline",
  "material-starPurple500",
  "material-start",
  "material-storeMallDirectory",
  "material-straight",
  "material-streetview",
  "material-strikethroughS",
  "material-subdirectoryArrowRight",
  "material-subscript",
  "material-subway",
  "material-superscript",
  "material-swapHoriz",
  "material-swapVert",
  "material-switchAccessShortcut",
  "material-synagogue",
  "material-sync",
  "material-syncAlt",
  "material-tableChart",
  "material-tableRows",
  "material-tablet",
  "material-tabletAndroid",
  "material-tabletMac",
  "material-takeoutDining",
  "material-taxiAlert",
  "material-templeBuddhist",
  "material-templeHindu",
  "material-terminal",
  "material-terrain",
  "material-textDecrease",
  "material-textFields",
  "material-textIncrease",
  "material-theaterComedy",
  "material-thumbDown",
  "material-thumbP",
  "material-ticket",
  "material-tireRepair",
  "material-title",
  "material-toggleOff",
  "material-toggleOn",
  "material-token",
  "material-toys",
  "material-traffic",
  "material-train",
  "material-tram",
  "material-transferWithinAStation",
  "material-transitEnterexit",
  "material-tripOrigin",
  "material-turnLeft",
  "material-turnRight",
  "material-turnSharpLeft",
  "material-turnSharpRight",
  "material-turnSlightLeft",
  "material-turnSlightRight",
  "material-tv",
  "material-twoWheeler",
  "material-typeSpecimen",
  "material-uTurnLeft",
  "material-uTurnRight",
  "material-undo",
  "material-unfoldLess",
  "material-unfoldMore",
  "material-upload",
  "material-vector",
  "material-verticalAlignBottom",
  "material-verticalAlignCenter",
  "material-verticalAlignTop",
  "material-verticalDistribute",
  "material-videogameAsset",
  "material-videogameAssetOff",
  "material-viewTimeline",
  "material-visibilityOff",
  "material-volunteerActivism",
  "material-warehouse",
  "material-watch",
  "material-watchOff",
  "material-wifi",
  "material-wineBar",
  "material-wrapText",
  "material-wrongLocation",
  "material-x",
  "material-zoomIn",
  "material-zoomInMap",
  "material-zoomOut",
  "material-zoomOutMap",
  "missing",
  "seldon-ai",
  "seldon-alignBottom",
  "seldon-alignLeft",
  "seldon-alignRight",
  "seldon-alignTop",
  "seldon-angle",
  "seldon-background",
  "seldon-codeCube",
  "seldon-component",
  "seldon-componentDefault",
  "seldon-componentVariant",
  "seldon-frame",
  "seldon-frameBackground",
  "seldon-frameColumns",
  "seldon-frameRows",
  "seldon-gap",
  "seldon-gradient",
  "seldon-hexagon",
  "seldon-hidden",
  "seldon-icon",
  "seldon-image",
  "seldon-imageFit",
  "seldon-input",
  "seldon-lines",
  "seldon-positionBottom",
  "seldon-positionBottomLeft",
  "seldon-positionBottomRight",
  "seldon-positionCenter",
  "seldon-positionLeft",
  "seldon-positionRight",
  "seldon-positionTop",
  "seldon-positionTopLeft",
  "seldon-positionTopRight",
  "seldon-reset",
  "seldon-screen",
  "seldon-sketchCircle",
  "seldon-sketchPencil",
  "seldon-sketchRectangle",
  "seldon-sketchText",
  "seldon-step",
  "seldon-stub",
  "seldon-swatch",
  "seldon-text",
  "seldon-theme",
  "seldon-toolArrow",
  "seldon-toolComponent",
  "seldon-toolImageAi",
  "seldon-toolSketch",
  "seldon-valuePx",
  "seldon-valueRem",
  "social-facebook",
  "social-youtube",
  "social-whatsapp",
  "social-instagram",
  "social-tiktok",
  "social-twitter",
  "social-linkedin",
  "social-snapchat",
  "social-pinterest",
  "social-reddit",
  "social-telegram",
  "social-discord",
  "social-twitch",
  "social-github",
  "social-spotify",
  "social-tumblr",
  "social-vimeo",
  "social-flickr",
  "social-medium",
  "social-quora",
] as const

export type IconId = (typeof iconIds)[number]

export const iconLabels: Record<IconId, string> = {
  __default__: "Default",
  "material-360": "360",
  "material-accountCircle": "Account Circle",
  "material-add": "Add",
  "material-addBox": "Add Box",
  "material-addBusiness": "Add Business",
  "material-addChart": "Add Chart",
  "material-addCircle": "Add Circle",
  "material-addComment": "Add Comment",
  "material-addLocation": "Add Location",
  "material-addLocationAlt": "Add Location Alt",
  "material-addRoad": "Add Road",
  "material-adfScanner": "Adf Scanner",
  "material-agriculture": "Agriculture",
  "material-airlineStops": "Airline Stops",
  "material-airlines": "Airlines",
  "material-alignHorizontalCenter": "Align Horizontal Center",
  "material-alignHorizontalLeft": "Align Horizontal Left",
  "material-alignHorizontalRight": "Align Horizontal Right",
  "material-alignVerticalBottom": "Align Vertical Bottom",
  "material-alignVerticalCenter": "Align Vertical Center",
  "material-alignVerticalTop": "Align Vertical Top",
  "material-altRoute": "Alt Route",
  "material-apps": "Apps",
  "material-areaChart": "Area Chart",
  "material-arrowBack": "Arrow Back",
  "material-arrowBackIosNew": "Arrow Back Ios New",
  "material-arrowCircleDown": "Arrow Circle Down",
  "material-arrowCircleLeft": "Arrow Circle Left",
  "material-arrowCircleRight": "Arrow Circle Right",
  "material-arrowCircleUp": "Arrow Circle Up",
  "material-arrowDownward": "Arrow Downward",
  "material-arrowDropDown": "Arrow Drop Down",
  "material-arrowDropDownCircle": "Arrow Drop Down Circle",
  "material-arrowDropUp": "Arrow Drop Up",
  "material-arrowForward": "Arrow Forward",
  "material-arrowForwardIos": "Arrow Forward Ios",
  "material-arrowLeft": "Arrow Left",
  "material-arrowOutward": "Arrow Outward",
  "material-arrowRight": "Arrow Right",
  "material-arrowRightAlt": "Arrow Right Alt",
  "material-arrowUpward": "Arrow Upward",
  "material-assistantNavigation": "Assistant Navigation",
  "material-atm": "Atm",
  "material-attachFile": "Attach File",
  "material-attachMoney": "Attach Money",
  "material-attractions": "Attractions",
  "material-autoGraph": "Auto Graph",
  "material-autorenew": "Autorenew",
  "material-backspace": "Backspace",
  "material-badge": "Badge",
  "material-bakeryDining": "Bakery Dining",
  "material-barChart": "Bar Chart",
  "material-battery0Bar": "Battery0 Bar",
  "material-batteryFullAlt": "Battery Full Alt",
  "material-batteryHoriz000": "Battery Horiz000",
  "material-batteryHoriz050": "Battery Horiz050",
  "material-batteryHoriz075": "Battery Horiz075",
  "material-batteryLow": "Battery Low",
  "material-beenhere": "Beenhere",
  "material-bikeScooter": "Bike Scooter",
  "material-block": "Block",
  "material-bolt": "Bolt",
  "material-border": "Border",
  "material-borderAll": "Border All",
  "material-borderBottom": "Border Bottom",
  "material-borderClear": "Border Clear",
  "material-borderColor": "Border Color",
  "material-borderHorizontal": "Border Horizontal",
  "material-borderInner": "Border Inner",
  "material-borderLeft": "Border Left",
  "material-borderOuter": "Border Outer",
  "material-borderRight": "Border Right",
  "material-borderStyle": "Border Style",
  "material-borderTop": "Border Top",
  "material-borderVertical": "Border Vertical",
  "material-breakfastDining": "Breakfast Dining",
  "material-browserNotSupported": "Browser Not Supported",
  "material-browserUpdated": "Browser Updated",
  "material-brunchDining": "Brunch Dining",
  "material-bubbleChart": "Bubble Chart",
  "material-busAlert": "Bus Alert",
  "material-cached": "Cached",
  "material-cancel": "Cancel",
  "material-candlestickChart": "Candlestick Chart",
  "material-carCrash": "Car Crash",
  "material-carRental": "Car Rental",
  "material-carRepair": "Car Repair",
  "material-cast": "Cast",
  "material-castConnected": "Cast Connected",
  "material-castForEducation": "Cast For Education",
  "material-castle": "Castle",
  "material-category": "Category",
  "material-celebration": "Celebration",
  "material-changeCircle": "Change Circle",
  "material-check": "Check",
  "material-checkBox": "Check Box",
  "material-checkBoxOutlineBlank": "Check Box Outline Blank",
  "material-checkboxOff": "Checkbox Off",
  "material-checkboxOn": "Checkbox On",
  "material-checklist": "Checklist",
  "material-checklistRtl": "Checklist Rtl",
  "material-chevronDoubleDown": "Chevron Double Down",
  "material-chevronDoubleLeft": "Chevron Double Left",
  "material-chevronDoubleP": "Chevron Double P",
  "material-chevronDoubleRight": "Chevron Double Right",
  "material-chevronDown": "Chevron Down",
  "material-chevronLeft": "Chevron Left",
  "material-chevronP": "Chevron P",
  "material-chevronRight": "Chevron Right",
  "material-church": "Church",
  "material-cleaningServices": "Cleaning Services",
  "material-clearAll": "Clear All",
  "material-clip": "Clip",
  "material-close": "Close",
  "material-closeFullscreen": "Close Fullscreen",
  "material-code": "Code",
  "material-color": "Color",
  "material-compareArrows": "Compare Arrows",
  "material-compassCalibration": "Compass Calibration",
  "material-computed": "Computed",
  "material-computer": "Computer",
  "material-connectedTv": "Connected Tv",
  "material-connectingAirports": "Connecting Airports",
  "material-content": "Content",
  "material-corner": "Corner",
  "material-createNewFolder": "Create New Folder",
  "material-crisisAlert": "Crisis Alert",
  "material-cursor": "Cursor",
  "material-custom": "Custom",
  "material-dataArray": "Data Array",
  "material-dataObject": "Data Object",
  "material-dataset": "Dataset",
  "material-delete": "Delete",
  "material-deleteForever": "Delete Forever",
  "material-deleteSweep": "Delete Sweep",
  "material-deliveryDining": "Delivery Dining",
  "material-densityMedium": "Density Medium",
  "material-departureBoard": "Departure Board",
  "material-designServices": "Design Services",
  "material-desktopMac": "Desktop Mac",
  "material-desktopWindows": "Desktop Windows",
  "material-developerBoard": "Developer Board",
  "material-developerBoardOff": "Developer Board Off",
  "material-deviceCustom": "Device Custom",
  "material-deviceDesktop": "Device Desktop",
  "material-deviceHub": "Device Hub",
  "material-deviceLaptop": "Device Laptop",
  "material-deviceMobile": "Device Mobile",
  "material-deviceTV": "Device T V",
  "material-deviceTablet": "Device Tablet",
  "material-deviceUnknown": "Device Unknown",
  "material-deviceWatch": "Device Watch",
  "material-devicesOther": "Devices Other",
  "material-diamond": "Diamond",
  "material-dinnerDining": "Dinner Dining",
  "material-directionLTR": "Direction L T R",
  "material-directionRTL": "Direction R T L",
  "material-directions": "Directions",
  "material-directionsBike": "Directions Bike",
  "material-directionsBoat": "Directions Boat",
  "material-directionsBoatFilled": "Directions Boat Filled",
  "material-directionsBus": "Directions Bus",
  "material-directionsBusFilled": "Directions Bus Filled",
  "material-directionsCar": "Directions Car",
  "material-directionsCarFilled": "Directions Car Filled",
  "material-directionsRailway": "Directions Railway",
  "material-directionsRailwayFilled": "Directions Railway Filled",
  "material-directionsRun": "Directions Run",
  "material-directionsSubway": "Directions Subway",
  "material-directionsSubwayFilled": "Directions Subway Filled",
  "material-directionsTransit": "Directions Transit",
  "material-directionsTransitFilled": "Directions Transit Filled",
  "material-directionsWalk": "Directions Walk",
  "material-disabledByDefault": "Disabled By Default",
  "material-display": "Display",
  "material-doNotDisturbOn": "Do Not Disturb On",
  "material-dock": "Dock",
  "material-doneAll": "Done All",
  "material-doneOutline": "Done Outline",
  "material-doubleArrow": "Double Arrow",
  "material-download": "Download",
  "material-downloadDone": "Download Done",
  "material-downloadForOffline": "Download For Offline",
  "material-downloading": "Downloading",
  "material-dragHandle": "Drag Handle",
  "material-dragIndicator": "Drag Indicator",
  "material-draw": "Draw",
  "material-dryCleaning": "Dry Cleaning",
  "material-earbuds": "Earbuds",
  "material-earbudsBattery": "Earbuds Battery",
  "material-editAttributes": "Edit Attributes",
  "material-editLocation": "Edit Location",
  "material-editLocationAlt": "Edit Location Alt",
  "material-editNote": "Edit Note",
  "material-editRoad": "Edit Road",
  "material-edited": "Edited",
  "material-egg": "Egg",
  "material-eggAlt": "Egg Alt",
  "material-electricBike": "Electric Bike",
  "material-electricCar": "Electric Car",
  "material-electricMoped": "Electric Moped",
  "material-electricRickshaw": "Electric Rickshaw",
  "material-electricScooter": "Electric Scooter",
  "material-electricalServices": "Electrical Services",
  "material-emergency": "Emergency",
  "material-emergencyRecording": "Emergency Recording",
  "material-emergencyShare": "Emergency Share",
  "material-empty": "Empty",
  "material-evStation": "Ev Station",
  "material-exitToApp": "Exit To App",
  "material-expand": "Expand",
  "material-expandCircleDown": "Expand Circle Down",
  "material-factory": "Factory",
  "material-fastfood": "Fastfood",
  "material-favorite": "Favorite",
  "material-festival": "Festival",
  "material-fileOpen": "File Open",
  "material-filterList": "Filter List",
  "material-fireHydrantAlt": "Fire Hydrant Alt",
  "material-fireTruck": "Fire Truck",
  "material-firstPage": "First Page",
  "material-fitHorizontal": "Fit Horizontal",
  "material-fitVertical": "Fit Vertical",
  "material-flight": "Flight",
  "material-flightClass": "Flight Class",
  "material-font": "Font",
  "material-fontFamily": "Font Family",
  "material-fontLetterSpacing": "Font Letter Spacing",
  "material-fontLineHeight": "Font Line Height",
  "material-fontSize": "Font Size",
  "material-fontTextAlignCenter": "Font Text Align Center",
  "material-fontTextAlignJustify": "Font Text Align Justify",
  "material-fontTextAlignLeft": "Font Text Align Left",
  "material-fontTextAlignRight": "Font Text Align Right",
  "material-fontTextDecoration": "Font Text Decoration",
  "material-fontTextWrap": "Font Text Wrap",
  "material-fontWeight": "Font Weight",
  "material-forest": "Forest",
  "material-forkLeft": "Fork Left",
  "material-forkRight": "Fork Right",
  "material-formatAlignCenter": "Format Align Center",
  "material-formatAlignJustify": "Format Align Justify",
  "material-formatAlignLeft": "Format Align Left",
  "material-formatAlignRight": "Format Align Right",
  "material-formatBold": "Format Bold",
  "material-formatClear": "Format Clear",
  "material-formatColorFill": "Format Color Fill",
  "material-formatColorReset": "Format Color Reset",
  "material-formatColorText": "Format Color Text",
  "material-formatIndentDecrease": "Format Indent Decrease",
  "material-formatIndentIncrease": "Format Indent Increase",
  "material-formatItalic": "Format Italic",
  "material-formatLineSpacing": "Format Line Spacing",
  "material-formatListBulleted": "Format List Bulleted",
  "material-formatListNumbered": "Format List Numbered",
  "material-formatListNumberedRtl": "Format List Numbered Rtl",
  "material-formatPaint": "Format Paint",
  "material-formatQuote": "Format Quote",
  "material-formatShapes": "Format Shapes",
  "material-formatSize": "Format Size",
  "material-formatStrikethrough": "Format Strikethrough",
  "material-formatTextdirectionLToR": "Format Textdirection L To R",
  "material-formatTextdirectionRToL": "Format Textdirection R To L",
  "material-formatUnderlined": "Format Underlined",
  "material-fort": "Fort",
  "material-forward": "Forward",
  "material-fullscreen": "Fullscreen",
  "material-fullscreenExit": "Fullscreen Exit",
  "material-functions": "Functions",
  "material-gamepad": "Gamepad",
  "material-grade": "Grade",
  "material-hail": "Hail",
  "material-handyman": "Handyman",
  "material-hardware": "Hardware",
  "material-headphones": "Headphones",
  "material-headphonesBattery": "Headphones Battery",
  "material-headset": "Headset",
  "material-headsetMic": "Headset Mic",
  "material-headsetOff": "Headset Off",
  "material-heartPlus": "Heart Plus",
  "material-height": "Height",
  "material-hexagon": "Hexagon",
  "material-highlight": "Highlight",
  "material-home": "Home",
  "material-homeMax": "Home Max",
  "material-homeMini": "Home Mini",
  "material-homeRepairService": "Home Repair Service",
  "material-horizontalDistribute": "Horizontal Distribute",
  "material-horizontalRule": "Horizontal Rule",
  "material-hotel": "Hotel",
  "material-hvac": "Hvac",
  "material-icecream": "Icecream",
  "material-iconFrame": "Icon Frame",
  "material-iconImage": "Icon Image",
  "material-iconInput": "Icon Input",
  "material-iconText": "Icon Text",
  "material-image": "Image",
  "material-indeterminateCheckBox": "Indeterminate Check Box",
  "material-inputType": "Input Type",
  "material-insertChart": "Insert Chart",
  "material-insertChartOutlined": "Insert Chart Outlined",
  "material-insertComment": "Insert Comment",
  "material-insertDriveFile": "Insert Drive File",
  "material-insertEmoticon": "Insert Emoticon",
  "material-insertInvitation": "Insert Invitation",
  "material-insertLink": "Insert Link",
  "material-insertPageBreak": "Insert Page Break",
  "material-insertPhoto": "Insert Photo",
  "material-iosShare": "Ios Share",
  "material-kebabDining": "Kebab Dining",
  "material-key": "Key",
  "material-keyboard": "Keyboard",
  "material-keyboardAlt": "Keyboard Alt",
  "material-keyboardArrowDown": "Keyboard Arrow Down",
  "material-keyboardArrowLeft": "Keyboard Arrow Left",
  "material-keyboardArrowRight": "Keyboard Arrow Right",
  "material-keyboardArrowUp": "Keyboard Arrow Up",
  "material-keyboardBackspace": "Keyboard Backspace",
  "material-keyboardCapslock": "Keyboard Capslock",
  "material-keyboardCommandKey": "Keyboard Command Key",
  "material-keyboardControlKey": "Keyboard Control Key",
  "material-keyboardDoubleArrowDown": "Keyboard Double Arrow Down",
  "material-keyboardDoubleArrowLeft": "Keyboard Double Arrow Left",
  "material-keyboardDoubleArrowRight": "Keyboard Double Arrow Right",
  "material-keyboardDoubleArrowUp": "Keyboard Double Arrow Up",
  "material-keyboardHide": "Keyboard Hide",
  "material-keyboardOptionKey": "Keyboard Option Key",
  "material-keyboardReturn": "Keyboard Return",
  "material-keyboardTab": "Keyboard Tab",
  "material-keyboardVoice": "Keyboard Voice",
  "material-laptop": "Laptop",
  "material-laptopChromebook": "Laptop Chromebook",
  "material-laptopMac": "Laptop Mac",
  "material-laptopWindows": "Laptop Windows",
  "material-lastPage": "Last Page",
  "material-layers": "Layers",
  "material-layersClear": "Layers Clear",
  "material-libraryAdd": "Library Add",
  "material-lineAxis": "Line Axis",
  "material-linearScale": "Linear Scale",
  "material-liquor": "Liquor",
  "material-localActivity": "Local Activity",
  "material-localAirport": "Local Airport",
  "material-localAtm": "Local Atm",
  "material-localBar": "Local Bar",
  "material-localCafe": "Local Cafe",
  "material-localCarWash": "Local Car Wash",
  "material-localConvenienceStore": "Local Convenience Store",
  "material-localDining": "Local Dining",
  "material-localDrink": "Local Drink",
  "material-localFireDepartment": "Local Fire Department",
  "material-localFlorist": "Local Florist",
  "material-localGasStation": "Local Gas Station",
  "material-localGroceryStore": "Local Grocery Store",
  "material-localHospital": "Local Hospital",
  "material-localHotel": "Local Hotel",
  "material-localLaundryService": "Local Laundry Service",
  "material-localLibrary": "Local Library",
  "material-localMall": "Local Mall",
  "material-localMovies": "Local Movies",
  "material-localOffer": "Local Offer",
  "material-localParking": "Local Parking",
  "material-localPharmacy": "Local Pharmacy",
  "material-localPhone": "Local Phone",
  "material-localPizza": "Local Pizza",
  "material-localPlay": "Local Play",
  "material-localPolice": "Local Police",
  "material-localPostOffice": "Local Post Office",
  "material-localPrintshop": "Local Printshop",
  "material-localSee": "Local See",
  "material-localShipping": "Local Shipping",
  "material-localTaxi": "Local Taxi",
  "material-login": "Login",
  "material-logout": "Logout",
  "material-lunchDining": "Lunch Dining",
  "material-manageSearch": "Manage Search",
  "material-map": "Map",
  "material-mapsUgc": "Maps Ugc",
  "material-margin": "Margin",
  "material-medicalInformation": "Medical Information",
  "material-medicalServices": "Medical Services",
  "material-memory": "Memory",
  "material-menu": "Menu",
  "material-menuBook": "Menu Book",
  "material-menuOpen": "Menu Open",
  "material-merge": "Merge",
  "material-mergeType": "Merge Type",
  "material-minorCrash": "Minor Crash",
  "material-minus": "Minus",
  "material-miscellaneousServices": "Miscellaneous Services",
  "material-mode": "Mode",
  "material-modeComment": "Mode Comment",
  "material-modeEdit": "Mode Edit",
  "material-modeEditOutline": "Mode Edit Outline",
  "material-modeOfTravel": "Mode Of Travel",
  "material-monetizationOn": "Monetization On",
  "material-money": "Money",
  "material-moneyOff": "Money Off",
  "material-moneyOffCsred": "Money Off Csred",
  "material-monitor": "Monitor",
  "material-moped": "Moped",
  "material-more": "More",
  "material-moreHoriz": "More Horiz",
  "material-moreVert": "More Vert",
  "material-mosque": "Mosque",
  "material-mouse": "Mouse",
  "material-moveDown": "Move Down",
  "material-moveUp": "Move Up",
  "material-moving": "Moving",
  "material-multilineChart": "Multiline Chart",
  "material-multipleStop": "Multiple Stop",
  "material-museum": "Museum",
  "material-myLocation": "My Location",
  "material-navigation": "Navigation",
  "material-nearMe": "Near Me",
  "material-nearMeDisabled": "Near Me Disabled",
  "material-nightlife": "Nightlife",
  "material-noCrash": "No Crash",
  "material-noMeals": "No Meals",
  "material-noTransfer": "No Transfer",
  "material-none": "None",
  "material-notListedLocation": "Not Listed Location",
  "material-notes": "Notes",
  "material-numbers": "Numbers",
  "material-opacity": "Opacity",
  "material-openInFull": "Open In Full",
  "material-openInNew": "Open In New",
  "material-openWith": "Open With",
  "material-orientationHorizontal": "Orientation Horizontal",
  "material-orientationVertical": "Orientation Vertical",
  "material-padding": "Padding",
  "material-park": "Park",
  "material-pedalBike": "Pedal Bike",
  "material-pentagon": "Pentagon",
  "material-person": "Person",
  "material-personPin": "Person Pin",
  "material-personPinCircle": "Person Pin Circle",
  "material-pestControl": "Pest Control",
  "material-pestControlRodent": "Pest Control Rodent",
  "material-phoneAndroid": "Phone Android",
  "material-phoneIphone": "Phone Iphone",
  "material-phonelink": "Phonelink",
  "material-phonelinkOff": "Phonelink Off",
  "material-pieChart": "Pie Chart",
  "material-pieChartOutline": "Pie Chart Outline",
  "material-pinDrop": "Pin Drop",
  "material-place": "Place",
  "material-plumbing": "Plumbing",
  "material-plus": "Plus",
  "material-pointOfSale": "Point Of Sale",
  "material-polyline": "Polyline",
  "material-postAdd": "Post Add",
  "material-powerInput": "Power Input",
  "material-preview": "Preview",
  "material-publish": "Publish",
  "material-queryStats": "Query Stats",
  "material-questionMark": "Question Mark",
  "material-radioButtonChecked": "Radio Button Checked",
  "material-radioButtonUnchecked": "Radio Button Unchecked",
  "material-radioOff": "Radio Off",
  "material-radioOn": "Radio On",
  "material-railwayAlert": "Railway Alert",
  "material-ramenDining": "Ramen Dining",
  "material-rampLeft": "Ramp Left",
  "material-rampRight": "Ramp Right",
  "material-rateReview": "Rate Review",
  "material-rectangle": "Rectangle",
  "material-redo": "Redo",
  "material-refresh": "Refresh",
  "material-remove": "Remove",
  "material-removeRoad": "Remove Road",
  "material-reply": "Reply",
  "material-restaurant": "Restaurant",
  "material-restaurantMenu": "Restaurant Menu",
  "material-retry": "Retry",
  "material-robot": "Robot",
  "material-roundaboutLeft": "Roundabout Left",
  "material-roundaboutRight": "Roundabout Right",
  "material-route": "Route",
  "material-router": "Router",
  "material-runCircle": "Run Circle",
  "material-safetyCheck": "Safety Check",
  "material-sailing": "Sailing",
  "material-satellite": "Satellite",
  "material-scanner": "Scanner",
  "material-scatterPlot": "Scatter Plot",
  "material-schema": "Schema",
  "material-score": "Score",
  "material-screenRotationAlt": "Screen Rotation Alt",
  "material-search": "Search",
  "material-security": "Security",
  "material-send": "Send",
  "material-setMeal": "Set Meal",
  "material-settings": "Settings",
  "material-settingsApplications": "Settings Applications",
  "material-settingsBackupRestore": "Settings Backup Restore",
  "material-shadow": "Shadow",
  "material-shapeLine": "Shape Line",
  "material-share": "Share",
  "material-shoppingCartCheckout": "Shopping Cart Checkout",
  "material-shortText": "Short Text",
  "material-showChart": "Show Chart",
  "material-signalCellularAlt": "Signal Cellular Alt",
  "material-signpost": "Signpost",
  "material-simCard": "Sim Card",
  "material-size": "Size",
  "material-smartDisplay": "Smart Display",
  "material-smartScreen": "Smart Screen",
  "material-smartToy": "Smart Toy",
  "material-smartphone": "Smartphone",
  "material-snowmobile": "Snowmobile",
  "material-sort": "Sort",
  "material-sortByAlpha": "Sort By Alpha",
  "material-sos": "Sos",
  "material-soupKitchen": "Soup Kitchen",
  "material-spaceBar": "Space Bar",
  "material-speaker": "Speaker",
  "material-speakerGroup": "Speaker Group",
  "material-spread": "Spread",
  "material-square": "Square",
  "material-stackedLineChart": "Stacked Line Chart",
  "material-stadium": "Stadium",
  "material-star": "Star",
  "material-starBorder": "Star Border",
  "material-starBorderPurple500": "Star Border Purple500",
  "material-starHalf": "Star Half",
  "material-starOutline": "Star Outline",
  "material-starPurple500": "Star Purple500",
  "material-start": "Start",
  "material-storeMallDirectory": "Store Mall Directory",
  "material-straight": "Straight",
  "material-streetview": "Streetview",
  "material-strikethroughS": "Strikethrough S",
  "material-subdirectoryArrowRight": "Subdirectory Arrow Right",
  "material-subscript": "Subscript",
  "material-subway": "Subway",
  "material-superscript": "Superscript",
  "material-swapHoriz": "Swap Horiz",
  "material-swapVert": "Swap Vert",
  "material-switchAccessShortcut": "Switch Access Shortcut",
  "material-synagogue": "Synagogue",
  "material-sync": "Sync",
  "material-syncAlt": "Sync Alt",
  "material-tableChart": "Table Chart",
  "material-tableRows": "Table Rows",
  "material-tablet": "Tablet",
  "material-tabletAndroid": "Tablet Android",
  "material-tabletMac": "Tablet Mac",
  "material-takeoutDining": "Takeout Dining",
  "material-taxiAlert": "Taxi Alert",
  "material-templeBuddhist": "Temple Buddhist",
  "material-templeHindu": "Temple Hindu",
  "material-terminal": "Terminal",
  "material-terrain": "Terrain",
  "material-textDecrease": "Text Decrease",
  "material-textFields": "Text Fields",
  "material-textIncrease": "Text Increase",
  "material-theaterComedy": "Theater Comedy",
  "material-thumbDown": "Thumb Down",
  "material-thumbP": "Thumb P",
  "material-ticket": "Ticket",
  "material-tireRepair": "Tire Repair",
  "material-title": "Title",
  "material-toggleOff": "Toggle Off",
  "material-toggleOn": "Toggle On",
  "material-token": "Token",
  "material-toys": "Toys",
  "material-traffic": "Traffic",
  "material-train": "Train",
  "material-tram": "Tram",
  "material-transferWithinAStation": "Transfer Within A Station",
  "material-transitEnterexit": "Transit Enterexit",
  "material-tripOrigin": "Trip Origin",
  "material-turnLeft": "Turn Left",
  "material-turnRight": "Turn Right",
  "material-turnSharpLeft": "Turn Sharp Left",
  "material-turnSharpRight": "Turn Sharp Right",
  "material-turnSlightLeft": "Turn Slight Left",
  "material-turnSlightRight": "Turn Slight Right",
  "material-tv": "Tv",
  "material-twoWheeler": "Two Wheeler",
  "material-typeSpecimen": "Type Specimen",
  "material-uTurnLeft": "U Turn Left",
  "material-uTurnRight": "U Turn Right",
  "material-undo": "Undo",
  "material-unfoldLess": "Unfold Less",
  "material-unfoldMore": "Unfold More",
  "material-upload": "Upload",
  "material-vector": "Vector",
  "material-verticalAlignBottom": "Vertical Align Bottom",
  "material-verticalAlignCenter": "Vertical Align Center",
  "material-verticalAlignTop": "Vertical Align Top",
  "material-verticalDistribute": "Vertical Distribute",
  "material-videogameAsset": "Videogame Asset",
  "material-videogameAssetOff": "Videogame Asset Off",
  "material-viewTimeline": "View Timeline",
  "material-visibilityOff": "Visibility Off",
  "material-volunteerActivism": "Volunteer Activism",
  "material-warehouse": "Warehouse",
  "material-watch": "Watch",
  "material-watchOff": "Watch Off",
  "material-wifi": "Wifi",
  "material-wineBar": "Wine Bar",
  "material-wrapText": "Wrap Text",
  "material-wrongLocation": "Wrong Location",
  "material-x": "X",
  "material-zoomIn": "Zoom In",
  "material-zoomInMap": "Zoom In Map",
  "material-zoomOut": "Zoom Out",
  "material-zoomOutMap": "Zoom Out Map",
  missing: "Missing",
  "seldon-ai": "Seldon - Ai",
  "seldon-alignBottom": "Seldon - Align Bottom",
  "seldon-alignLeft": "Seldon - Align Left",
  "seldon-alignRight": "Seldon - Align Right",
  "seldon-alignTop": "Seldon - Align Top",
  "seldon-angle": "Seldon - Angle",
  "seldon-background": "Seldon - Background",
  "seldon-codeCube": "Seldon - Code Cube",
  "seldon-component": "Seldon - Component",
  "seldon-componentDefault": "Seldon - Component Default",
  "seldon-componentVariant": "Seldon - Component Variant",
  "seldon-frame": "Seldon - Frame",
  "seldon-frameBackground": "Seldon - Frame Background",
  "seldon-frameColumns": "Seldon - Frame Columns",
  "seldon-frameRows": "Seldon - Frame Rows",
  "seldon-gap": "Seldon - Gap",
  "seldon-gradient": "Seldon - Gradient",
  "seldon-hexagon": "Seldon - Hexagon",
  "seldon-hidden": "Seldon - Hidden",
  "seldon-icon": "Seldon - Icon",
  "seldon-image": "Seldon - Image",
  "seldon-imageFit": "Seldon - Image Fit",
  "seldon-input": "Seldon - Input",
  "seldon-lines": "Seldon - Lines",
  "seldon-positionBottom": "Seldon - Position Bottom",
  "seldon-positionBottomLeft": "Seldon - Position Bottom Left",
  "seldon-positionBottomRight": "Seldon - Position Bottom Right",
  "seldon-positionCenter": "Seldon - Position Center",
  "seldon-positionLeft": "Seldon - Position Left",
  "seldon-positionRight": "Seldon - Position Right",
  "seldon-positionTop": "Seldon - Position Top",
  "seldon-positionTopLeft": "Seldon - Position Top Left",
  "seldon-positionTopRight": "Seldon - Position Top Right",
  "seldon-reset": "Seldon - Reset",
  "seldon-screen": "Seldon - Screen",
  "seldon-sketchCircle": "Seldon - Sketch Circle",
  "seldon-sketchPencil": "Seldon - Sketch Pencil",
  "seldon-sketchRectangle": "Seldon - Sketch Rectangle",
  "seldon-sketchText": "Seldon - Sketch Text",
  "seldon-step": "Seldon - Step",
  "seldon-stub": "Seldon - Stub",
  "seldon-swatch": "Seldon - Swatch",
  "seldon-text": "Seldon - Text",
  "seldon-theme": "Seldon - Theme",
  "seldon-toolArrow": "Seldon - Tool Arrow",
  "seldon-toolComponent": "Seldon - Tool Component",
  "seldon-toolImageAi": "Seldon - Tool Image A I",
  "seldon-toolSketch": "Seldon - Tool Sketch",
  "seldon-valuePx": "Seldon - Value Px",
  "seldon-valueRem": "Seldon - Value Rem",
  "social-facebook": "Social - Facebook",
  "social-youtube": "Social - YouTube",
  "social-whatsapp": "Social - WhatsApp",
  "social-instagram": "Social - Instagram",
  "social-tiktok": "Social - TikTok",
  "social-twitter": "Social - Twitter",
  "social-linkedin": "Social - LinkedIn",
  "social-snapchat": "Social - Snapchat",
  "social-pinterest": "Social - Pinterest",
  "social-reddit": "Social - Reddit",
  "social-telegram": "Social - Telegram",
  "social-discord": "Social - Discord",
  "social-twitch": "Social - Twitch",
  "social-github": "Social - GitHub",
  "social-spotify": "Social - Spotify",
  "social-tumblr": "Social - Tumblr",
  "social-vimeo": "Social - Vimeo",
  "social-flickr": "Social - Flickr",
  "social-medium": "Social - Medium",
  "social-quora": "Social - Quora",
}

export const defaultIconId = "__default__"
