/**
 * The `@seldon-generated` ownership marker.
 *
 * The token string is FROZEN — treat it as a file-format magic number. Both
 * marker injection (workspace_export writes) and conflict detection
 * (the overwrite policy) read the one constant below, so the two sides
 * can never drift apart. The prose around the token may change; the token
 * itself must not.
 */
export const SELDON_GENERATED_MARKER = "@seldon-generated"

const MARKER_LINES = [
  SELDON_GENERATED_MARKER,
  "Generated by Seldon Factory. Do not edit — changes are overwritten on re-export.",
  "https://github.com/SeldonDigital/seldon",
]

/**
 * Comment syntaxes by extension. Extensions without a comment syntax (JSON,
 * binaries) return null — those files are covered by the manifest alone;
 * prepending anything would corrupt them.
 */
export function buildMarkerComment(filePath: string): string | null {
  const extension = filePath.slice(filePath.lastIndexOf(".")).toLowerCase()
  switch (extension) {
    case ".ts":
    case ".tsx":
    case ".js":
    case ".jsx":
    case ".css":
      return `/*\n * ${MARKER_LINES.join("\n * ")}\n */\n`
    case ".md":
    case ".html":
      return `<!--\n  ${MARKER_LINES.join("\n  ")}\n-->\n`
    default:
      return null
  }
}

/** The overwrite policy's ownership check: does this text carry the frozen token? */
export function hasGeneratedMarker(content: string): boolean {
  return content.includes(SELDON_GENERATED_MARKER)
}
