/**
 * Regenerates the `category-map.ts` file of every icon set from its
 * `index-all.ts` file.
 *
 * Each icon's category path comes from its import path inside `index-all.ts`:
 * `./{category}/{subcategory}/IconX` maps to `"{category}/{subcategory}"`.
 * The file location is the source for an icon's category.
 *
 * Run with: bun scripts/generate-mappings.ts
 *
 * The script validates every derived icon id against the set's
 * `{set}AllIconIds` array and every category path against `categoryPaths`
 * before writing. It prints a summary of added, removed, and changed entries
 * per set.
 */
import fs from "node:fs"
import path from "node:path"

import { categoryPaths } from "../packages/core/icon-sets/constants/categories"

const REPO_ROOT = path.resolve(import.meta.dir, "../..")
const CATALOG_DIR = path.join(REPO_ROOT, "packages/core/icon-sets/catalog")

/** Icon sets to process: catalog folder name -> icon id prefix. */
const ICON_SETS: Record<string, string> = {
  seldon: "seldon",
  material: "material",
  carbon: "carbon",
  lucide: "lucide",
}

const VALID_CATEGORY_PATHS = new Set<string>(categoryPaths)

const EXPORT_PATTERN = /^export \{ (\w+) \} from "\.\/(.+)\/\w+"$/

function lowerFirst(value: string): string {
  return value.charAt(0).toLowerCase() + value.slice(1)
}

/**
 * Derives an icon id from its exported component name.
 *
 * `IconMaterialFolderOpen` -> `material-folderOpen`
 * `IconSeldonAlignTop` -> `seldon-alignTop`
 * `IconSocialFacebook` (seldon, no set infix) -> `seldon-iconSocialFacebook`
 *
 * When the derived id is not registered but a single registered id matches
 * case-insensitively, that id wins. This covers ids whose casing differs from
 * the component name, such as `seldon-deviceTv` for `IconSeldonDeviceTV`.
 */
function deriveIconId(
  componentName: string,
  prefix: string,
  allIconIds: Set<string>,
): string {
  const setInfix = prefix.charAt(0).toUpperCase() + prefix.slice(1)
  const standardPrefix = `Icon${setInfix}`
  const derived = componentName.startsWith(standardPrefix)
    ? `${prefix}-${lowerFirst(componentName.slice(standardPrefix.length))}`
    : `${prefix}-${lowerFirst(componentName)}`

  if (allIconIds.has(derived)) {
    return derived
  }
  const caseMatches = [...allIconIds].filter(
    (id) => id.toLowerCase() === derived.toLowerCase(),
  )
  return caseMatches.length === 1 ? caseMatches[0] : derived
}

/** Parses the `{set}AllIconIds` array literal out of an index-all source. */
function parseAllIconIds(source: string, setFolder: string): Set<string> {
  const arrayPattern = new RegExp(
    `export const ${setFolder}AllIconIds[^=]*= \\[([\\s\\S]*?)\\] as const`,
  )
  const match = source.match(arrayPattern)
  if (!match) {
    throw new Error(`Could not find ${setFolder}AllIconIds array`)
  }
  const ids = new Set<string>()
  for (const idMatch of match[1].matchAll(/"([^"]+)"/g)) {
    ids.add(idMatch[1])
  }
  return ids
}

/** Reads the existing map's id -> category pairs for the change summary. */
function parseExistingMap(filePath: string): Map<string, string> {
  const entries = new Map<string, string>()
  if (!fs.existsSync(filePath)) {
    return entries
  }
  const source = fs.readFileSync(filePath, "utf8")
  // Prettier may wrap long entries, so allow whitespace and newlines between
  // the id, the path, and the cast.
  for (const match of source.matchAll(
    /"([^"]+)":\s+"([^"]+)" as IconCategoryPath,/g,
  )) {
    entries.set(match[1], match[2])
  }
  return entries
}

function generateMapSource(
  setFolder: string,
  entries: Map<string, string>,
): string {
  const sorted = [...entries.entries()].sort(([idA, pathA], [idB, pathB]) => {
    if (pathA !== pathB) return pathA.localeCompare(pathB)
    return idA.localeCompare(idB)
  })

  const lines = sorted.map(
    ([iconId, categoryPath]) =>
      `  "${iconId}": "${categoryPath}" as IconCategoryPath,`,
  )

  return `/**
 * Auto-generated icon category mapping for ${setFolder} icon set
 * Generated by: scripts/generate-mappings.ts
 * DO NOT EDIT MANUALLY - This file is generated from index-all.ts files
 *
 * Last generated: ${new Date().toISOString()}
 */
import type { IconId } from "@seldon/core/icon-sets"

import type { IconCategoryPath } from "../../constants/categories"

export const iconCategoryMapping: Partial<Record<IconId, IconCategoryPath>> = {
${lines.join("\n")}
} as const
`
}

function generateSet(setFolder: string, prefix: string): void {
  const indexAllPath = path.join(CATALOG_DIR, setFolder, "index-all.ts")
  const mapPath = path.join(CATALOG_DIR, setFolder, "category-map.ts")
  const source = fs.readFileSync(indexAllPath, "utf8")

  const allIconIds = parseAllIconIds(source, setFolder)
  const entries = new Map<string, string>()
  const problems: string[] = []

  for (const line of source.split("\n")) {
    const match = line.match(EXPORT_PATTERN)
    if (!match) continue

    const [, componentName, importDir] = match
    const iconId = deriveIconId(componentName, prefix, allIconIds)
    const categoryPath = importDir.split("/").slice(0, 2).join("/")

    if (!VALID_CATEGORY_PATHS.has(categoryPath)) {
      problems.push(`${iconId}: invalid category path "${categoryPath}"`)
      continue
    }
    if (!allIconIds.has(iconId)) {
      problems.push(
        `${componentName}: derived id "${iconId}" not in ${setFolder}AllIconIds`,
      )
      continue
    }
    if (entries.has(iconId)) {
      problems.push(`${iconId}: duplicate export`)
      continue
    }
    entries.set(iconId, categoryPath)
  }

  const missingIds = [...allIconIds].filter((id) => !entries.has(id))
  for (const id of missingIds) {
    problems.push(`${id}: in ${setFolder}AllIconIds but has no export`)
  }

  if (problems.length > 0) {
    console.error(`\n[${setFolder}] validation failed:`)
    for (const problem of problems) console.error(`  - ${problem}`)
    process.exitCode = 1
    return
  }

  const previous = parseExistingMap(mapPath)
  const added = [...entries.keys()].filter((id) => !previous.has(id))
  const removed = [...previous.keys()].filter((id) => !entries.has(id))
  const changed = [...entries.entries()].filter(
    ([id, categoryPath]) =>
      previous.has(id) && previous.get(id) !== categoryPath,
  )

  fs.writeFileSync(mapPath, generateMapSource(setFolder, entries))

  console.log(
    `[${setFolder}] ${entries.size} icons -> ${path.relative(REPO_ROOT, mapPath)}` +
      ` (+${added.length} added, -${removed.length} removed, ~${changed.length} recategorized)`,
  )
  for (const id of added) console.log(`  + ${id}: ${entries.get(id)}`)
  for (const id of removed) console.log(`  - ${id}: ${previous.get(id)}`)
  for (const [id, categoryPath] of changed) {
    console.log(`  ~ ${id}: ${previous.get(id)} -> ${categoryPath}`)
  }
}

for (const [setFolder, prefix] of Object.entries(ICON_SETS)) {
  generateSet(setFolder, prefix)
}
