import type { ComponentId } from "../constants"

export const COMPONENT_PREVIEW_FILES = {
  screen: "screen.jpg",
  themeSpec: "themeSpec.jpg",
  linksFooter: "linksFooter.jpg",
  calendar: "calendar.jpg",
  chart: "chart.jpg",
  smallMultiples: "smallMultiples.jpg",
  masterDetail: "masterDetail.jpg",
  panel: "panel.jpg",
  footer: "footer.jpg",
  sidebar: "sidebar.jpg",
  table: "table.jpg",
  widgetTodo: "widgetTodo.jpg",
  accordion: "accordion.jpg",
  activityTimeline: "activityTimeline.jpg",
  bar: "bar.jpg",
  carousel: "carousel.jpg",
  topbar: "topbar.jpg",
  cardStacked: "cardStacked.jpg",
  fieldset: "fieldset.jpg",
  filterBar: "filterBar.jpg",
  listStandard: "listStandard.jpg",
  menu: "menu.jpg",
  propertyGrid: "propertyGrid.jpg",
  empty: "empty.jpg",
  pagination: "pagination.jpg",
  progress: "progress.jpg",
  slider: "slider.jpg",
  stepper: "stepper.jpg",
  combobox: "combobox.jpg",
  articleCard: "articleCard.jpg",
  mediaCard: "mediaCard.jpg",
  notificationCard: "notificationCard.jpg",
  pricingCard: "pricingCard.jpg",
  productCard: "productCard.jpg",
  profileCard: "profileCard.jpg",
  statCard: "statCard.jpg",
  cta: "cta.jpg",
  subscribeCta: "subscribeCta.jpg",
  boldCta: "boldCta.jpg",
  joinCta: "joinCta.jpg",
  socialProofCta: "socialProofCta.jpg",
  typeSpecimen: "typeSpecimen.jpg",
  colorSpecimen: "colorSpecimen.jpg",
  ordinalSpecimen: "ordinalSpecimen.jpg",
  avatar: "avatar.jpg",
  badge: "badge.jpg",
  button: "button.jpg",
  calendarDay: "calendarDay.jpg",
  chip: "chip.jpg",
  colorChip: "colorChip.jpg",
  ordinalChip: "ordinalChip.jpg",
  formControl: "formControl.jpg",
  optionGroup: "optionGroup.jpg",
  header: "header.jpg",
  descriptionList: "descriptionList.jpg",
  item: "item.jpg",
  menuItem: "menuItem.jpg",
  message: "message.jpg",
  kbd: "kbd.jpg",
  metric: "metric.jpg",
  tooltip: "tooltip.jpg",
  comboboxField: "comboboxField.jpg",
  nav: "nav.jpg",
  list: "list.jpg",
  listItem: "listItem.jpg",
  paragraph: "paragraph.jpg",
  section: "section.jpg",
  select: "select.jpg",
  tableGrid: "tableGrid.jpg",
  hr: "hr.jpg",
  image: "image.jpg",
  skeleton: "skeleton.jpg",
  input: "input.jpg",
  legend: "legend.jpg",
  textarea: "textarea.jpg",
  toggleSwitch: "toggleSwitch.jpg",
  blockquote: "blockquote.jpg",
  cite: "cite.jpg",
  link: "link.jpg",
  text: "text.jpg",
  video: "video.jpg",
  resizable: "resizable.jpg",
  sandbox: "sandbox.jpg",
} as const satisfies Partial<Record<ComponentId, string>>

export const COMPONENT_PREVIEW_SKIPPED = [
  "tableHead",
  "tableBody",
  "tableData",
  "tableHeader",
  "tableRowData",
  "icon",
  "source",
  "track",
  "container",
  "frame",
] as const
